// MIR2 角色/账号存档的持久化格式。
//
// 对应 Delphi THumData（Common/Grobal2.pas:891-952）与 TAccountDBRecord（:987-993）。
// 原版是 ~3628 字节的定长二进制，改为 protobuf 后：
//   - 字段可演进（加字段不破坏旧档）
//   - 不再受"改背包长度就要重编三端"的约束（Grobal2.pas:808 的历史坑）
//
// ⚠️ 字段号一旦发布不得更改/复用，否则旧档解析错乱。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: storage/v1/character.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MinMax 对应原版打包进单个 DWord 的属性对（LoWord=下限，HiWord=上限）。
// 见 Common/Grobal2.pas:734-753 —— 原版战斗公式大量用 LoWord/HiWord 拆分，此处拆开存储。
type MinMax struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           uint32                 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint32                 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinMax) Reset() {
	*x = MinMax{}
	mi := &file_storage_v1_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinMax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinMax) ProtoMessage() {}

func (x *MinMax) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinMax.ProtoReflect.Descriptor instead.
func (*MinMax) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{0}
}

func (x *MinMax) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MinMax) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// Ability 对应 Delphi TAbility（Grobal2.pas:734-753，packed 50 字节）。
type Ability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Ac            *MinMax                `protobuf:"bytes,2,opt,name=ac,proto3" json:"ac,omitempty"`
	Mac           *MinMax                `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	Dc            *MinMax                `protobuf:"bytes,4,opt,name=dc,proto3" json:"dc,omitempty"`
	Mc            *MinMax                `protobuf:"bytes,5,opt,name=mc,proto3" json:"mc,omitempty"`
	Sc            *MinMax                `protobuf:"bytes,6,opt,name=sc,proto3" json:"sc,omitempty"`
	Hp            uint32                 `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            uint32                 `protobuf:"varint,8,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxHp         uint32                 `protobuf:"varint,9,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MaxMp         uint32                 `protobuf:"varint,10,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Exp           uint64                 `protobuf:"varint,11,opt,name=exp,proto3" json:"exp,omitempty"`
	MaxExp        uint64                 `protobuf:"varint,12,opt,name=max_exp,json=maxExp,proto3" json:"max_exp,omitempty"`
	Weight        uint32                 `protobuf:"varint,13,opt,name=weight,proto3" json:"weight,omitempty"`
	MaxWeight     uint32                 `protobuf:"varint,14,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	WearWeight    uint32                 `protobuf:"varint,15,opt,name=wear_weight,json=wearWeight,proto3" json:"wear_weight,omitempty"`
	MaxWearWeight uint32                 `protobuf:"varint,16,opt,name=max_wear_weight,json=maxWearWeight,proto3" json:"max_wear_weight,omitempty"`
	HandWeight    uint32                 `protobuf:"varint,17,opt,name=hand_weight,json=handWeight,proto3" json:"hand_weight,omitempty"`
	MaxHandWeight uint32                 `protobuf:"varint,18,opt,name=max_hand_weight,json=maxHandWeight,proto3" json:"max_hand_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ability) Reset() {
	*x = Ability{}
	mi := &file_storage_v1_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{1}
}

func (x *Ability) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Ability) GetAc() *MinMax {
	if x != nil {
		return x.Ac
	}
	return nil
}

func (x *Ability) GetMac() *MinMax {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *Ability) GetDc() *MinMax {
	if x != nil {
		return x.Dc
	}
	return nil
}

func (x *Ability) GetMc() *MinMax {
	if x != nil {
		return x.Mc
	}
	return nil
}

func (x *Ability) GetSc() *MinMax {
	if x != nil {
		return x.Sc
	}
	return nil
}

func (x *Ability) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Ability) GetMp() uint32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *Ability) GetMaxHp() uint32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Ability) GetMaxMp() uint32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *Ability) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Ability) GetMaxExp() uint64 {
	if x != nil {
		return x.MaxExp
	}
	return 0
}

func (x *Ability) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Ability) GetMaxWeight() uint32 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

func (x *Ability) GetWearWeight() uint32 {
	if x != nil {
		return x.WearWeight
	}
	return 0
}

func (x *Ability) GetMaxWearWeight() uint32 {
	if x != nil {
		return x.MaxWearWeight
	}
	return 0
}

func (x *Ability) GetHandWeight() uint32 {
	if x != nil {
		return x.HandWeight
	}
	return 0
}

func (x *Ability) GetMaxHandWeight() uint32 {
	if x != nil {
		return x.MaxHandWeight
	}
	return 0
}

// NakedAbility 对应 Delphi TNakedAbility（Grobal2.pas:662-673）。
type NakedAbility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dc            *MinMax                `protobuf:"bytes,1,opt,name=dc,proto3" json:"dc,omitempty"`
	Mc            *MinMax                `protobuf:"bytes,2,opt,name=mc,proto3" json:"mc,omitempty"`
	Sc            *MinMax                `protobuf:"bytes,3,opt,name=sc,proto3" json:"sc,omitempty"`
	Ac            *MinMax                `protobuf:"bytes,4,opt,name=ac,proto3" json:"ac,omitempty"`
	Mac           *MinMax                `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Hp            uint32                 `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            uint32                 `protobuf:"varint,7,opt,name=mp,proto3" json:"mp,omitempty"`
	Hit           uint32                 `protobuf:"varint,8,opt,name=hit,proto3" json:"hit,omitempty"`
	Speed         int32                  `protobuf:"varint,9,opt,name=speed,proto3" json:"speed,omitempty"`
	X2            uint32                 `protobuf:"varint,10,opt,name=x2,proto3" json:"x2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NakedAbility) Reset() {
	*x = NakedAbility{}
	mi := &file_storage_v1_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NakedAbility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NakedAbility) ProtoMessage() {}

func (x *NakedAbility) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NakedAbility.ProtoReflect.Descriptor instead.
func (*NakedAbility) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{2}
}

func (x *NakedAbility) GetDc() *MinMax {
	if x != nil {
		return x.Dc
	}
	return nil
}

func (x *NakedAbility) GetMc() *MinMax {
	if x != nil {
		return x.Mc
	}
	return nil
}

func (x *NakedAbility) GetSc() *MinMax {
	if x != nil {
		return x.Sc
	}
	return nil
}

func (x *NakedAbility) GetAc() *MinMax {
	if x != nil {
		return x.Ac
	}
	return nil
}

func (x *NakedAbility) GetMac() *MinMax {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *NakedAbility) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *NakedAbility) GetMp() uint32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *NakedAbility) GetHit() uint32 {
	if x != nil {
		return x.Hit
	}
	return 0
}

func (x *NakedAbility) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *NakedAbility) GetX2() uint32 {
	if x != nil {
		return x.X2
	}
	return 0
}

// UserItem 对应 Delphi TUserItem（Grobal2.pas:788-795，24 字节）。
type UserItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MakeIndex     int32                  `protobuf:"varint,1,opt,name=make_index,json=makeIndex,proto3" json:"make_index,omitempty"` // 物品唯一 ID（GetItemNumber 分配）
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                          // 物品模板索引（StdItem.Index，1-based）
	Dura          uint32                 `protobuf:"varint,3,opt,name=dura,proto3" json:"dura,omitempty"`
	DuraMax       uint32                 `protobuf:"varint,4,opt,name=dura_max,json=duraMax,proto3" json:"dura_max,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"` // 14 字节：附加属性与升级点数（btValue[0..13]）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserItem) Reset() {
	*x = UserItem{}
	mi := &file_storage_v1_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserItem) ProtoMessage() {}

func (x *UserItem) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserItem.ProtoReflect.Descriptor instead.
func (*UserItem) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{3}
}

func (x *UserItem) GetMakeIndex() int32 {
	if x != nil {
		return x.MakeIndex
	}
	return 0
}

func (x *UserItem) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UserItem) GetDura() uint32 {
	if x != nil {
		return x.Dura
	}
	return 0
}

func (x *UserItem) GetDuraMax() uint32 {
	if x != nil {
		return x.DuraMax
	}
	return 0
}

func (x *UserItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// UserMagic 对应 Delphi TUserMagic（Grobal2.pas:814-820）。
type UserMagic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 原版存的是 pTMagic 指针（落盘时无意义），改为存技能号（MagicID）。
	MagicId       uint32 `protobuf:"varint,1,opt,name=magic_id,json=magicId,proto3" json:"magic_id,omitempty"`
	Level         uint32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	MagIdx        uint32 `protobuf:"varint,3,opt,name=mag_idx,json=magIdx,proto3" json:"mag_idx,omitempty"`
	TranPoint     int32  `protobuf:"varint,4,opt,name=tran_point,json=tranPoint,proto3" json:"tran_point,omitempty"` // 修炼点
	Key           uint32 `protobuf:"varint,5,opt,name=key,proto3" json:"key,omitempty"`                              // 快捷键
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMagic) Reset() {
	*x = UserMagic{}
	mi := &file_storage_v1_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMagic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMagic) ProtoMessage() {}

func (x *UserMagic) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMagic.ProtoReflect.Descriptor instead.
func (*UserMagic) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{4}
}

func (x *UserMagic) GetMagicId() uint32 {
	if x != nil {
		return x.MagicId
	}
	return 0
}

func (x *UserMagic) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserMagic) GetMagIdx() uint32 {
	if x != nil {
		return x.MagIdx
	}
	return 0
}

func (x *UserMagic) GetTranPoint() int32 {
	if x != nil {
		return x.TranPoint
	}
	return 0
}

func (x *UserMagic) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

// CharacterData 对应 Delphi THumData（Grobal2.pas:891-952）。
//
// 高频查询字段（账号、角色名、等级、金币等）已提为 SQL 主表列，
// 此处只存"整块读写"的详情。见 docs/service-architecture.md。
type CharacterData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础
	ChrName string `protobuf:"bytes,1,opt,name=chr_name,json=chrName,proto3" json:"chr_name,omitempty"`
	CurMap  string `protobuf:"bytes,2,opt,name=cur_map,json=curMap,proto3" json:"cur_map,omitempty"`
	CurX    uint32 `protobuf:"varint,3,opt,name=cur_x,json=curX,proto3" json:"cur_x,omitempty"`
	CurY    uint32 `protobuf:"varint,4,opt,name=cur_y,json=curY,proto3" json:"cur_y,omitempty"`
	Dir     uint32 `protobuf:"varint,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Hair    uint32 `protobuf:"varint,6,opt,name=hair,proto3" json:"hair,omitempty"`
	Sex     uint32 `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Job     uint32 `protobuf:"varint,8,opt,name=job,proto3" json:"job,omitempty"`
	Gold    int64  `protobuf:"varint,9,opt,name=gold,proto3" json:"gold,omitempty"`
	// 能力与状态（status_time 长度 = MAX_STATUS_ATTRIBUTE = 12）
	Abil       *Ability `protobuf:"bytes,10,opt,name=abil,proto3" json:"abil,omitempty"`
	StatusTime []uint32 `protobuf:"varint,11,rep,packed,name=status_time,json=statusTime,proto3" json:"status_time,omitempty"`
	// 回城点
	HomeMap string `protobuf:"bytes,12,opt,name=home_map,json=homeMap,proto3" json:"home_map,omitempty"`
	HomeX   uint32 `protobuf:"varint,13,opt,name=home_x,json=homeX,proto3" json:"home_x,omitempty"`
	HomeY   uint32 `protobuf:"varint,14,opt,name=home_y,json=homeY,proto3" json:"home_y,omitempty"`
	// 加点
	BonusAbil   *NakedAbility `protobuf:"bytes,15,opt,name=bonus_abil,json=bonusAbil,proto3" json:"bonus_abil,omitempty"`
	BonusPoint  int64         `protobuf:"varint,16,opt,name=bonus_point,json=bonusPoint,proto3" json:"bonus_point,omitempty"`
	CreditPoint uint32        `protobuf:"varint,17,opt,name=credit_point,json=creditPoint,proto3" json:"credit_point,omitempty"`
	ReLevel     uint32        `protobuf:"varint,18,opt,name=re_level,json=reLevel,proto3" json:"re_level,omitempty"`
	// 元宝 / 点数
	StoragePwd   string `protobuf:"bytes,19,opt,name=storage_pwd,json=storagePwd,proto3" json:"storage_pwd,omitempty"`
	GameGold     int64  `protobuf:"varint,20,opt,name=game_gold,json=gameGold,proto3" json:"game_gold,omitempty"`
	GamePoint    int64  `protobuf:"varint,21,opt,name=game_point,json=gamePoint,proto3" json:"game_point,omitempty"`
	PaymentPoint int64  `protobuf:"varint,22,opt,name=payment_point,json=paymentPoint,proto3" json:"payment_point,omitempty"`
	PkPoint      int64  `protobuf:"varint,23,opt,name=pk_point,json=pkPoint,proto3" json:"pk_point,omitempty"`
	// 行为开关
	AllowGroup        bool   `protobuf:"varint,24,opt,name=allow_group,json=allowGroup,proto3" json:"allow_group,omitempty"`
	F9                uint32 `protobuf:"varint,25,opt,name=f9,proto3" json:"f9,omitempty"`
	AttackMode        uint32 `protobuf:"varint,26,opt,name=attack_mode,json=attackMode,proto3" json:"attack_mode,omitempty"`
	IncHealth         bool   `protobuf:"varint,27,opt,name=inc_health,json=incHealth,proto3" json:"inc_health,omitempty"`
	IncSpell          bool   `protobuf:"varint,28,opt,name=inc_spell,json=incSpell,proto3" json:"inc_spell,omitempty"`
	IncHealing        bool   `protobuf:"varint,29,opt,name=inc_healing,json=incHealing,proto3" json:"inc_healing,omitempty"`
	FightZoneDieCount uint32 `protobuf:"varint,30,opt,name=fight_zone_die_count,json=fightZoneDieCount,proto3" json:"fight_zone_die_count,omitempty"`
	Ee                bool   `protobuf:"varint,31,opt,name=ee,proto3" json:"ee,omitempty"`
	Ef                bool   `protobuf:"varint,32,opt,name=ef,proto3" json:"ef,omitempty"`
	// 归属与其它
	Account          string  `protobuf:"bytes,33,opt,name=account,proto3" json:"account,omitempty"`
	LockLogon        bool    `protobuf:"varint,34,opt,name=lock_logon,json=lockLogon,proto3" json:"lock_logon,omitempty"`
	Contribution     uint32  `protobuf:"varint,35,opt,name=contribution,proto3" json:"contribution,omitempty"`
	HungerStatus     int64   `protobuf:"varint,36,opt,name=hunger_status,json=hungerStatus,proto3" json:"hunger_status,omitempty"`
	AllowGuildRecall bool    `protobuf:"varint,37,opt,name=allow_guild_recall,json=allowGuildRecall,proto3" json:"allow_guild_recall,omitempty"`
	GroupRecallTime  uint32  `protobuf:"varint,38,opt,name=group_recall_time,json=groupRecallTime,proto3" json:"group_recall_time,omitempty"`
	BodyLuck         float64 `protobuf:"fixed64,39,opt,name=body_luck,json=bodyLuck,proto3" json:"body_luck,omitempty"` // 原版 TDateTime（Double）
	AllowGroupRecall bool    `protobuf:"varint,40,opt,name=allow_group_recall,json=allowGroupRecall,proto3" json:"allow_group_recall,omitempty"`
	// 任务标志，原版各为 array[0..127] of Byte
	QuestUnitOpen []byte `protobuf:"bytes,41,opt,name=quest_unit_open,json=questUnitOpen,proto3" json:"quest_unit_open,omitempty"`
	QuestUnit     []byte `protobuf:"bytes,42,opt,name=quest_unit,json=questUnit,proto3" json:"quest_unit,omitempty"`
	QuestFlag     []byte `protobuf:"bytes,43,opt,name=quest_flag,json=questFlag,proto3" json:"quest_flag,omitempty"`
	// 物品与技能（数量：装备 13 / 背包 46 / 技能 20 / 仓库 50）
	HumItems      []*UserItem  `protobuf:"bytes,44,rep,name=hum_items,json=humItems,proto3" json:"hum_items,omitempty"`
	BagItems      []*UserItem  `protobuf:"bytes,45,rep,name=bag_items,json=bagItems,proto3" json:"bag_items,omitempty"`
	Magics        []*UserMagic `protobuf:"bytes,46,rep,name=magics,proto3" json:"magics,omitempty"`
	StorageItems  []*UserItem  `protobuf:"bytes,47,rep,name=storage_items,json=storageItems,proto3" json:"storage_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterData) Reset() {
	*x = CharacterData{}
	mi := &file_storage_v1_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterData) ProtoMessage() {}

func (x *CharacterData) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterData.ProtoReflect.Descriptor instead.
func (*CharacterData) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterData) GetChrName() string {
	if x != nil {
		return x.ChrName
	}
	return ""
}

func (x *CharacterData) GetCurMap() string {
	if x != nil {
		return x.CurMap
	}
	return ""
}

func (x *CharacterData) GetCurX() uint32 {
	if x != nil {
		return x.CurX
	}
	return 0
}

func (x *CharacterData) GetCurY() uint32 {
	if x != nil {
		return x.CurY
	}
	return 0
}

func (x *CharacterData) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *CharacterData) GetHair() uint32 {
	if x != nil {
		return x.Hair
	}
	return 0
}

func (x *CharacterData) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CharacterData) GetJob() uint32 {
	if x != nil {
		return x.Job
	}
	return 0
}

func (x *CharacterData) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *CharacterData) GetAbil() *Ability {
	if x != nil {
		return x.Abil
	}
	return nil
}

func (x *CharacterData) GetStatusTime() []uint32 {
	if x != nil {
		return x.StatusTime
	}
	return nil
}

func (x *CharacterData) GetHomeMap() string {
	if x != nil {
		return x.HomeMap
	}
	return ""
}

func (x *CharacterData) GetHomeX() uint32 {
	if x != nil {
		return x.HomeX
	}
	return 0
}

func (x *CharacterData) GetHomeY() uint32 {
	if x != nil {
		return x.HomeY
	}
	return 0
}

func (x *CharacterData) GetBonusAbil() *NakedAbility {
	if x != nil {
		return x.BonusAbil
	}
	return nil
}

func (x *CharacterData) GetBonusPoint() int64 {
	if x != nil {
		return x.BonusPoint
	}
	return 0
}

func (x *CharacterData) GetCreditPoint() uint32 {
	if x != nil {
		return x.CreditPoint
	}
	return 0
}

func (x *CharacterData) GetReLevel() uint32 {
	if x != nil {
		return x.ReLevel
	}
	return 0
}

func (x *CharacterData) GetStoragePwd() string {
	if x != nil {
		return x.StoragePwd
	}
	return ""
}

func (x *CharacterData) GetGameGold() int64 {
	if x != nil {
		return x.GameGold
	}
	return 0
}

func (x *CharacterData) GetGamePoint() int64 {
	if x != nil {
		return x.GamePoint
	}
	return 0
}

func (x *CharacterData) GetPaymentPoint() int64 {
	if x != nil {
		return x.PaymentPoint
	}
	return 0
}

func (x *CharacterData) GetPkPoint() int64 {
	if x != nil {
		return x.PkPoint
	}
	return 0
}

func (x *CharacterData) GetAllowGroup() bool {
	if x != nil {
		return x.AllowGroup
	}
	return false
}

func (x *CharacterData) GetF9() uint32 {
	if x != nil {
		return x.F9
	}
	return 0
}

func (x *CharacterData) GetAttackMode() uint32 {
	if x != nil {
		return x.AttackMode
	}
	return 0
}

func (x *CharacterData) GetIncHealth() bool {
	if x != nil {
		return x.IncHealth
	}
	return false
}

func (x *CharacterData) GetIncSpell() bool {
	if x != nil {
		return x.IncSpell
	}
	return false
}

func (x *CharacterData) GetIncHealing() bool {
	if x != nil {
		return x.IncHealing
	}
	return false
}

func (x *CharacterData) GetFightZoneDieCount() uint32 {
	if x != nil {
		return x.FightZoneDieCount
	}
	return 0
}

func (x *CharacterData) GetEe() bool {
	if x != nil {
		return x.Ee
	}
	return false
}

func (x *CharacterData) GetEf() bool {
	if x != nil {
		return x.Ef
	}
	return false
}

func (x *CharacterData) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CharacterData) GetLockLogon() bool {
	if x != nil {
		return x.LockLogon
	}
	return false
}

func (x *CharacterData) GetContribution() uint32 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *CharacterData) GetHungerStatus() int64 {
	if x != nil {
		return x.HungerStatus
	}
	return 0
}

func (x *CharacterData) GetAllowGuildRecall() bool {
	if x != nil {
		return x.AllowGuildRecall
	}
	return false
}

func (x *CharacterData) GetGroupRecallTime() uint32 {
	if x != nil {
		return x.GroupRecallTime
	}
	return 0
}

func (x *CharacterData) GetBodyLuck() float64 {
	if x != nil {
		return x.BodyLuck
	}
	return 0
}

func (x *CharacterData) GetAllowGroupRecall() bool {
	if x != nil {
		return x.AllowGroupRecall
	}
	return false
}

func (x *CharacterData) GetQuestUnitOpen() []byte {
	if x != nil {
		return x.QuestUnitOpen
	}
	return nil
}

func (x *CharacterData) GetQuestUnit() []byte {
	if x != nil {
		return x.QuestUnit
	}
	return nil
}

func (x *CharacterData) GetQuestFlag() []byte {
	if x != nil {
		return x.QuestFlag
	}
	return nil
}

func (x *CharacterData) GetHumItems() []*UserItem {
	if x != nil {
		return x.HumItems
	}
	return nil
}

func (x *CharacterData) GetBagItems() []*UserItem {
	if x != nil {
		return x.BagItems
	}
	return nil
}

func (x *CharacterData) GetMagics() []*UserMagic {
	if x != nil {
		return x.Magics
	}
	return nil
}

func (x *CharacterData) GetStorageItems() []*UserItem {
	if x != nil {
		return x.StorageItems
	}
	return nil
}

// AccountData 是账号的详情部分。
//
// 对应 Delphi TUserEntry（Grobal2.pas:592-601，148 字节）+
// TUserEntryAdd（:602-609，143 字节）。
// 账号名、密码哈希、错误计数等高频字段已提为 SQL 主表列。
type AccountData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` // 真实姓名
	SsNo          string                 `protobuf:"bytes,2,opt,name=ss_no,json=ssNo,proto3" json:"ss_no,omitempty"`             // 身份证号
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Quiz          string                 `protobuf:"bytes,4,opt,name=quiz,proto3" json:"quiz,omitempty"` // 密码提示问题 1
	Answer        string                 `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Quiz2         string                 `protobuf:"bytes,7,opt,name=quiz2,proto3" json:"quiz2,omitempty"` // 密码提示问题 2
	Answer2       string                 `protobuf:"bytes,8,opt,name=answer2,proto3" json:"answer2,omitempty"`
	BirthDay      string                 `protobuf:"bytes,9,opt,name=birth_day,json=birthDay,proto3" json:"birth_day,omitempty"`
	MobilePhone   string                 `protobuf:"bytes,10,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	Memo          string                 `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
	Memo2         string                 `protobuf:"bytes,12,opt,name=memo2,proto3" json:"memo2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountData) Reset() {
	*x = AccountData{}
	mi := &file_storage_v1_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountData) ProtoMessage() {}

func (x *AccountData) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountData.ProtoReflect.Descriptor instead.
func (*AccountData) Descriptor() ([]byte, []int) {
	return file_storage_v1_character_proto_rawDescGZIP(), []int{6}
}

func (x *AccountData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AccountData) GetSsNo() string {
	if x != nil {
		return x.SsNo
	}
	return ""
}

func (x *AccountData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AccountData) GetQuiz() string {
	if x != nil {
		return x.Quiz
	}
	return ""
}

func (x *AccountData) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AccountData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountData) GetQuiz2() string {
	if x != nil {
		return x.Quiz2
	}
	return ""
}

func (x *AccountData) GetAnswer2() string {
	if x != nil {
		return x.Answer2
	}
	return ""
}

func (x *AccountData) GetBirthDay() string {
	if x != nil {
		return x.BirthDay
	}
	return ""
}

func (x *AccountData) GetMobilePhone() string {
	if x != nil {
		return x.MobilePhone
	}
	return ""
}

func (x *AccountData) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *AccountData) GetMemo2() string {
	if x != nil {
		return x.Memo2
	}
	return ""
}

var File_storage_v1_character_proto protoreflect.FileDescriptor

const file_storage_v1_character_proto_rawDesc = "" +
	"\n" +
	"\x1astorage/v1/character.proto\x12\x11mir2go.storage.v1\",\n" +
	"\x06MinMax\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\"\xba\x04\n" +
	"\aAbility\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12)\n" +
	"\x02ac\x18\x02 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02ac\x12+\n" +
	"\x03mac\x18\x03 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x03mac\x12)\n" +
	"\x02dc\x18\x04 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02dc\x12)\n" +
	"\x02mc\x18\x05 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02mc\x12)\n" +
	"\x02sc\x18\x06 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02sc\x12\x0e\n" +
	"\x02hp\x18\a \x01(\rR\x02hp\x12\x0e\n" +
	"\x02mp\x18\b \x01(\rR\x02mp\x12\x15\n" +
	"\x06max_hp\x18\t \x01(\rR\x05maxHp\x12\x15\n" +
	"\x06max_mp\x18\n" +
	" \x01(\rR\x05maxMp\x12\x10\n" +
	"\x03exp\x18\v \x01(\x04R\x03exp\x12\x17\n" +
	"\amax_exp\x18\f \x01(\x04R\x06maxExp\x12\x16\n" +
	"\x06weight\x18\r \x01(\rR\x06weight\x12\x1d\n" +
	"\n" +
	"max_weight\x18\x0e \x01(\rR\tmaxWeight\x12\x1f\n" +
	"\vwear_weight\x18\x0f \x01(\rR\n" +
	"wearWeight\x12&\n" +
	"\x0fmax_wear_weight\x18\x10 \x01(\rR\rmaxWearWeight\x12\x1f\n" +
	"\vhand_weight\x18\x11 \x01(\rR\n" +
	"handWeight\x12&\n" +
	"\x0fmax_hand_weight\x18\x12 \x01(\rR\rmaxHandWeight\"\xbf\x02\n" +
	"\fNakedAbility\x12)\n" +
	"\x02dc\x18\x01 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02dc\x12)\n" +
	"\x02mc\x18\x02 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02mc\x12)\n" +
	"\x02sc\x18\x03 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02sc\x12)\n" +
	"\x02ac\x18\x04 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x02ac\x12+\n" +
	"\x03mac\x18\x05 \x01(\v2\x19.mir2go.storage.v1.MinMaxR\x03mac\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\rR\x02hp\x12\x0e\n" +
	"\x02mp\x18\a \x01(\rR\x02mp\x12\x10\n" +
	"\x03hit\x18\b \x01(\rR\x03hit\x12\x14\n" +
	"\x05speed\x18\t \x01(\x05R\x05speed\x12\x0e\n" +
	"\x02x2\x18\n" +
	" \x01(\rR\x02x2\"\x84\x01\n" +
	"\bUserItem\x12\x1d\n" +
	"\n" +
	"make_index\x18\x01 \x01(\x05R\tmakeIndex\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x12\n" +
	"\x04dura\x18\x03 \x01(\rR\x04dura\x12\x19\n" +
	"\bdura_max\x18\x04 \x01(\rR\aduraMax\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"\x86\x01\n" +
	"\tUserMagic\x12\x19\n" +
	"\bmagic_id\x18\x01 \x01(\rR\amagicId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x17\n" +
	"\amag_idx\x18\x03 \x01(\rR\x06magIdx\x12\x1d\n" +
	"\n" +
	"tran_point\x18\x04 \x01(\x05R\ttranPoint\x12\x10\n" +
	"\x03key\x18\x05 \x01(\rR\x03key\"\x9a\f\n" +
	"\rCharacterData\x12\x19\n" +
	"\bchr_name\x18\x01 \x01(\tR\achrName\x12\x17\n" +
	"\acur_map\x18\x02 \x01(\tR\x06curMap\x12\x13\n" +
	"\x05cur_x\x18\x03 \x01(\rR\x04curX\x12\x13\n" +
	"\x05cur_y\x18\x04 \x01(\rR\x04curY\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\rR\x03dir\x12\x12\n" +
	"\x04hair\x18\x06 \x01(\rR\x04hair\x12\x10\n" +
	"\x03sex\x18\a \x01(\rR\x03sex\x12\x10\n" +
	"\x03job\x18\b \x01(\rR\x03job\x12\x12\n" +
	"\x04gold\x18\t \x01(\x03R\x04gold\x12.\n" +
	"\x04abil\x18\n" +
	" \x01(\v2\x1a.mir2go.storage.v1.AbilityR\x04abil\x12\x1f\n" +
	"\vstatus_time\x18\v \x03(\rR\n" +
	"statusTime\x12\x19\n" +
	"\bhome_map\x18\f \x01(\tR\ahomeMap\x12\x15\n" +
	"\x06home_x\x18\r \x01(\rR\x05homeX\x12\x15\n" +
	"\x06home_y\x18\x0e \x01(\rR\x05homeY\x12>\n" +
	"\n" +
	"bonus_abil\x18\x0f \x01(\v2\x1f.mir2go.storage.v1.NakedAbilityR\tbonusAbil\x12\x1f\n" +
	"\vbonus_point\x18\x10 \x01(\x03R\n" +
	"bonusPoint\x12!\n" +
	"\fcredit_point\x18\x11 \x01(\rR\vcreditPoint\x12\x19\n" +
	"\bre_level\x18\x12 \x01(\rR\areLevel\x12\x1f\n" +
	"\vstorage_pwd\x18\x13 \x01(\tR\n" +
	"storagePwd\x12\x1b\n" +
	"\tgame_gold\x18\x14 \x01(\x03R\bgameGold\x12\x1d\n" +
	"\n" +
	"game_point\x18\x15 \x01(\x03R\tgamePoint\x12#\n" +
	"\rpayment_point\x18\x16 \x01(\x03R\fpaymentPoint\x12\x19\n" +
	"\bpk_point\x18\x17 \x01(\x03R\apkPoint\x12\x1f\n" +
	"\vallow_group\x18\x18 \x01(\bR\n" +
	"allowGroup\x12\x0e\n" +
	"\x02f9\x18\x19 \x01(\rR\x02f9\x12\x1f\n" +
	"\vattack_mode\x18\x1a \x01(\rR\n" +
	"attackMode\x12\x1d\n" +
	"\n" +
	"inc_health\x18\x1b \x01(\bR\tincHealth\x12\x1b\n" +
	"\tinc_spell\x18\x1c \x01(\bR\bincSpell\x12\x1f\n" +
	"\vinc_healing\x18\x1d \x01(\bR\n" +
	"incHealing\x12/\n" +
	"\x14fight_zone_die_count\x18\x1e \x01(\rR\x11fightZoneDieCount\x12\x0e\n" +
	"\x02ee\x18\x1f \x01(\bR\x02ee\x12\x0e\n" +
	"\x02ef\x18  \x01(\bR\x02ef\x12\x18\n" +
	"\aaccount\x18! \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"lock_logon\x18\" \x01(\bR\tlockLogon\x12\"\n" +
	"\fcontribution\x18# \x01(\rR\fcontribution\x12#\n" +
	"\rhunger_status\x18$ \x01(\x03R\fhungerStatus\x12,\n" +
	"\x12allow_guild_recall\x18% \x01(\bR\x10allowGuildRecall\x12*\n" +
	"\x11group_recall_time\x18& \x01(\rR\x0fgroupRecallTime\x12\x1b\n" +
	"\tbody_luck\x18' \x01(\x01R\bbodyLuck\x12,\n" +
	"\x12allow_group_recall\x18( \x01(\bR\x10allowGroupRecall\x12&\n" +
	"\x0fquest_unit_open\x18) \x01(\fR\rquestUnitOpen\x12\x1d\n" +
	"\n" +
	"quest_unit\x18* \x01(\fR\tquestUnit\x12\x1d\n" +
	"\n" +
	"quest_flag\x18+ \x01(\fR\tquestFlag\x128\n" +
	"\thum_items\x18, \x03(\v2\x1b.mir2go.storage.v1.UserItemR\bhumItems\x128\n" +
	"\tbag_items\x18- \x03(\v2\x1b.mir2go.storage.v1.UserItemR\bbagItems\x124\n" +
	"\x06magics\x18. \x03(\v2\x1c.mir2go.storage.v1.UserMagicR\x06magics\x12@\n" +
	"\rstorage_items\x18/ \x03(\v2\x1b.mir2go.storage.v1.UserItemR\fstorageItems\"\xb1\x02\n" +
	"\vAccountData\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x13\n" +
	"\x05ss_no\x18\x02 \x01(\tR\x04ssNo\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04quiz\x18\x04 \x01(\tR\x04quiz\x12\x16\n" +
	"\x06answer\x18\x05 \x01(\tR\x06answer\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05quiz2\x18\a \x01(\tR\x05quiz2\x12\x18\n" +
	"\aanswer2\x18\b \x01(\tR\aanswer2\x12\x1b\n" +
	"\tbirth_day\x18\t \x01(\tR\bbirthDay\x12!\n" +
	"\fmobile_phone\x18\n" +
	" \x01(\tR\vmobilePhone\x12\x12\n" +
	"\x04memo\x18\v \x01(\tR\x04memo\x12\x14\n" +
	"\x05memo2\x18\f \x01(\tR\x05memo2B4Z2github.com/algotao/mir2/server/internal/storage/pbb\x06proto3"

var (
	file_storage_v1_character_proto_rawDescOnce sync.Once
	file_storage_v1_character_proto_rawDescData []byte
)

func file_storage_v1_character_proto_rawDescGZIP() []byte {
	file_storage_v1_character_proto_rawDescOnce.Do(func() {
		file_storage_v1_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_character_proto_rawDesc), len(file_storage_v1_character_proto_rawDesc)))
	})
	return file_storage_v1_character_proto_rawDescData
}

var file_storage_v1_character_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_storage_v1_character_proto_goTypes = []any{
	(*MinMax)(nil),        // 0: mir2go.storage.v1.MinMax
	(*Ability)(nil),       // 1: mir2go.storage.v1.Ability
	(*NakedAbility)(nil),  // 2: mir2go.storage.v1.NakedAbility
	(*UserItem)(nil),      // 3: mir2go.storage.v1.UserItem
	(*UserMagic)(nil),     // 4: mir2go.storage.v1.UserMagic
	(*CharacterData)(nil), // 5: mir2go.storage.v1.CharacterData
	(*AccountData)(nil),   // 6: mir2go.storage.v1.AccountData
}
var file_storage_v1_character_proto_depIdxs = []int32{
	0,  // 0: mir2go.storage.v1.Ability.ac:type_name -> mir2go.storage.v1.MinMax
	0,  // 1: mir2go.storage.v1.Ability.mac:type_name -> mir2go.storage.v1.MinMax
	0,  // 2: mir2go.storage.v1.Ability.dc:type_name -> mir2go.storage.v1.MinMax
	0,  // 3: mir2go.storage.v1.Ability.mc:type_name -> mir2go.storage.v1.MinMax
	0,  // 4: mir2go.storage.v1.Ability.sc:type_name -> mir2go.storage.v1.MinMax
	0,  // 5: mir2go.storage.v1.NakedAbility.dc:type_name -> mir2go.storage.v1.MinMax
	0,  // 6: mir2go.storage.v1.NakedAbility.mc:type_name -> mir2go.storage.v1.MinMax
	0,  // 7: mir2go.storage.v1.NakedAbility.sc:type_name -> mir2go.storage.v1.MinMax
	0,  // 8: mir2go.storage.v1.NakedAbility.ac:type_name -> mir2go.storage.v1.MinMax
	0,  // 9: mir2go.storage.v1.NakedAbility.mac:type_name -> mir2go.storage.v1.MinMax
	1,  // 10: mir2go.storage.v1.CharacterData.abil:type_name -> mir2go.storage.v1.Ability
	2,  // 11: mir2go.storage.v1.CharacterData.bonus_abil:type_name -> mir2go.storage.v1.NakedAbility
	3,  // 12: mir2go.storage.v1.CharacterData.hum_items:type_name -> mir2go.storage.v1.UserItem
	3,  // 13: mir2go.storage.v1.CharacterData.bag_items:type_name -> mir2go.storage.v1.UserItem
	4,  // 14: mir2go.storage.v1.CharacterData.magics:type_name -> mir2go.storage.v1.UserMagic
	3,  // 15: mir2go.storage.v1.CharacterData.storage_items:type_name -> mir2go.storage.v1.UserItem
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_storage_v1_character_proto_init() }
func file_storage_v1_character_proto_init() {
	if File_storage_v1_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_character_proto_rawDesc), len(file_storage_v1_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_v1_character_proto_goTypes,
		DependencyIndexes: file_storage_v1_character_proto_depIdxs,
		MessageInfos:      file_storage_v1_character_proto_msgTypes,
	}.Build()
	File_storage_v1_character_proto = out.File
	file_storage_v1_character_proto_goTypes = nil
	file_storage_v1_character_proto_depIdxs = nil
}
