// MIR2 协议 · 0x02xx 账号 / 0x03xx 角色
//
// 对应 docs/protocol.md §5：登录 → 列角色 → 选角（★ 服务端在此申请**角色租约**）。
// ⚠️ 租约被占（同角色在线）⇒ **明确拒绝**，不要"顶号"式静默踢人（D-13）。
// ⚠️ `accountsvc` 不对客户端 Listen；这些消息由 `gamesvr` 作为唯一对端处理（D-13）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: account.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginCode int32

const (
	LoginCode_LOGIN_CODE_UNSPECIFIED  LoginCode = 0
	LoginCode_LOGIN_OK                LoginCode = 1
	LoginCode_LOGIN_BAD_CREDENTIALS   LoginCode = 2
	LoginCode_LOGIN_ACCOUNT_NOT_FOUND LoginCode = 3 // ⚠️ 与 BAD_CREDENTIALS 同义：**不区分**账号是否存在
	LoginCode_LOGIN_LOCKED            LoginCode = 6 // 口令错误次数过多，暂时锁定
	LoginCode_LOGIN_ALREADY_ONLINE    LoginCode = 4
	LoginCode_LOGIN_SERVER_FULL       LoginCode = 5
)

// Enum value maps for LoginCode.
var (
	LoginCode_name = map[int32]string{
		0: "LOGIN_CODE_UNSPECIFIED",
		1: "LOGIN_OK",
		2: "LOGIN_BAD_CREDENTIALS",
		3: "LOGIN_ACCOUNT_NOT_FOUND",
		6: "LOGIN_LOCKED",
		4: "LOGIN_ALREADY_ONLINE",
		5: "LOGIN_SERVER_FULL",
	}
	LoginCode_value = map[string]int32{
		"LOGIN_CODE_UNSPECIFIED":  0,
		"LOGIN_OK":                1,
		"LOGIN_BAD_CREDENTIALS":   2,
		"LOGIN_ACCOUNT_NOT_FOUND": 3,
		"LOGIN_LOCKED":            6,
		"LOGIN_ALREADY_ONLINE":    4,
		"LOGIN_SERVER_FULL":       5,
	}
)

func (x LoginCode) Enum() *LoginCode {
	p := new(LoginCode)
	*p = x
	return p
}

func (x LoginCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginCode) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[0].Descriptor()
}

func (LoginCode) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[0]
}

func (x LoginCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginCode.Descriptor instead.
func (LoginCode) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

type SelectCharCode int32

const (
	SelectCharCode_SELECT_CHAR_CODE_UNSPECIFIED SelectCharCode = 0
	SelectCharCode_SELECT_CHAR_OK               SelectCharCode = 1
	SelectCharCode_SELECT_CHAR_NOT_FOUND        SelectCharCode = 2
	SelectCharCode_SELECT_CHAR_LEASE_HELD       SelectCharCode = 3 // ★ 该角色已被占用（租约）——明确拒绝，不顶号
	SelectCharCode_SELECT_CHAR_SERVER_BUSY      SelectCharCode = 4
)

// Enum value maps for SelectCharCode.
var (
	SelectCharCode_name = map[int32]string{
		0: "SELECT_CHAR_CODE_UNSPECIFIED",
		1: "SELECT_CHAR_OK",
		2: "SELECT_CHAR_NOT_FOUND",
		3: "SELECT_CHAR_LEASE_HELD",
		4: "SELECT_CHAR_SERVER_BUSY",
	}
	SelectCharCode_value = map[string]int32{
		"SELECT_CHAR_CODE_UNSPECIFIED": 0,
		"SELECT_CHAR_OK":               1,
		"SELECT_CHAR_NOT_FOUND":        2,
		"SELECT_CHAR_LEASE_HELD":       3,
		"SELECT_CHAR_SERVER_BUSY":      4,
	}
)

func (x SelectCharCode) Enum() *SelectCharCode {
	p := new(SelectCharCode)
	*p = x
	return p
}

func (x SelectCharCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectCharCode) Descriptor() protoreflect.EnumDescriptor {
	return file_account_proto_enumTypes[1].Descriptor()
}

func (SelectCharCode) Type() protoreflect.EnumType {
	return &file_account_proto_enumTypes[1]
}

func (x SelectCharCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectCharCode.Descriptor instead.
func (SelectCharCode) EnumDescriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

// 客户端 → 服务端：取登录要用的 KDF 参数。
//
// ⚠️ 这条往返是 **D-24①（挑战应答）** 的必需品：存储侧是 `PBKDF2(口令, 服务端随机盐)`，
// 客户端**拿不到盐就算不出服务端能校验的那个值**（这正是 D-24 卡住的地方）。
// 盐不是秘密 —— 标准做法（SCRAM/HTTP digest）都是明文下发它。
type LoginSaltRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSaltRequest) Reset() {
	*x = LoginSaltRequest{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSaltRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSaltRequest) ProtoMessage() {}

func (x *LoginSaltRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSaltRequest.ProtoReflect.Descriptor instead.
func (*LoginSaltRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *LoginSaltRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 服务端 → 客户端：KDF 参数。
//
// ⚠️ 三个数必须与**存储侧**当前用的完全一致（`storage/password.go` 的 pwIterations 等），
// 否则客户端算出来的 `K` 与服务端存的对不上。所以由服务端下发，客户端**不许写死**
// —— 将来调迭代次数时，只有服务端要改。
type LoginSalt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salt          []byte                 `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Iterations    uint32                 `protobuf:"varint,2,opt,name=iterations,proto3" json:"iterations,omitempty"`
	KeyLen        uint32                 `protobuf:"varint,3,opt,name=key_len,json=keyLen,proto3" json:"key_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginSalt) Reset() {
	*x = LoginSalt{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginSalt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginSalt) ProtoMessage() {}

func (x *LoginSalt) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginSalt.ProtoReflect.Descriptor instead.
func (*LoginSalt) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *LoginSalt) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *LoginSalt) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *LoginSalt) GetKeyLen() uint32 {
	if x != nil {
		return x.KeyLen
	}
	return 0
}

type Login struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// 口令的**证明**，不是口令、也不是口令的等价物：
	//
	//    password_hash = hex( HMAC-SHA256( K, nonce ‖ account ) )
	//    K            = PBKDF2-SHA256(口令, salt, iterations, key_len)   ← 三个参数由 LoginSalt 下发
	//    nonce        = 握手时 ServerHello.session_key（每条连接一次性的随机值）
	//
	// ⚠️ 三个「不落网络」：明文不落、`K`（等价口令）不落、连证明本身也**绑在这条连接的
	// 一次性 nonce 上** —— 嗅到也重放不了（D-24①）。
	// 字段名保持 `password_hash` 是历史包袱（IDL 先写的），语义以这里为准。
	PasswordHash  string `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	ClientBuild   string `protobuf:"bytes,3,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *Login) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Login) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *Login) GetClientBuild() string {
	if x != nil {
		return x.ClientBuild
	}
	return ""
}

type LoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          LoginCode              `protobuf:"varint,1,opt,name=code,proto3,enum=mir2.LoginCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionToken  []byte                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // ★ 独立于 TCP 连接（protocol.md §5）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResult) GetCode() LoginCode {
	if x != nil {
		return x.Code
	}
	return LoginCode_LOGIN_CODE_UNSPECIFIED
}

func (x *LoginResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResult) GetSessionToken() []byte {
	if x != nil {
		return x.SessionToken
	}
	return nil
}

type ChangePassword struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Account         string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	OldPasswordHash string                 `protobuf:"bytes,2,opt,name=old_password_hash,json=oldPasswordHash,proto3" json:"old_password_hash,omitempty"`
	NewPasswordHash string                 `protobuf:"bytes,3,opt,name=new_password_hash,json=newPasswordHash,proto3" json:"new_password_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePassword) Reset() {
	*x = ChangePassword{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePassword) ProtoMessage() {}

func (x *ChangePassword) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePassword.ProtoReflect.Descriptor instead.
func (*ChangePassword) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePassword) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ChangePassword) GetOldPasswordHash() string {
	if x != nil {
		return x.OldPasswordHash
	}
	return ""
}

func (x *ChangePassword) GetNewPasswordHash() string {
	if x != nil {
		return x.NewPasswordHash
	}
	return ""
}

type ChangePasswordResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ActionResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResult) Reset() {
	*x = ChangePasswordResult{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResult) ProtoMessage() {}

func (x *ChangePasswordResult) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResult.ProtoReflect.Descriptor instead.
func (*ChangePasswordResult) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordResult) GetResult() *ActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 客户端 → 服务端：**创建账号**（D-32）。
//
// 用法（**必须**先走一次 D-24① 的取盐）：
//
//	① LoginSaltRequest{account} → LoginSalt{salt, iterations, key_len}
//	② K = PBKDF2-SHA256(口令, salt, iterations, key_len)
//	③ CreateAccount{account, verifier: hex(K)}
//
// ⚠️ **这里必须把 `K` 本身送过去** —— 建号时服务端手里什么都没有，它得拿到一个
// "以后能用来验登录"的值才能落库（登录侧是拿存着的 K 重算 HMAC 证明来比对）。
// 因此**建号那一次**的 verifier 就是口令的等价物：D-24 说的"等价物不落网络"只对
// **登录**成立；建号这条链的机密性是连接级的（明文仍不落网络）。
//
// ⚠️ 盐由**服务端**在上一步给出并留存（`protoSession.pendingSalt`），客户端不许自带 ——
// 否则盐就成了客户端可控的东西，而盐的意义正是"服务端随机"。
type CreateAccount struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// hex( K )，K = PBKDF2-SHA256(口令, salt, iterations, key_len)
	Verifier      string `protobuf:"bytes,2,opt,name=verifier,proto3" json:"verifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccount) Reset() {
	*x = CreateAccount{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount) ProtoMessage() {}

func (x *CreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount.ProtoReflect.Descriptor instead.
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccount) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateAccount) GetVerifier() string {
	if x != nil {
		return x.Verifier
	}
	return ""
}

// 服务端 → 客户端：建号结果。
//
// `result.code`：
//
//	0 = 成功
//	1 = 账号已存在（原版 `SM_NEWID_FAIL` 的 nErrCode=0）
//	2 = 账号名不合规（3..14 位，仅 [a-z0-9_]）
//	3 = 本服未开放注册（`-allow-new-account` 关着）
//	4 = 操作过快（同一 IP 5 秒一次，原版是每连接 5 秒）
//	5 = 服务器暂时建不了（存储错误）
//	6 = 没先取盐（缺 KDF 盐 ⇒ 无法落库）
//
// ⚠️ **没有"口令不合规"这一码**：服务端只收到 `verifier`，从来见不到口令 ⇒
// 口令长度/强度只能由客户端把关（原版服务端同样不查口令 ——
// `LMain.pas:1019-1079` 的 `AccountCreate` 只查账号名与重名）。这是挑战应答
// 必然的代价，写在这里免得以后有人来找"服务端怎么不校验口令"。
//
// ⚠️ 成功了也**不自动登录**（原版 `SM_NEWID_SUCCESS` 只是弹个提示，
// 见 `ClMain.pas:3684-3691`）—— 客户端要把人送回登录框自己登。
type CreateAccountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ActionResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResult) Reset() {
	*x = CreateAccountResult{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResult) ProtoMessage() {}

func (x *CreateAccountResult) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResult.ProtoReflect.Descriptor instead.
func (*CreateAccountResult) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAccountResult) GetResult() *ActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// 角色摘要（选角列表用；不含完整存档）。
type CharacterSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class         CharClass              `protobuf:"varint,3,opt,name=class,proto3,enum=mir2.CharClass" json:"class,omitempty"`
	Gender        Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=mir2.Gender" json:"gender,omitempty"`
	Level         uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	GenderHair    uint32                 `protobuf:"varint,6,opt,name=gender_hair,json=genderHair,proto3" json:"gender_hair,omitempty"` // 发型外观
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSummary) Reset() {
	*x = CharacterSummary{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSummary) ProtoMessage() {}

func (x *CharacterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSummary.ProtoReflect.Descriptor instead.
func (*CharacterSummary) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *CharacterSummary) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterSummary) GetClass() CharClass {
	if x != nil {
		return x.Class
	}
	return CharClass_CHAR_CLASS_UNSPECIFIED
}

func (x *CharacterSummary) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CharacterSummary) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterSummary) GetGenderHair() uint32 {
	if x != nil {
		return x.GenderHair
	}
	return 0
}

type ListCharacters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharacters) Reset() {
	*x = ListCharacters{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharacters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharacters) ProtoMessage() {}

func (x *ListCharacters) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharacters.ProtoReflect.Descriptor instead.
func (*ListCharacters) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

type CharacterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterSummary    `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterList) Reset() {
	*x = CharacterList{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterList) ProtoMessage() {}

func (x *CharacterList) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterList.ProtoReflect.Descriptor instead.
func (*CharacterList) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *CharacterList) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

type SelectCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectCharacter) Reset() {
	*x = SelectCharacter{}
	mi := &file_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectCharacter) ProtoMessage() {}

func (x *SelectCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectCharacter.ProtoReflect.Descriptor instead.
func (*SelectCharacter) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{11}
}

func (x *SelectCharacter) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type SelectCharacterResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          SelectCharCode         `protobuf:"varint,1,opt,name=code,proto3,enum=mir2.SelectCharCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CharacterId   uint64                 `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectCharacterResult) Reset() {
	*x = SelectCharacterResult{}
	mi := &file_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectCharacterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectCharacterResult) ProtoMessage() {}

func (x *SelectCharacterResult) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectCharacterResult.ProtoReflect.Descriptor instead.
func (*SelectCharacterResult) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{12}
}

func (x *SelectCharacterResult) GetCode() SelectCharCode {
	if x != nil {
		return x.Code
	}
	return SelectCharCode_SELECT_CHAR_CODE_UNSPECIFIED
}

func (x *SelectCharacterResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SelectCharacterResult) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type CreateCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class         CharClass              `protobuf:"varint,2,opt,name=class,proto3,enum=mir2.CharClass" json:"class,omitempty"`
	Gender        Gender                 `protobuf:"varint,3,opt,name=gender,proto3,enum=mir2.Gender" json:"gender,omitempty"`
	Hair          uint32                 `protobuf:"varint,4,opt,name=hair,proto3" json:"hair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacter) Reset() {
	*x = CreateCharacter{}
	mi := &file_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacter) ProtoMessage() {}

func (x *CreateCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacter.ProtoReflect.Descriptor instead.
func (*CreateCharacter) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCharacter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharacter) GetClass() CharClass {
	if x != nil {
		return x.Class
	}
	return CharClass_CHAR_CLASS_UNSPECIFIED
}

func (x *CreateCharacter) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CreateCharacter) GetHair() uint32 {
	if x != nil {
		return x.Hair
	}
	return 0
}

type CreateCharacterResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ActionResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	CharacterId   uint64                 `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"` // 成功时返回新角色 id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResult) Reset() {
	*x = CreateCharacterResult{}
	mi := &file_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResult) ProtoMessage() {}

func (x *CreateCharacterResult) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResult.ProtoReflect.Descriptor instead.
func (*CreateCharacterResult) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCharacterResult) GetResult() *ActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateCharacterResult) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint64                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"` // 二次确认
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacter) Reset() {
	*x = DeleteCharacter{}
	mi := &file_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacter) ProtoMessage() {}

func (x *DeleteCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacter.ProtoReflect.Descriptor instead.
func (*DeleteCharacter) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCharacter) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *DeleteCharacter) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type DeleteCharacterResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ActionResult          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResult) Reset() {
	*x = DeleteCharacterResult{}
	mi := &file_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResult) ProtoMessage() {}

func (x *DeleteCharacterResult) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResult.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResult) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCharacterResult) GetResult() *ActionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x04mir2\x1a\fcommon.proto\",\n" +
	"\x10LoginSaltRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"X\n" +
	"\tLoginSalt\x12\x12\n" +
	"\x04salt\x18\x01 \x01(\fR\x04salt\x12\x1e\n" +
	"\n" +
	"iterations\x18\x02 \x01(\rR\n" +
	"iterations\x12\x17\n" +
	"\akey_len\x18\x03 \x01(\rR\x06keyLen\"i\n" +
	"\x05Login\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12!\n" +
	"\fclient_build\x18\x03 \x01(\tR\vclientBuild\"q\n" +
	"\vLoginResult\x12#\n" +
	"\x04code\x18\x01 \x01(\x0e2\x0f.mir2.LoginCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsession_token\x18\x03 \x01(\fR\fsessionToken\"\x82\x01\n" +
	"\x0eChangePassword\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12*\n" +
	"\x11old_password_hash\x18\x02 \x01(\tR\x0foldPasswordHash\x12*\n" +
	"\x11new_password_hash\x18\x03 \x01(\tR\x0fnewPasswordHash\"B\n" +
	"\x14ChangePasswordResult\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.mir2.ActionResultR\x06result\"E\n" +
	"\rCreateAccount\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bverifier\x18\x02 \x01(\tR\bverifier\"A\n" +
	"\x13CreateAccountResult\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.mir2.ActionResultR\x06result\"\xcd\x01\n" +
	"\x10CharacterSummary\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x05class\x18\x03 \x01(\x0e2\x0f.mir2.CharClassR\x05class\x12$\n" +
	"\x06gender\x18\x04 \x01(\x0e2\f.mir2.GenderR\x06gender\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x1f\n" +
	"\vgender_hair\x18\x06 \x01(\rR\n" +
	"genderHair\"\x10\n" +
	"\x0eListCharacters\"G\n" +
	"\rCharacterList\x126\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x16.mir2.CharacterSummaryR\n" +
	"characters\"4\n" +
	"\x0fSelectCharacter\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\"~\n" +
	"\x15SelectCharacterResult\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.mir2.SelectCharCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x04R\vcharacterId\"\x86\x01\n" +
	"\x0fCreateCharacter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x05class\x18\x02 \x01(\x0e2\x0f.mir2.CharClassR\x05class\x12$\n" +
	"\x06gender\x18\x03 \x01(\x0e2\f.mir2.GenderR\x06gender\x12\x12\n" +
	"\x04hair\x18\x04 \x01(\rR\x04hair\"f\n" +
	"\x15CreateCharacterResult\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.mir2.ActionResultR\x06result\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x04R\vcharacterId\"Y\n" +
	"\x0fDeleteCharacter\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x04R\vcharacterId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"C\n" +
	"\x15DeleteCharacterResult\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.mir2.ActionResultR\x06result*\xb0\x01\n" +
	"\tLoginCode\x12\x1a\n" +
	"\x16LOGIN_CODE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bLOGIN_OK\x10\x01\x12\x19\n" +
	"\x15LOGIN_BAD_CREDENTIALS\x10\x02\x12\x1b\n" +
	"\x17LOGIN_ACCOUNT_NOT_FOUND\x10\x03\x12\x10\n" +
	"\fLOGIN_LOCKED\x10\x06\x12\x18\n" +
	"\x14LOGIN_ALREADY_ONLINE\x10\x04\x12\x15\n" +
	"\x11LOGIN_SERVER_FULL\x10\x05*\x9a\x01\n" +
	"\x0eSelectCharCode\x12 \n" +
	"\x1cSELECT_CHAR_CODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSELECT_CHAR_OK\x10\x01\x12\x19\n" +
	"\x15SELECT_CHAR_NOT_FOUND\x10\x02\x12\x1a\n" +
	"\x16SELECT_CHAR_LEASE_HELD\x10\x03\x12\x1b\n" +
	"\x17SELECT_CHAR_SERVER_BUSY\x10\x04B2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_account_proto_goTypes = []any{
	(LoginCode)(0),                // 0: mir2.LoginCode
	(SelectCharCode)(0),           // 1: mir2.SelectCharCode
	(*LoginSaltRequest)(nil),      // 2: mir2.LoginSaltRequest
	(*LoginSalt)(nil),             // 3: mir2.LoginSalt
	(*Login)(nil),                 // 4: mir2.Login
	(*LoginResult)(nil),           // 5: mir2.LoginResult
	(*ChangePassword)(nil),        // 6: mir2.ChangePassword
	(*ChangePasswordResult)(nil),  // 7: mir2.ChangePasswordResult
	(*CreateAccount)(nil),         // 8: mir2.CreateAccount
	(*CreateAccountResult)(nil),   // 9: mir2.CreateAccountResult
	(*CharacterSummary)(nil),      // 10: mir2.CharacterSummary
	(*ListCharacters)(nil),        // 11: mir2.ListCharacters
	(*CharacterList)(nil),         // 12: mir2.CharacterList
	(*SelectCharacter)(nil),       // 13: mir2.SelectCharacter
	(*SelectCharacterResult)(nil), // 14: mir2.SelectCharacterResult
	(*CreateCharacter)(nil),       // 15: mir2.CreateCharacter
	(*CreateCharacterResult)(nil), // 16: mir2.CreateCharacterResult
	(*DeleteCharacter)(nil),       // 17: mir2.DeleteCharacter
	(*DeleteCharacterResult)(nil), // 18: mir2.DeleteCharacterResult
	(*ActionResult)(nil),          // 19: mir2.ActionResult
	(CharClass)(0),                // 20: mir2.CharClass
	(Gender)(0),                   // 21: mir2.Gender
}
var file_account_proto_depIdxs = []int32{
	0,  // 0: mir2.LoginResult.code:type_name -> mir2.LoginCode
	19, // 1: mir2.ChangePasswordResult.result:type_name -> mir2.ActionResult
	19, // 2: mir2.CreateAccountResult.result:type_name -> mir2.ActionResult
	20, // 3: mir2.CharacterSummary.class:type_name -> mir2.CharClass
	21, // 4: mir2.CharacterSummary.gender:type_name -> mir2.Gender
	10, // 5: mir2.CharacterList.characters:type_name -> mir2.CharacterSummary
	1,  // 6: mir2.SelectCharacterResult.code:type_name -> mir2.SelectCharCode
	20, // 7: mir2.CreateCharacter.class:type_name -> mir2.CharClass
	21, // 8: mir2.CreateCharacter.gender:type_name -> mir2.Gender
	19, // 9: mir2.CreateCharacterResult.result:type_name -> mir2.ActionResult
	19, // 10: mir2.DeleteCharacterResult.result:type_name -> mir2.ActionResult
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		EnumInfos:         file_account_proto_enumTypes,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
