// MIR2 协议 · 0x06xx 战斗 / 0x07xx 技能
//
// 原版把一次攻击拆成 SM_HIT/SM_HEAVYHIT/SM_BIGHIT/SM_POWERHIT/SM_LONGHIT/SM_WIDEHIT…
// 十几个消息号；自研协议用 **一个 AttackInput + 一个 action 枚举**表达（protocol.md §10：
// 一个语义一个字段）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: combat.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 攻击动作（原版 SM_HIT=14 / SM_HEAVYHIT=15 / SM_BIGHIT=16 / SM_POWERHIT=18 /
// SM_LONGHIT=19 / SM_WIDEHIT=24 / SM_CRSHIT=25 / SM_TWINHIT=26 / SM_FIREHIT=8 …）
type AttackAction int32

const (
	AttackAction_ATTACK_ACTION_UNSPECIFIED AttackAction = 0
	AttackAction_ATTACK_HIT                AttackAction = 1 // 砍
	AttackAction_ATTACK_HEAVY              AttackAction = 2 // 重砍
	AttackAction_ATTACK_BIG                AttackAction = 3 // 大力
	AttackAction_ATTACK_POWER              AttackAction = 4 // 攻杀（战士技能）
	AttackAction_ATTACK_LONG               AttackAction = 5 // 刺杀
	AttackAction_ATTACK_WIDE               AttackAction = 6 // 半月
	AttackAction_ATTACK_FIRE               AttackAction = 7 // 烈火
	AttackAction_ATTACK_TWIN               AttackAction = 8
)

// Enum value maps for AttackAction.
var (
	AttackAction_name = map[int32]string{
		0: "ATTACK_ACTION_UNSPECIFIED",
		1: "ATTACK_HIT",
		2: "ATTACK_HEAVY",
		3: "ATTACK_BIG",
		4: "ATTACK_POWER",
		5: "ATTACK_LONG",
		6: "ATTACK_WIDE",
		7: "ATTACK_FIRE",
		8: "ATTACK_TWIN",
	}
	AttackAction_value = map[string]int32{
		"ATTACK_ACTION_UNSPECIFIED": 0,
		"ATTACK_HIT":                1,
		"ATTACK_HEAVY":              2,
		"ATTACK_BIG":                3,
		"ATTACK_POWER":              4,
		"ATTACK_LONG":               5,
		"ATTACK_WIDE":               6,
		"ATTACK_FIRE":               7,
		"ATTACK_TWIN":               8,
	}
)

func (x AttackAction) Enum() *AttackAction {
	p := new(AttackAction)
	*p = x
	return p
}

func (x AttackAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttackAction) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[0].Descriptor()
}

func (AttackAction) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[0]
}

func (x AttackAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttackAction.Descriptor instead.
func (AttackAction) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0}
}

// 客户端 → 服务端：攻击输入（★ 有且仅有一次生效）。
type AttackInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetEntityId uint64                 `protobuf:"varint,1,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	Action         AttackAction           `protobuf:"varint,2,opt,name=action,proto3,enum=mir2.AttackAction" json:"action,omitempty"`
	ClientTick     uint32                 `protobuf:"varint,3,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttackInput) Reset() {
	*x = AttackInput{}
	mi := &file_combat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackInput) ProtoMessage() {}

func (x *AttackInput) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackInput.ProtoReflect.Descriptor instead.
func (*AttackInput) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0}
}

func (x *AttackInput) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *AttackInput) GetAction() AttackAction {
	if x != nil {
		return x.Action
	}
	return AttackAction_ATTACK_ACTION_UNSPECIFIED
}

func (x *AttackInput) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type Damage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttackerId    uint64                 `protobuf:"varint,1,opt,name=attacker_id,json=attackerId,proto3" json:"attacker_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"` // 1=暴击 2=闪避 4=免疫 …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Damage) Reset() {
	*x = Damage{}
	mi := &file_combat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{1}
}

func (x *Damage) GetAttackerId() uint64 {
	if x != nil {
		return x.AttackerId
	}
	return 0
}

func (x *Damage) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Damage) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Damage) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type Death struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	KillerId      uint64                 `protobuf:"varint,2,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"` // 0 = 非玩家击杀
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Death) Reset() {
	*x = Death{}
	mi := &file_combat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Death) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Death) ProtoMessage() {}

func (x *Death) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Death.ProtoReflect.Descriptor instead.
func (*Death) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{2}
}

func (x *Death) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Death) GetKillerId() uint64 {
	if x != nil {
		return x.KillerId
	}
	return 0
}

type Revive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Hp            uint32                 `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revive) Reset() {
	*x = Revive{}
	mi := &file_combat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revive) ProtoMessage() {}

func (x *Revive) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revive.ProtoReflect.Descriptor instead.
func (*Revive) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{3}
}

func (x *Revive) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Revive) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Revive) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type ExperienceGain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"` // 本次获得
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`   // 累计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperienceGain) Reset() {
	*x = ExperienceGain{}
	mi := &file_combat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperienceGain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperienceGain) ProtoMessage() {}

func (x *ExperienceGain) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperienceGain.ProtoReflect.Descriptor instead.
func (*ExperienceGain) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{4}
}

func (x *ExperienceGain) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExperienceGain) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LevelUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Ability       *Ability               `protobuf:"bytes,2,opt,name=ability,proto3" json:"ability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUp) Reset() {
	*x = LevelUp{}
	mi := &file_combat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUp) ProtoMessage() {}

func (x *LevelUp) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUp.ProtoReflect.Descriptor instead.
func (*LevelUp) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{5}
}

func (x *LevelUp) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *LevelUp) GetAbility() *Ability {
	if x != nil {
		return x.Ability
	}
	return nil
}

// 客户端 → 服务端：施法输入。
type CastSkillInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SkillId        uint32                 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	TargetEntityId uint64                 `protobuf:"varint,2,opt,name=target_entity_id,json=targetEntityId,proto3" json:"target_entity_id,omitempty"`
	TargetPosition *Vec2                  `protobuf:"bytes,3,opt,name=target_position,json=targetPosition,proto3" json:"target_position,omitempty"`
	ClientTick     uint32                 `protobuf:"varint,4,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CastSkillInput) Reset() {
	*x = CastSkillInput{}
	mi := &file_combat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastSkillInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSkillInput) ProtoMessage() {}

func (x *CastSkillInput) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSkillInput.ProtoReflect.Descriptor instead.
func (*CastSkillInput) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{6}
}

func (x *CastSkillInput) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *CastSkillInput) GetTargetEntityId() uint64 {
	if x != nil {
		return x.TargetEntityId
	}
	return 0
}

func (x *CastSkillInput) GetTargetPosition() *Vec2 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *CastSkillInput) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

// 服务端 → 客户端：施法特效广播（原版 SM_MAGICFIRE / magiceff 的 15 个特效类 ⇒ 一个 id）。
type SkillEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CasterId      uint64                 `protobuf:"varint,1,opt,name=caster_id,json=casterId,proto3" json:"caster_id,omitempty"`
	SkillId       uint32                 `protobuf:"varint,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	TargetId      uint64                 `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillEffect) Reset() {
	*x = SkillEffect{}
	mi := &file_combat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillEffect) ProtoMessage() {}

func (x *SkillEffect) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillEffect.ProtoReflect.Descriptor instead.
func (*SkillEffect) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{7}
}

func (x *SkillEffect) GetCasterId() uint64 {
	if x != nil {
		return x.CasterId
	}
	return 0
}

func (x *SkillEffect) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *SkillEffect) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SkillEffect) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type MagicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       uint32                 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Exp           uint32                 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagicInfo) Reset() {
	*x = MagicInfo{}
	mi := &file_combat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicInfo) ProtoMessage() {}

func (x *MagicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicInfo.ProtoReflect.Descriptor instead.
func (*MagicInfo) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{8}
}

func (x *MagicInfo) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *MagicInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MagicInfo) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// 服务端 → 客户端：全量技能列表（取代原版 SM_SENDMYMAGIC）。
type MagicList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Magics        []*MagicInfo           `protobuf:"bytes,1,rep,name=magics,proto3" json:"magics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagicList) Reset() {
	*x = MagicList{}
	mi := &file_combat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicList) ProtoMessage() {}

func (x *MagicList) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicList.ProtoReflect.Descriptor instead.
func (*MagicList) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{9}
}

func (x *MagicList) GetMagics() []*MagicInfo {
	if x != nil {
		return x.Magics
	}
	return nil
}

// 增量变更（原版 SM_ADDMAGIC / SM_DELMAGIC 合并）。
type MagicChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         bool                   `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"` // true=新增/升级 false=删除
	Magic         *MagicInfo             `protobuf:"bytes,2,opt,name=magic,proto3" json:"magic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagicChanged) Reset() {
	*x = MagicChanged{}
	mi := &file_combat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagicChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicChanged) ProtoMessage() {}

func (x *MagicChanged) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicChanged.ProtoReflect.Descriptor instead.
func (*MagicChanged) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{10}
}

func (x *MagicChanged) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

func (x *MagicChanged) GetMagic() *MagicInfo {
	if x != nil {
		return x.Magic
	}
	return nil
}

type MagicLevelExp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       uint32                 `protobuf:"varint,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Level         uint32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Exp           uint32                 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagicLevelExp) Reset() {
	*x = MagicLevelExp{}
	mi := &file_combat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagicLevelExp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagicLevelExp) ProtoMessage() {}

func (x *MagicLevelExp) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagicLevelExp.ProtoReflect.Descriptor instead.
func (*MagicLevelExp) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{11}
}

func (x *MagicLevelExp) GetSkillId() uint32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *MagicLevelExp) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *MagicLevelExp) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_combat_proto protoreflect.FileDescriptor

const file_combat_proto_rawDesc = "" +
	"\n" +
	"\fcombat.proto\x12\x04mir2\x1a\fcommon.proto\"\x84\x01\n" +
	"\vAttackInput\x12(\n" +
	"\x10target_entity_id\x18\x01 \x01(\x04R\x0etargetEntityId\x12*\n" +
	"\x06action\x18\x02 \x01(\x0e2\x12.mir2.AttackActionR\x06action\x12\x1f\n" +
	"\vclient_tick\x18\x03 \x01(\rR\n" +
	"clientTick\"r\n" +
	"\x06Damage\x12\x1f\n" +
	"\vattacker_id\x18\x01 \x01(\x04R\n" +
	"attackerId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\"A\n" +
	"\x05Death\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1b\n" +
	"\tkiller_id\x18\x02 \x01(\x04R\bkillerId\"]\n" +
	"\x06Revive\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12&\n" +
	"\bposition\x18\x02 \x01(\v2\n" +
	".mir2.Vec2R\bposition\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\rR\x02hp\">\n" +
	"\x0eExperienceGain\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"H\n" +
	"\aLevelUp\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12'\n" +
	"\aability\x18\x02 \x01(\v2\r.mir2.AbilityR\aability\"\xab\x01\n" +
	"\x0eCastSkillInput\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\rR\askillId\x12(\n" +
	"\x10target_entity_id\x18\x02 \x01(\x04R\x0etargetEntityId\x123\n" +
	"\x0ftarget_position\x18\x03 \x01(\v2\n" +
	".mir2.Vec2R\x0etargetPosition\x12\x1f\n" +
	"\vclient_tick\x18\x04 \x01(\rR\n" +
	"clientTick\"\x8a\x01\n" +
	"\vSkillEffect\x12\x1b\n" +
	"\tcaster_id\x18\x01 \x01(\x04R\bcasterId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\rR\askillId\x12&\n" +
	"\bposition\x18\x03 \x01(\v2\n" +
	".mir2.Vec2R\bposition\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x04R\btargetId\"N\n" +
	"\tMagicInfo\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\rR\askillId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\rR\x03exp\"4\n" +
	"\tMagicList\x12'\n" +
	"\x06magics\x18\x01 \x03(\v2\x0f.mir2.MagicInfoR\x06magics\"K\n" +
	"\fMagicChanged\x12\x14\n" +
	"\x05added\x18\x01 \x01(\bR\x05added\x12%\n" +
	"\x05magic\x18\x02 \x01(\v2\x0f.mir2.MagicInfoR\x05magic\"R\n" +
	"\rMagicLevelExp\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\rR\askillId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\rR\x03exp*\xb5\x01\n" +
	"\fAttackAction\x12\x1d\n" +
	"\x19ATTACK_ACTION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ATTACK_HIT\x10\x01\x12\x10\n" +
	"\fATTACK_HEAVY\x10\x02\x12\x0e\n" +
	"\n" +
	"ATTACK_BIG\x10\x03\x12\x10\n" +
	"\fATTACK_POWER\x10\x04\x12\x0f\n" +
	"\vATTACK_LONG\x10\x05\x12\x0f\n" +
	"\vATTACK_WIDE\x10\x06\x12\x0f\n" +
	"\vATTACK_FIRE\x10\a\x12\x0f\n" +
	"\vATTACK_TWIN\x10\bB2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_combat_proto_rawDescOnce sync.Once
	file_combat_proto_rawDescData []byte
)

func file_combat_proto_rawDescGZIP() []byte {
	file_combat_proto_rawDescOnce.Do(func() {
		file_combat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_combat_proto_rawDesc), len(file_combat_proto_rawDesc)))
	})
	return file_combat_proto_rawDescData
}

var file_combat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_combat_proto_goTypes = []any{
	(AttackAction)(0),      // 0: mir2.AttackAction
	(*AttackInput)(nil),    // 1: mir2.AttackInput
	(*Damage)(nil),         // 2: mir2.Damage
	(*Death)(nil),          // 3: mir2.Death
	(*Revive)(nil),         // 4: mir2.Revive
	(*ExperienceGain)(nil), // 5: mir2.ExperienceGain
	(*LevelUp)(nil),        // 6: mir2.LevelUp
	(*CastSkillInput)(nil), // 7: mir2.CastSkillInput
	(*SkillEffect)(nil),    // 8: mir2.SkillEffect
	(*MagicInfo)(nil),      // 9: mir2.MagicInfo
	(*MagicList)(nil),      // 10: mir2.MagicList
	(*MagicChanged)(nil),   // 11: mir2.MagicChanged
	(*MagicLevelExp)(nil),  // 12: mir2.MagicLevelExp
	(*Vec2)(nil),           // 13: mir2.Vec2
	(*Ability)(nil),        // 14: mir2.Ability
}
var file_combat_proto_depIdxs = []int32{
	0,  // 0: mir2.AttackInput.action:type_name -> mir2.AttackAction
	13, // 1: mir2.Revive.position:type_name -> mir2.Vec2
	14, // 2: mir2.LevelUp.ability:type_name -> mir2.Ability
	13, // 3: mir2.CastSkillInput.target_position:type_name -> mir2.Vec2
	13, // 4: mir2.SkillEffect.position:type_name -> mir2.Vec2
	9,  // 5: mir2.MagicList.magics:type_name -> mir2.MagicInfo
	9,  // 6: mir2.MagicChanged.magic:type_name -> mir2.MagicInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_combat_proto_init() }
func file_combat_proto_init() {
	if File_combat_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_combat_proto_rawDesc), len(file_combat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_combat_proto_goTypes,
		DependencyIndexes: file_combat_proto_depIdxs,
		EnumInfos:         file_combat_proto_enumTypes,
		MessageInfos:      file_combat_proto_msgTypes,
	}.Build()
	File_combat_proto = out.File
	file_combat_proto_goTypes = nil
	file_combat_proto_depIdxs = nil
}
