// MIR2 协议 · 共享类型
//
// ⚠️ 硬规则（见 docs/protocol.md §4.1）
//  1. 字段号**全局唯一、永不复用**；避开 protobuf 保留区 19000–19999。
//  2. **禁止手写编解码**：两端都由本 schema 生成。
//  3. `oneof` 字段列表**只能**在 envelope.proto（无法跨文件扩展）。
//
// 说明：docs/protocol.md §3 的文件清单未列 common.proto；
//   共享类型（坐标/方向/实体外观）单独成文件，避免各处重复定义。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: common.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 8 方向。值 = **原版编号 + 1**（原版 0..7，见 GameOfMir `Common/Grobal2.pas:19-26`，
// 服务端侧对应 `entity.DirUp..DirUpLeft`）：
//
//	原版 0=上 1=右上 2=右 3=右下 4=下 5=左下 6=左 7=左上
//
// ⚠️ 曾经写反过：枚举按"下→逆时针"排（DIR_DOWN=1 …），注释却声称"沿用原版顺序"。
// 那种错**不会报错**，只会让每个实体的朝向差 4 个方向（上看起来是下）——
// 正是 §9 要防的"两端都以为自己对"。改这里 = 改线上的枚举值 ⇒ 必须 bump version.txt。
// 0 保留给"未指定"（原版 0 是"上"，所以这里**不能**直接照抄原版编号）。
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIR_UP                Direction = 1 // 原版 0
	Direction_DIR_UP_RIGHT          Direction = 2 // 原版 1
	Direction_DIR_RIGHT             Direction = 3 // 原版 2
	Direction_DIR_DOWN_RIGHT        Direction = 4 // 原版 3
	Direction_DIR_DOWN              Direction = 5 // 原版 4
	Direction_DIR_DOWN_LEFT         Direction = 6 // 原版 5
	Direction_DIR_LEFT              Direction = 7 // 原版 6
	Direction_DIR_UP_LEFT           Direction = 8 // 原版 7
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIR_UP",
		2: "DIR_UP_RIGHT",
		3: "DIR_RIGHT",
		4: "DIR_DOWN_RIGHT",
		5: "DIR_DOWN",
		6: "DIR_DOWN_LEFT",
		7: "DIR_LEFT",
		8: "DIR_UP_LEFT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIR_UP":                1,
		"DIR_UP_RIGHT":          2,
		"DIR_RIGHT":             3,
		"DIR_DOWN_RIGHT":        4,
		"DIR_DOWN":              5,
		"DIR_DOWN_LEFT":         6,
		"DIR_LEFT":              7,
		"DIR_UP_LEFT":           8,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 三职业（1.76 只有这三个）。
type CharClass int32

const (
	CharClass_CHAR_CLASS_UNSPECIFIED CharClass = 0
	CharClass_CHAR_CLASS_WARRIOR     CharClass = 1 // 战士
	CharClass_CHAR_CLASS_WIZARD      CharClass = 2 // 法师
	CharClass_CHAR_CLASS_TAOIST      CharClass = 3 // 道士
)

// Enum value maps for CharClass.
var (
	CharClass_name = map[int32]string{
		0: "CHAR_CLASS_UNSPECIFIED",
		1: "CHAR_CLASS_WARRIOR",
		2: "CHAR_CLASS_WIZARD",
		3: "CHAR_CLASS_TAOIST",
	}
	CharClass_value = map[string]int32{
		"CHAR_CLASS_UNSPECIFIED": 0,
		"CHAR_CLASS_WARRIOR":     1,
		"CHAR_CLASS_WIZARD":      2,
		"CHAR_CLASS_TAOIST":      3,
	}
)

func (x CharClass) Enum() *CharClass {
	p := new(CharClass)
	*p = x
	return p
}

func (x CharClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharClass) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (CharClass) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x CharClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharClass.Descriptor instead.
func (CharClass) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// 服务端权威的 2D 坐标（格）。
// ⚠️ 视野格数锁死（D-07）：分辨率可变，"看得到多少格"不可变。
type Vec2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Vec2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 通用「成功 / 失败」回执。用于一次性事务（丢弃、穿戴、购买…）。
// 原版把结果拆成 *_OK / *_FAIL 两条消息；自研协议合并为一条 + 一个 code。
type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"` // 0 = 成功；非 0 见各消息的注释
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ActionResult) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ActionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 实体外观（原版的 Feature 位打包：raceImg/weapon/hair/dress）。
// 用显式字段而不是位掩码 —— 位掩码是原版 bug 的来源之一。
type EntityFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaceImg       uint32                 `protobuf:"varint,1,opt,name=race_img,json=raceImg,proto3" json:"race_img,omitempty"`
	Weapon        uint32                 `protobuf:"varint,2,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Hair          uint32                 `protobuf:"varint,3,opt,name=hair,proto3" json:"hair,omitempty"`
	Dress         uint32                 `protobuf:"varint,4,opt,name=dress,proto3" json:"dress,omitempty"`
	Effect        uint32                 `protobuf:"varint,5,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityFeature) Reset() {
	*x = EntityFeature{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityFeature) ProtoMessage() {}

func (x *EntityFeature) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityFeature.ProtoReflect.Descriptor instead.
func (*EntityFeature) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *EntityFeature) GetRaceImg() uint32 {
	if x != nil {
		return x.RaceImg
	}
	return 0
}

func (x *EntityFeature) GetWeapon() uint32 {
	if x != nil {
		return x.Weapon
	}
	return 0
}

func (x *EntityFeature) GetHair() uint32 {
	if x != nil {
		return x.Hair
	}
	return 0
}

func (x *EntityFeature) GetDress() uint32 {
	if x != nil {
		return x.Dress
	}
	return 0
}

func (x *EntityFeature) GetEffect() uint32 {
	if x != nil {
		return x.Effect
	}
	return 0
}

// 能力值（原版 SM_ABILITY / TAbility）。
// 放在 common 而非 scene：scene（AbilityUpdate）与 combat（LevelUp）都要用。
type Ability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DcMin         uint32                 `protobuf:"varint,1,opt,name=dc_min,json=dcMin,proto3" json:"dc_min,omitempty"`
	DcMax         uint32                 `protobuf:"varint,2,opt,name=dc_max,json=dcMax,proto3" json:"dc_max,omitempty"`
	McMin         uint32                 `protobuf:"varint,3,opt,name=mc_min,json=mcMin,proto3" json:"mc_min,omitempty"`
	McMax         uint32                 `protobuf:"varint,4,opt,name=mc_max,json=mcMax,proto3" json:"mc_max,omitempty"`
	ScMin         uint32                 `protobuf:"varint,5,opt,name=sc_min,json=scMin,proto3" json:"sc_min,omitempty"`
	ScMax         uint32                 `protobuf:"varint,6,opt,name=sc_max,json=scMax,proto3" json:"sc_max,omitempty"`
	Ac            uint32                 `protobuf:"varint,7,opt,name=ac,proto3" json:"ac,omitempty"`
	Mac           uint32                 `protobuf:"varint,8,opt,name=mac,proto3" json:"mac,omitempty"`
	Hp            uint32                 `protobuf:"varint,9,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            uint32                 `protobuf:"varint,10,opt,name=mp,proto3" json:"mp,omitempty"`
	MaxHp         uint32                 `protobuf:"varint,11,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MaxMp         uint32                 `protobuf:"varint,12,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Weight        uint32                 `protobuf:"varint,13,opt,name=weight,proto3" json:"weight,omitempty"`
	MaxWeight     uint32                 `protobuf:"varint,14,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	WearWeight    uint32                 `protobuf:"varint,15,opt,name=wear_weight,json=wearWeight,proto3" json:"wear_weight,omitempty"`
	MaxWearWeight uint32                 `protobuf:"varint,16,opt,name=max_wear_weight,json=maxWearWeight,proto3" json:"max_wear_weight,omitempty"`
	Level         uint32                 `protobuf:"varint,17,opt,name=level,proto3" json:"level,omitempty"`
	Gold          uint64                 `protobuf:"varint,18,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ability) Reset() {
	*x = Ability{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Ability) GetDcMin() uint32 {
	if x != nil {
		return x.DcMin
	}
	return 0
}

func (x *Ability) GetDcMax() uint32 {
	if x != nil {
		return x.DcMax
	}
	return 0
}

func (x *Ability) GetMcMin() uint32 {
	if x != nil {
		return x.McMin
	}
	return 0
}

func (x *Ability) GetMcMax() uint32 {
	if x != nil {
		return x.McMax
	}
	return 0
}

func (x *Ability) GetScMin() uint32 {
	if x != nil {
		return x.ScMin
	}
	return 0
}

func (x *Ability) GetScMax() uint32 {
	if x != nil {
		return x.ScMax
	}
	return 0
}

func (x *Ability) GetAc() uint32 {
	if x != nil {
		return x.Ac
	}
	return 0
}

func (x *Ability) GetMac() uint32 {
	if x != nil {
		return x.Mac
	}
	return 0
}

func (x *Ability) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Ability) GetMp() uint32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *Ability) GetMaxHp() uint32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Ability) GetMaxMp() uint32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *Ability) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Ability) GetMaxWeight() uint32 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

func (x *Ability) GetWearWeight() uint32 {
	if x != nil {
		return x.WearWeight
	}
	return 0
}

func (x *Ability) GetMaxWearWeight() uint32 {
	if x != nil {
		return x.MaxWearWeight
	}
	return 0
}

func (x *Ability) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Ability) GetGold() uint64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x04mir2\"\"\n" +
	"\x04Vec2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"L\n" +
	"\fActionResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x84\x01\n" +
	"\rEntityFeature\x12\x19\n" +
	"\brace_img\x18\x01 \x01(\rR\araceImg\x12\x16\n" +
	"\x06weapon\x18\x02 \x01(\rR\x06weapon\x12\x12\n" +
	"\x04hair\x18\x03 \x01(\rR\x04hair\x12\x14\n" +
	"\x05dress\x18\x04 \x01(\rR\x05dress\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\rR\x06effect\"\xad\x03\n" +
	"\aAbility\x12\x15\n" +
	"\x06dc_min\x18\x01 \x01(\rR\x05dcMin\x12\x15\n" +
	"\x06dc_max\x18\x02 \x01(\rR\x05dcMax\x12\x15\n" +
	"\x06mc_min\x18\x03 \x01(\rR\x05mcMin\x12\x15\n" +
	"\x06mc_max\x18\x04 \x01(\rR\x05mcMax\x12\x15\n" +
	"\x06sc_min\x18\x05 \x01(\rR\x05scMin\x12\x15\n" +
	"\x06sc_max\x18\x06 \x01(\rR\x05scMax\x12\x0e\n" +
	"\x02ac\x18\a \x01(\rR\x02ac\x12\x10\n" +
	"\x03mac\x18\b \x01(\rR\x03mac\x12\x0e\n" +
	"\x02hp\x18\t \x01(\rR\x02hp\x12\x0e\n" +
	"\x02mp\x18\n" +
	" \x01(\rR\x02mp\x12\x15\n" +
	"\x06max_hp\x18\v \x01(\rR\x05maxHp\x12\x15\n" +
	"\x06max_mp\x18\f \x01(\rR\x05maxMp\x12\x16\n" +
	"\x06weight\x18\r \x01(\rR\x06weight\x12\x1d\n" +
	"\n" +
	"max_weight\x18\x0e \x01(\rR\tmaxWeight\x12\x1f\n" +
	"\vwear_weight\x18\x0f \x01(\rR\n" +
	"wearWeight\x12&\n" +
	"\x0fmax_wear_weight\x18\x10 \x01(\rR\rmaxWearWeight\x12\x14\n" +
	"\x05level\x18\x11 \x01(\rR\x05level\x12\x12\n" +
	"\x04gold\x18\x12 \x01(\x04R\x04gold*\xa7\x01\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DIR_UP\x10\x01\x12\x10\n" +
	"\fDIR_UP_RIGHT\x10\x02\x12\r\n" +
	"\tDIR_RIGHT\x10\x03\x12\x12\n" +
	"\x0eDIR_DOWN_RIGHT\x10\x04\x12\f\n" +
	"\bDIR_DOWN\x10\x05\x12\x11\n" +
	"\rDIR_DOWN_LEFT\x10\x06\x12\f\n" +
	"\bDIR_LEFT\x10\a\x12\x0f\n" +
	"\vDIR_UP_LEFT\x10\b*m\n" +
	"\tCharClass\x12\x1a\n" +
	"\x16CHAR_CLASS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CHAR_CLASS_WARRIOR\x10\x01\x12\x15\n" +
	"\x11CHAR_CLASS_WIZARD\x10\x02\x12\x15\n" +
	"\x11CHAR_CLASS_TAOIST\x10\x03*D\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02B2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(Direction)(0),        // 0: mir2.Direction
	(CharClass)(0),        // 1: mir2.CharClass
	(Gender)(0),           // 2: mir2.Gender
	(*Vec2)(nil),          // 3: mir2.Vec2
	(*ActionResult)(nil),  // 4: mir2.ActionResult
	(*EntityFeature)(nil), // 5: mir2.EntityFeature
	(*Ability)(nil),       // 6: mir2.Ability
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
