// MIR2 协议 · 信封 + oneof 消息总目录（★ 唯一集中点）
//
// 设计见 docs/protocol.md §2 / §4。
//
// 硬规则
//  1. **字段号即消息号**（D-16）：不设独立 `msg_id`。
//  2. 字段号**全局唯一、永不复用**；避开 protobuf 保留区 19000–19999。
//  3. `oneof` 无法跨文件扩展 ⇒ **所有消息的字段列表只能写在本文件**
//     （消息体仍按模块拆文件，见 §3）。这份列表就是"消息总目录"。
//  4. 收到未知消息时 oneof 的 case **未设置** ⇒ 显式处理 None：
//     记数 + 告警 + 忽略，**禁止 panic**。
//  5. 分帧：`[u32 length][Envelope]`，小端，length 不含自身，上限 64 KiB。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: envelope.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Seq       uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                              // 发送方单调递增
	AckSeq    uint32                 `protobuf:"varint,2,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`          // 已处理的对端 seq（输入确认）
	RequestId uint64                 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 一次性事务幂等键，缺省 0（protocol.md §6）
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_ClientHello
	//	*Envelope_ServerHello
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Disconnect
	//	*Envelope_ServerError
	//	*Envelope_Reconnect
	//	*Envelope_ReconnectResult
	//	*Envelope_Login
	//	*Envelope_LoginResult
	//	*Envelope_ChangePassword
	//	*Envelope_ChangePasswordResult
	//	*Envelope_LoginSaltRequest
	//	*Envelope_LoginSalt
	//	*Envelope_CreateAccount
	//	*Envelope_CreateAccountResult
	//	*Envelope_ListCharacters
	//	*Envelope_CharacterList
	//	*Envelope_SelectCharacter
	//	*Envelope_SelectCharacterResult
	//	*Envelope_CreateCharacter
	//	*Envelope_CreateCharacterResult
	//	*Envelope_DeleteCharacter
	//	*Envelope_DeleteCharacterResult
	//	*Envelope_EnterWorld
	//	*Envelope_ChangeMap
	//	*Envelope_MapChunk
	//	*Envelope_TimeOfDay
	//	*Envelope_MapDescription
	//	*Envelope_EntityAppear
	//	*Envelope_EntityDisappear
	//	*Envelope_EntityMove
	//	*Envelope_EntityAction
	//	*Envelope_EntityHealth
	//	*Envelope_EntityStatus
	//	*Envelope_AbilityUpdate
	//	*Envelope_MoveInput
	//	*Envelope_MoveRejected
	//	*Envelope_EntityFeatureChanged
	//	*Envelope_AttackInput
	//	*Envelope_Damage
	//	*Envelope_Death
	//	*Envelope_Revive
	//	*Envelope_ExperienceGain
	//	*Envelope_LevelUp
	//	*Envelope_CastSkillInput
	//	*Envelope_SkillEffect
	//	*Envelope_MagicList
	//	*Envelope_MagicChanged
	//	*Envelope_MagicLevelExp
	//	*Envelope_BagItems
	//	*Envelope_AddItem
	//	*Envelope_RemoveItem
	//	*Envelope_UpdateItem
	//	*Envelope_UseItem
	//	*Envelope_DropItem
	//	*Envelope_PickupItem
	//	*Envelope_GroundItemShow
	//	*Envelope_GroundItemHide
	//	*Envelope_EquipItem
	//	*Envelope_UnequipItem
	//	*Envelope_EquippedItems
	//	*Envelope_WeightChanged
	//	*Envelope_GoldChanged
	//	*Envelope_RepairItem
	//	*Envelope_RepairCostNotice
	//	*Envelope_ChatInput
	//	*Envelope_ChatMessage
	//	*Envelope_NpcClick
	//	*Envelope_NpcSay
	//	*Envelope_NpcSelect
	//	*Envelope_NpcClose
	//	*Envelope_Raw
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetAckSeq() uint32 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Envelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *Envelope) GetServerHello() *ServerHello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ServerHello); ok {
			return x.ServerHello
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *Envelope) GetServerError() *ServerError {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ServerError); ok {
			return x.ServerError
		}
	}
	return nil
}

func (x *Envelope) GetReconnect() *Reconnect {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Reconnect); ok {
			return x.Reconnect
		}
	}
	return nil
}

func (x *Envelope) GetReconnectResult() *ReconnectResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ReconnectResult); ok {
			return x.ReconnectResult
		}
	}
	return nil
}

func (x *Envelope) GetLogin() *Login {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *Envelope) GetLoginResult() *LoginResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LoginResult); ok {
			return x.LoginResult
		}
	}
	return nil
}

func (x *Envelope) GetChangePassword() *ChangePassword {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ChangePassword); ok {
			return x.ChangePassword
		}
	}
	return nil
}

func (x *Envelope) GetChangePasswordResult() *ChangePasswordResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ChangePasswordResult); ok {
			return x.ChangePasswordResult
		}
	}
	return nil
}

func (x *Envelope) GetLoginSaltRequest() *LoginSaltRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LoginSaltRequest); ok {
			return x.LoginSaltRequest
		}
	}
	return nil
}

func (x *Envelope) GetLoginSalt() *LoginSalt {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LoginSalt); ok {
			return x.LoginSalt
		}
	}
	return nil
}

func (x *Envelope) GetCreateAccount() *CreateAccount {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CreateAccount); ok {
			return x.CreateAccount
		}
	}
	return nil
}

func (x *Envelope) GetCreateAccountResult() *CreateAccountResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CreateAccountResult); ok {
			return x.CreateAccountResult
		}
	}
	return nil
}

func (x *Envelope) GetListCharacters() *ListCharacters {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ListCharacters); ok {
			return x.ListCharacters
		}
	}
	return nil
}

func (x *Envelope) GetCharacterList() *CharacterList {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CharacterList); ok {
			return x.CharacterList
		}
	}
	return nil
}

func (x *Envelope) GetSelectCharacter() *SelectCharacter {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SelectCharacter); ok {
			return x.SelectCharacter
		}
	}
	return nil
}

func (x *Envelope) GetSelectCharacterResult() *SelectCharacterResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SelectCharacterResult); ok {
			return x.SelectCharacterResult
		}
	}
	return nil
}

func (x *Envelope) GetCreateCharacter() *CreateCharacter {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CreateCharacter); ok {
			return x.CreateCharacter
		}
	}
	return nil
}

func (x *Envelope) GetCreateCharacterResult() *CreateCharacterResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CreateCharacterResult); ok {
			return x.CreateCharacterResult
		}
	}
	return nil
}

func (x *Envelope) GetDeleteCharacter() *DeleteCharacter {
	if x != nil {
		if x, ok := x.Body.(*Envelope_DeleteCharacter); ok {
			return x.DeleteCharacter
		}
	}
	return nil
}

func (x *Envelope) GetDeleteCharacterResult() *DeleteCharacterResult {
	if x != nil {
		if x, ok := x.Body.(*Envelope_DeleteCharacterResult); ok {
			return x.DeleteCharacterResult
		}
	}
	return nil
}

func (x *Envelope) GetEnterWorld() *EnterWorld {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EnterWorld); ok {
			return x.EnterWorld
		}
	}
	return nil
}

func (x *Envelope) GetChangeMap() *ChangeMap {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ChangeMap); ok {
			return x.ChangeMap
		}
	}
	return nil
}

func (x *Envelope) GetMapChunk() *MapChunk {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MapChunk); ok {
			return x.MapChunk
		}
	}
	return nil
}

func (x *Envelope) GetTimeOfDay() *TimeOfDay {
	if x != nil {
		if x, ok := x.Body.(*Envelope_TimeOfDay); ok {
			return x.TimeOfDay
		}
	}
	return nil
}

func (x *Envelope) GetMapDescription() *MapDescription {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MapDescription); ok {
			return x.MapDescription
		}
	}
	return nil
}

func (x *Envelope) GetEntityAppear() *EntityAppear {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityAppear); ok {
			return x.EntityAppear
		}
	}
	return nil
}

func (x *Envelope) GetEntityDisappear() *EntityDisappear {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityDisappear); ok {
			return x.EntityDisappear
		}
	}
	return nil
}

func (x *Envelope) GetEntityMove() *EntityMove {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityMove); ok {
			return x.EntityMove
		}
	}
	return nil
}

func (x *Envelope) GetEntityAction() *EntityAction {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityAction); ok {
			return x.EntityAction
		}
	}
	return nil
}

func (x *Envelope) GetEntityHealth() *EntityHealth {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityHealth); ok {
			return x.EntityHealth
		}
	}
	return nil
}

func (x *Envelope) GetEntityStatus() *EntityStatus {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityStatus); ok {
			return x.EntityStatus
		}
	}
	return nil
}

func (x *Envelope) GetAbilityUpdate() *AbilityUpdate {
	if x != nil {
		if x, ok := x.Body.(*Envelope_AbilityUpdate); ok {
			return x.AbilityUpdate
		}
	}
	return nil
}

func (x *Envelope) GetMoveInput() *MoveInput {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MoveInput); ok {
			return x.MoveInput
		}
	}
	return nil
}

func (x *Envelope) GetMoveRejected() *MoveRejected {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MoveRejected); ok {
			return x.MoveRejected
		}
	}
	return nil
}

func (x *Envelope) GetEntityFeatureChanged() *EntityFeatureChanged {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EntityFeatureChanged); ok {
			return x.EntityFeatureChanged
		}
	}
	return nil
}

func (x *Envelope) GetAttackInput() *AttackInput {
	if x != nil {
		if x, ok := x.Body.(*Envelope_AttackInput); ok {
			return x.AttackInput
		}
	}
	return nil
}

func (x *Envelope) GetDamage() *Damage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Damage); ok {
			return x.Damage
		}
	}
	return nil
}

func (x *Envelope) GetDeath() *Death {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Death); ok {
			return x.Death
		}
	}
	return nil
}

func (x *Envelope) GetRevive() *Revive {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Revive); ok {
			return x.Revive
		}
	}
	return nil
}

func (x *Envelope) GetExperienceGain() *ExperienceGain {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ExperienceGain); ok {
			return x.ExperienceGain
		}
	}
	return nil
}

func (x *Envelope) GetLevelUp() *LevelUp {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LevelUp); ok {
			return x.LevelUp
		}
	}
	return nil
}

func (x *Envelope) GetCastSkillInput() *CastSkillInput {
	if x != nil {
		if x, ok := x.Body.(*Envelope_CastSkillInput); ok {
			return x.CastSkillInput
		}
	}
	return nil
}

func (x *Envelope) GetSkillEffect() *SkillEffect {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SkillEffect); ok {
			return x.SkillEffect
		}
	}
	return nil
}

func (x *Envelope) GetMagicList() *MagicList {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MagicList); ok {
			return x.MagicList
		}
	}
	return nil
}

func (x *Envelope) GetMagicChanged() *MagicChanged {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MagicChanged); ok {
			return x.MagicChanged
		}
	}
	return nil
}

func (x *Envelope) GetMagicLevelExp() *MagicLevelExp {
	if x != nil {
		if x, ok := x.Body.(*Envelope_MagicLevelExp); ok {
			return x.MagicLevelExp
		}
	}
	return nil
}

func (x *Envelope) GetBagItems() *BagItems {
	if x != nil {
		if x, ok := x.Body.(*Envelope_BagItems); ok {
			return x.BagItems
		}
	}
	return nil
}

func (x *Envelope) GetAddItem() *AddItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_AddItem); ok {
			return x.AddItem
		}
	}
	return nil
}

func (x *Envelope) GetRemoveItem() *RemoveItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RemoveItem); ok {
			return x.RemoveItem
		}
	}
	return nil
}

func (x *Envelope) GetUpdateItem() *UpdateItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_UpdateItem); ok {
			return x.UpdateItem
		}
	}
	return nil
}

func (x *Envelope) GetUseItem() *UseItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_UseItem); ok {
			return x.UseItem
		}
	}
	return nil
}

func (x *Envelope) GetDropItem() *DropItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_DropItem); ok {
			return x.DropItem
		}
	}
	return nil
}

func (x *Envelope) GetPickupItem() *PickupItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_PickupItem); ok {
			return x.PickupItem
		}
	}
	return nil
}

func (x *Envelope) GetGroundItemShow() *GroundItemShow {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GroundItemShow); ok {
			return x.GroundItemShow
		}
	}
	return nil
}

func (x *Envelope) GetGroundItemHide() *GroundItemHide {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GroundItemHide); ok {
			return x.GroundItemHide
		}
	}
	return nil
}

func (x *Envelope) GetEquipItem() *EquipItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EquipItem); ok {
			return x.EquipItem
		}
	}
	return nil
}

func (x *Envelope) GetUnequipItem() *UnequipItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_UnequipItem); ok {
			return x.UnequipItem
		}
	}
	return nil
}

func (x *Envelope) GetEquippedItems() *EquippedItems {
	if x != nil {
		if x, ok := x.Body.(*Envelope_EquippedItems); ok {
			return x.EquippedItems
		}
	}
	return nil
}

func (x *Envelope) GetWeightChanged() *WeightChanged {
	if x != nil {
		if x, ok := x.Body.(*Envelope_WeightChanged); ok {
			return x.WeightChanged
		}
	}
	return nil
}

func (x *Envelope) GetGoldChanged() *GoldChanged {
	if x != nil {
		if x, ok := x.Body.(*Envelope_GoldChanged); ok {
			return x.GoldChanged
		}
	}
	return nil
}

func (x *Envelope) GetRepairItem() *RepairItem {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RepairItem); ok {
			return x.RepairItem
		}
	}
	return nil
}

func (x *Envelope) GetRepairCostNotice() *RepairCostNotice {
	if x != nil {
		if x, ok := x.Body.(*Envelope_RepairCostNotice); ok {
			return x.RepairCostNotice
		}
	}
	return nil
}

func (x *Envelope) GetChatInput() *ChatInput {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ChatInput); ok {
			return x.ChatInput
		}
	}
	return nil
}

func (x *Envelope) GetChatMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Body.(*Envelope_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *Envelope) GetNpcClick() *NpcClick {
	if x != nil {
		if x, ok := x.Body.(*Envelope_NpcClick); ok {
			return x.NpcClick
		}
	}
	return nil
}

func (x *Envelope) GetNpcSay() *NpcSay {
	if x != nil {
		if x, ok := x.Body.(*Envelope_NpcSay); ok {
			return x.NpcSay
		}
	}
	return nil
}

func (x *Envelope) GetNpcSelect() *NpcSelect {
	if x != nil {
		if x, ok := x.Body.(*Envelope_NpcSelect); ok {
			return x.NpcSelect
		}
	}
	return nil
}

func (x *Envelope) GetNpcClose() *NpcClose {
	if x != nil {
		if x, ok := x.Body.(*Envelope_NpcClose); ok {
			return x.NpcClose
		}
	}
	return nil
}

func (x *Envelope) GetRaw() *Raw {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_ClientHello struct {
	// ---------- 0x01xx 控制 / 握手 / 心跳 / 错误 ----------
	ClientHello *ClientHello `protobuf:"bytes,257,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type Envelope_ServerHello struct {
	ServerHello *ServerHello `protobuf:"bytes,258,opt,name=server_hello,json=serverHello,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,259,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,260,opt,name=pong,proto3,oneof"`
}

type Envelope_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,261,opt,name=disconnect,proto3,oneof"`
}

type Envelope_ServerError struct {
	ServerError *ServerError `protobuf:"bytes,262,opt,name=server_error,json=serverError,proto3,oneof"`
}

type Envelope_Reconnect struct {
	Reconnect *Reconnect `protobuf:"bytes,263,opt,name=reconnect,proto3,oneof"`
}

type Envelope_ReconnectResult struct {
	ReconnectResult *ReconnectResult `protobuf:"bytes,264,opt,name=reconnect_result,json=reconnectResult,proto3,oneof"`
}

type Envelope_Login struct {
	// ---------- 0x02xx 账号 ----------
	Login *Login `protobuf:"bytes,513,opt,name=login,proto3,oneof"`
}

type Envelope_LoginResult struct {
	LoginResult *LoginResult `protobuf:"bytes,514,opt,name=login_result,json=loginResult,proto3,oneof"`
}

type Envelope_ChangePassword struct {
	ChangePassword *ChangePassword `protobuf:"bytes,515,opt,name=change_password,json=changePassword,proto3,oneof"`
}

type Envelope_ChangePasswordResult struct {
	ChangePasswordResult *ChangePasswordResult `protobuf:"bytes,516,opt,name=change_password_result,json=changePasswordResult,proto3,oneof"`
}

type Envelope_LoginSaltRequest struct {
	// D-24① 挑战应答的第一步：取盐（见 account.proto 的说明）
	LoginSaltRequest *LoginSaltRequest `protobuf:"bytes,517,opt,name=login_salt_request,json=loginSaltRequest,proto3,oneof"`
}

type Envelope_LoginSalt struct {
	LoginSalt *LoginSalt `protobuf:"bytes,518,opt,name=login_salt,json=loginSalt,proto3,oneof"`
}

type Envelope_CreateAccount struct {
	// D-32 建号（必须先取盐，见 account.proto）
	CreateAccount *CreateAccount `protobuf:"bytes,519,opt,name=create_account,json=createAccount,proto3,oneof"`
}

type Envelope_CreateAccountResult struct {
	CreateAccountResult *CreateAccountResult `protobuf:"bytes,520,opt,name=create_account_result,json=createAccountResult,proto3,oneof"`
}

type Envelope_ListCharacters struct {
	// ---------- 0x03xx 角色 ----------
	ListCharacters *ListCharacters `protobuf:"bytes,769,opt,name=list_characters,json=listCharacters,proto3,oneof"`
}

type Envelope_CharacterList struct {
	CharacterList *CharacterList `protobuf:"bytes,770,opt,name=character_list,json=characterList,proto3,oneof"`
}

type Envelope_SelectCharacter struct {
	SelectCharacter *SelectCharacter `protobuf:"bytes,771,opt,name=select_character,json=selectCharacter,proto3,oneof"`
}

type Envelope_SelectCharacterResult struct {
	SelectCharacterResult *SelectCharacterResult `protobuf:"bytes,772,opt,name=select_character_result,json=selectCharacterResult,proto3,oneof"`
}

type Envelope_CreateCharacter struct {
	CreateCharacter *CreateCharacter `protobuf:"bytes,773,opt,name=create_character,json=createCharacter,proto3,oneof"`
}

type Envelope_CreateCharacterResult struct {
	CreateCharacterResult *CreateCharacterResult `protobuf:"bytes,774,opt,name=create_character_result,json=createCharacterResult,proto3,oneof"`
}

type Envelope_DeleteCharacter struct {
	DeleteCharacter *DeleteCharacter `protobuf:"bytes,775,opt,name=delete_character,json=deleteCharacter,proto3,oneof"`
}

type Envelope_DeleteCharacterResult struct {
	DeleteCharacterResult *DeleteCharacterResult `protobuf:"bytes,776,opt,name=delete_character_result,json=deleteCharacterResult,proto3,oneof"`
}

type Envelope_EnterWorld struct {
	// ---------- 0x04xx 场景 ----------
	EnterWorld *EnterWorld `protobuf:"bytes,1025,opt,name=enter_world,json=enterWorld,proto3,oneof"`
}

type Envelope_ChangeMap struct {
	ChangeMap *ChangeMap `protobuf:"bytes,1026,opt,name=change_map,json=changeMap,proto3,oneof"`
}

type Envelope_MapChunk struct {
	MapChunk *MapChunk `protobuf:"bytes,1027,opt,name=map_chunk,json=mapChunk,proto3,oneof"`
}

type Envelope_TimeOfDay struct {
	TimeOfDay *TimeOfDay `protobuf:"bytes,1028,opt,name=time_of_day,json=timeOfDay,proto3,oneof"`
}

type Envelope_MapDescription struct {
	MapDescription *MapDescription `protobuf:"bytes,1029,opt,name=map_description,json=mapDescription,proto3,oneof"`
}

type Envelope_EntityAppear struct {
	// ---------- 0x05xx 实体 ----------
	EntityAppear *EntityAppear `protobuf:"bytes,1281,opt,name=entity_appear,json=entityAppear,proto3,oneof"`
}

type Envelope_EntityDisappear struct {
	EntityDisappear *EntityDisappear `protobuf:"bytes,1282,opt,name=entity_disappear,json=entityDisappear,proto3,oneof"`
}

type Envelope_EntityMove struct {
	EntityMove *EntityMove `protobuf:"bytes,1283,opt,name=entity_move,json=entityMove,proto3,oneof"`
}

type Envelope_EntityAction struct {
	EntityAction *EntityAction `protobuf:"bytes,1284,opt,name=entity_action,json=entityAction,proto3,oneof"`
}

type Envelope_EntityHealth struct {
	EntityHealth *EntityHealth `protobuf:"bytes,1285,opt,name=entity_health,json=entityHealth,proto3,oneof"`
}

type Envelope_EntityStatus struct {
	EntityStatus *EntityStatus `protobuf:"bytes,1286,opt,name=entity_status,json=entityStatus,proto3,oneof"`
}

type Envelope_AbilityUpdate struct {
	AbilityUpdate *AbilityUpdate `protobuf:"bytes,1287,opt,name=ability_update,json=abilityUpdate,proto3,oneof"`
}

type Envelope_MoveInput struct {
	MoveInput *MoveInput `protobuf:"bytes,1288,opt,name=move_input,json=moveInput,proto3,oneof"`
}

type Envelope_MoveRejected struct {
	MoveRejected *MoveRejected `protobuf:"bytes,1289,opt,name=move_rejected,json=moveRejected,proto3,oneof"`
}

type Envelope_EntityFeatureChanged struct {
	EntityFeatureChanged *EntityFeatureChanged `protobuf:"bytes,1290,opt,name=entity_feature_changed,json=entityFeatureChanged,proto3,oneof"`
}

type Envelope_AttackInput struct {
	// ---------- 0x06xx 战斗 ----------
	AttackInput *AttackInput `protobuf:"bytes,1537,opt,name=attack_input,json=attackInput,proto3,oneof"`
}

type Envelope_Damage struct {
	Damage *Damage `protobuf:"bytes,1538,opt,name=damage,proto3,oneof"`
}

type Envelope_Death struct {
	Death *Death `protobuf:"bytes,1539,opt,name=death,proto3,oneof"`
}

type Envelope_Revive struct {
	Revive *Revive `protobuf:"bytes,1540,opt,name=revive,proto3,oneof"`
}

type Envelope_ExperienceGain struct {
	ExperienceGain *ExperienceGain `protobuf:"bytes,1541,opt,name=experience_gain,json=experienceGain,proto3,oneof"`
}

type Envelope_LevelUp struct {
	LevelUp *LevelUp `protobuf:"bytes,1542,opt,name=level_up,json=levelUp,proto3,oneof"`
}

type Envelope_CastSkillInput struct {
	// ---------- 0x07xx 技能 ----------
	CastSkillInput *CastSkillInput `protobuf:"bytes,1793,opt,name=cast_skill_input,json=castSkillInput,proto3,oneof"`
}

type Envelope_SkillEffect struct {
	SkillEffect *SkillEffect `protobuf:"bytes,1794,opt,name=skill_effect,json=skillEffect,proto3,oneof"`
}

type Envelope_MagicList struct {
	MagicList *MagicList `protobuf:"bytes,1795,opt,name=magic_list,json=magicList,proto3,oneof"`
}

type Envelope_MagicChanged struct {
	MagicChanged *MagicChanged `protobuf:"bytes,1796,opt,name=magic_changed,json=magicChanged,proto3,oneof"`
}

type Envelope_MagicLevelExp struct {
	MagicLevelExp *MagicLevelExp `protobuf:"bytes,1797,opt,name=magic_level_exp,json=magicLevelExp,proto3,oneof"`
}

type Envelope_BagItems struct {
	// ---------- 0x08xx 物品 ----------
	BagItems *BagItems `protobuf:"bytes,2049,opt,name=bag_items,json=bagItems,proto3,oneof"`
}

type Envelope_AddItem struct {
	AddItem *AddItem `protobuf:"bytes,2050,opt,name=add_item,json=addItem,proto3,oneof"`
}

type Envelope_RemoveItem struct {
	RemoveItem *RemoveItem `protobuf:"bytes,2051,opt,name=remove_item,json=removeItem,proto3,oneof"`
}

type Envelope_UpdateItem struct {
	UpdateItem *UpdateItem `protobuf:"bytes,2052,opt,name=update_item,json=updateItem,proto3,oneof"`
}

type Envelope_UseItem struct {
	UseItem *UseItem `protobuf:"bytes,2053,opt,name=use_item,json=useItem,proto3,oneof"`
}

type Envelope_DropItem struct {
	DropItem *DropItem `protobuf:"bytes,2054,opt,name=drop_item,json=dropItem,proto3,oneof"`
}

type Envelope_PickupItem struct {
	PickupItem *PickupItem `protobuf:"bytes,2055,opt,name=pickup_item,json=pickupItem,proto3,oneof"`
}

type Envelope_GroundItemShow struct {
	GroundItemShow *GroundItemShow `protobuf:"bytes,2056,opt,name=ground_item_show,json=groundItemShow,proto3,oneof"`
}

type Envelope_GroundItemHide struct {
	GroundItemHide *GroundItemHide `protobuf:"bytes,2057,opt,name=ground_item_hide,json=groundItemHide,proto3,oneof"`
}

type Envelope_EquipItem struct {
	EquipItem *EquipItem `protobuf:"bytes,2058,opt,name=equip_item,json=equipItem,proto3,oneof"`
}

type Envelope_UnequipItem struct {
	UnequipItem *UnequipItem `protobuf:"bytes,2059,opt,name=unequip_item,json=unequipItem,proto3,oneof"`
}

type Envelope_EquippedItems struct {
	EquippedItems *EquippedItems `protobuf:"bytes,2060,opt,name=equipped_items,json=equippedItems,proto3,oneof"`
}

type Envelope_WeightChanged struct {
	WeightChanged *WeightChanged `protobuf:"bytes,2061,opt,name=weight_changed,json=weightChanged,proto3,oneof"`
}

type Envelope_GoldChanged struct {
	GoldChanged *GoldChanged `protobuf:"bytes,2062,opt,name=gold_changed,json=goldChanged,proto3,oneof"`
}

type Envelope_RepairItem struct {
	RepairItem *RepairItem `protobuf:"bytes,2063,opt,name=repair_item,json=repairItem,proto3,oneof"`
}

type Envelope_RepairCostNotice struct {
	RepairCostNotice *RepairCostNotice `protobuf:"bytes,2064,opt,name=repair_cost_notice,json=repairCostNotice,proto3,oneof"`
}

type Envelope_ChatInput struct {
	// ---------- 0x09xx 聊天 ----------
	ChatInput *ChatInput `protobuf:"bytes,2305,opt,name=chat_input,json=chatInput,proto3,oneof"`
}

type Envelope_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,2306,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type Envelope_NpcClick struct {
	// ---------- 0x0Axx NPC 对话（见 npc.proto）----------
	NpcClick *NpcClick `protobuf:"bytes,2561,opt,name=npc_click,json=npcClick,proto3,oneof"`
}

type Envelope_NpcSay struct {
	NpcSay *NpcSay `protobuf:"bytes,2562,opt,name=npc_say,json=npcSay,proto3,oneof"`
}

type Envelope_NpcSelect struct {
	NpcSelect *NpcSelect `protobuf:"bytes,2563,opt,name=npc_select,json=npcSelect,proto3,oneof"`
}

type Envelope_NpcClose struct {
	NpcClose *NpcClose `protobuf:"bytes,2564,opt,name=npc_close,json=npcClose,proto3,oneof"`
}

type Envelope_Raw struct {
	// ---------- 逃生舱（protocol.md §4.1）----------
	// 仅供 GM 工具 / 调试 / 插件注入；oneof 无法从外部扩展，这是唯一硬限制的出口。
	Raw *Raw `protobuf:"bytes,4095,opt,name=raw,proto3,oneof"`
}

func (*Envelope_ClientHello) isEnvelope_Body() {}

func (*Envelope_ServerHello) isEnvelope_Body() {}

func (*Envelope_Ping) isEnvelope_Body() {}

func (*Envelope_Pong) isEnvelope_Body() {}

func (*Envelope_Disconnect) isEnvelope_Body() {}

func (*Envelope_ServerError) isEnvelope_Body() {}

func (*Envelope_Reconnect) isEnvelope_Body() {}

func (*Envelope_ReconnectResult) isEnvelope_Body() {}

func (*Envelope_Login) isEnvelope_Body() {}

func (*Envelope_LoginResult) isEnvelope_Body() {}

func (*Envelope_ChangePassword) isEnvelope_Body() {}

func (*Envelope_ChangePasswordResult) isEnvelope_Body() {}

func (*Envelope_LoginSaltRequest) isEnvelope_Body() {}

func (*Envelope_LoginSalt) isEnvelope_Body() {}

func (*Envelope_CreateAccount) isEnvelope_Body() {}

func (*Envelope_CreateAccountResult) isEnvelope_Body() {}

func (*Envelope_ListCharacters) isEnvelope_Body() {}

func (*Envelope_CharacterList) isEnvelope_Body() {}

func (*Envelope_SelectCharacter) isEnvelope_Body() {}

func (*Envelope_SelectCharacterResult) isEnvelope_Body() {}

func (*Envelope_CreateCharacter) isEnvelope_Body() {}

func (*Envelope_CreateCharacterResult) isEnvelope_Body() {}

func (*Envelope_DeleteCharacter) isEnvelope_Body() {}

func (*Envelope_DeleteCharacterResult) isEnvelope_Body() {}

func (*Envelope_EnterWorld) isEnvelope_Body() {}

func (*Envelope_ChangeMap) isEnvelope_Body() {}

func (*Envelope_MapChunk) isEnvelope_Body() {}

func (*Envelope_TimeOfDay) isEnvelope_Body() {}

func (*Envelope_MapDescription) isEnvelope_Body() {}

func (*Envelope_EntityAppear) isEnvelope_Body() {}

func (*Envelope_EntityDisappear) isEnvelope_Body() {}

func (*Envelope_EntityMove) isEnvelope_Body() {}

func (*Envelope_EntityAction) isEnvelope_Body() {}

func (*Envelope_EntityHealth) isEnvelope_Body() {}

func (*Envelope_EntityStatus) isEnvelope_Body() {}

func (*Envelope_AbilityUpdate) isEnvelope_Body() {}

func (*Envelope_MoveInput) isEnvelope_Body() {}

func (*Envelope_MoveRejected) isEnvelope_Body() {}

func (*Envelope_EntityFeatureChanged) isEnvelope_Body() {}

func (*Envelope_AttackInput) isEnvelope_Body() {}

func (*Envelope_Damage) isEnvelope_Body() {}

func (*Envelope_Death) isEnvelope_Body() {}

func (*Envelope_Revive) isEnvelope_Body() {}

func (*Envelope_ExperienceGain) isEnvelope_Body() {}

func (*Envelope_LevelUp) isEnvelope_Body() {}

func (*Envelope_CastSkillInput) isEnvelope_Body() {}

func (*Envelope_SkillEffect) isEnvelope_Body() {}

func (*Envelope_MagicList) isEnvelope_Body() {}

func (*Envelope_MagicChanged) isEnvelope_Body() {}

func (*Envelope_MagicLevelExp) isEnvelope_Body() {}

func (*Envelope_BagItems) isEnvelope_Body() {}

func (*Envelope_AddItem) isEnvelope_Body() {}

func (*Envelope_RemoveItem) isEnvelope_Body() {}

func (*Envelope_UpdateItem) isEnvelope_Body() {}

func (*Envelope_UseItem) isEnvelope_Body() {}

func (*Envelope_DropItem) isEnvelope_Body() {}

func (*Envelope_PickupItem) isEnvelope_Body() {}

func (*Envelope_GroundItemShow) isEnvelope_Body() {}

func (*Envelope_GroundItemHide) isEnvelope_Body() {}

func (*Envelope_EquipItem) isEnvelope_Body() {}

func (*Envelope_UnequipItem) isEnvelope_Body() {}

func (*Envelope_EquippedItems) isEnvelope_Body() {}

func (*Envelope_WeightChanged) isEnvelope_Body() {}

func (*Envelope_GoldChanged) isEnvelope_Body() {}

func (*Envelope_RepairItem) isEnvelope_Body() {}

func (*Envelope_RepairCostNotice) isEnvelope_Body() {}

func (*Envelope_ChatInput) isEnvelope_Body() {}

func (*Envelope_ChatMessage) isEnvelope_Body() {}

func (*Envelope_NpcClick) isEnvelope_Body() {}

func (*Envelope_NpcSay) isEnvelope_Body() {}

func (*Envelope_NpcSelect) isEnvelope_Body() {}

func (*Envelope_NpcClose) isEnvelope_Body() {}

func (*Envelope_Raw) isEnvelope_Body() {}

// 逃生舱载荷：绕过 oneof 的直通消息。
type Raw struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Raw) Reset() {
	*x = Raw{}
	mi := &file_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Raw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Raw) ProtoMessage() {}

func (x *Raw) ProtoReflect() protoreflect.Message {
	mi := &file_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Raw.ProtoReflect.Descriptor instead.
func (*Raw) Descriptor() ([]byte, []int) {
	return file_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Raw) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Raw) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_envelope_proto protoreflect.FileDescriptor

const file_envelope_proto_rawDesc = "" +
	"\n" +
	"\x0eenvelope.proto\x12\x04mir2\x1a\rcontrol.proto\x1a\raccount.proto\x1a\vscene.proto\x1a\fcombat.proto\x1a\n" +
	"item.proto\x1a\fsocial.proto\x1a\tnpc.proto\"\xe9!\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x17\n" +
	"\aack_seq\x18\x02 \x01(\rR\x06ackSeq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x04R\trequestId\x127\n" +
	"\fclient_hello\x18\x81\x02 \x01(\v2\x11.mir2.ClientHelloH\x00R\vclientHello\x127\n" +
	"\fserver_hello\x18\x82\x02 \x01(\v2\x11.mir2.ServerHelloH\x00R\vserverHello\x12!\n" +
	"\x04ping\x18\x83\x02 \x01(\v2\n" +
	".mir2.PingH\x00R\x04ping\x12!\n" +
	"\x04pong\x18\x84\x02 \x01(\v2\n" +
	".mir2.PongH\x00R\x04pong\x123\n" +
	"\n" +
	"disconnect\x18\x85\x02 \x01(\v2\x10.mir2.DisconnectH\x00R\n" +
	"disconnect\x127\n" +
	"\fserver_error\x18\x86\x02 \x01(\v2\x11.mir2.ServerErrorH\x00R\vserverError\x120\n" +
	"\treconnect\x18\x87\x02 \x01(\v2\x0f.mir2.ReconnectH\x00R\treconnect\x12C\n" +
	"\x10reconnect_result\x18\x88\x02 \x01(\v2\x15.mir2.ReconnectResultH\x00R\x0freconnectResult\x12$\n" +
	"\x05login\x18\x81\x04 \x01(\v2\v.mir2.LoginH\x00R\x05login\x127\n" +
	"\flogin_result\x18\x82\x04 \x01(\v2\x11.mir2.LoginResultH\x00R\vloginResult\x12@\n" +
	"\x0fchange_password\x18\x83\x04 \x01(\v2\x14.mir2.ChangePasswordH\x00R\x0echangePassword\x12S\n" +
	"\x16change_password_result\x18\x84\x04 \x01(\v2\x1a.mir2.ChangePasswordResultH\x00R\x14changePasswordResult\x12G\n" +
	"\x12login_salt_request\x18\x85\x04 \x01(\v2\x16.mir2.LoginSaltRequestH\x00R\x10loginSaltRequest\x121\n" +
	"\n" +
	"login_salt\x18\x86\x04 \x01(\v2\x0f.mir2.LoginSaltH\x00R\tloginSalt\x12=\n" +
	"\x0ecreate_account\x18\x87\x04 \x01(\v2\x13.mir2.CreateAccountH\x00R\rcreateAccount\x12P\n" +
	"\x15create_account_result\x18\x88\x04 \x01(\v2\x19.mir2.CreateAccountResultH\x00R\x13createAccountResult\x12@\n" +
	"\x0flist_characters\x18\x81\x06 \x01(\v2\x14.mir2.ListCharactersH\x00R\x0elistCharacters\x12=\n" +
	"\x0echaracter_list\x18\x82\x06 \x01(\v2\x13.mir2.CharacterListH\x00R\rcharacterList\x12C\n" +
	"\x10select_character\x18\x83\x06 \x01(\v2\x15.mir2.SelectCharacterH\x00R\x0fselectCharacter\x12V\n" +
	"\x17select_character_result\x18\x84\x06 \x01(\v2\x1b.mir2.SelectCharacterResultH\x00R\x15selectCharacterResult\x12C\n" +
	"\x10create_character\x18\x85\x06 \x01(\v2\x15.mir2.CreateCharacterH\x00R\x0fcreateCharacter\x12V\n" +
	"\x17create_character_result\x18\x86\x06 \x01(\v2\x1b.mir2.CreateCharacterResultH\x00R\x15createCharacterResult\x12C\n" +
	"\x10delete_character\x18\x87\x06 \x01(\v2\x15.mir2.DeleteCharacterH\x00R\x0fdeleteCharacter\x12V\n" +
	"\x17delete_character_result\x18\x88\x06 \x01(\v2\x1b.mir2.DeleteCharacterResultH\x00R\x15deleteCharacterResult\x124\n" +
	"\venter_world\x18\x81\b \x01(\v2\x10.mir2.EnterWorldH\x00R\n" +
	"enterWorld\x121\n" +
	"\n" +
	"change_map\x18\x82\b \x01(\v2\x0f.mir2.ChangeMapH\x00R\tchangeMap\x12.\n" +
	"\tmap_chunk\x18\x83\b \x01(\v2\x0e.mir2.MapChunkH\x00R\bmapChunk\x122\n" +
	"\vtime_of_day\x18\x84\b \x01(\v2\x0f.mir2.TimeOfDayH\x00R\ttimeOfDay\x12@\n" +
	"\x0fmap_description\x18\x85\b \x01(\v2\x14.mir2.MapDescriptionH\x00R\x0emapDescription\x12:\n" +
	"\rentity_appear\x18\x81\n" +
	" \x01(\v2\x12.mir2.EntityAppearH\x00R\fentityAppear\x12C\n" +
	"\x10entity_disappear\x18\x82\n" +
	" \x01(\v2\x15.mir2.EntityDisappearH\x00R\x0fentityDisappear\x124\n" +
	"\ventity_move\x18\x83\n" +
	" \x01(\v2\x10.mir2.EntityMoveH\x00R\n" +
	"entityMove\x12:\n" +
	"\rentity_action\x18\x84\n" +
	" \x01(\v2\x12.mir2.EntityActionH\x00R\fentityAction\x12:\n" +
	"\rentity_health\x18\x85\n" +
	" \x01(\v2\x12.mir2.EntityHealthH\x00R\fentityHealth\x12:\n" +
	"\rentity_status\x18\x86\n" +
	" \x01(\v2\x12.mir2.EntityStatusH\x00R\fentityStatus\x12=\n" +
	"\x0eability_update\x18\x87\n" +
	" \x01(\v2\x13.mir2.AbilityUpdateH\x00R\rabilityUpdate\x121\n" +
	"\n" +
	"move_input\x18\x88\n" +
	" \x01(\v2\x0f.mir2.MoveInputH\x00R\tmoveInput\x12:\n" +
	"\rmove_rejected\x18\x89\n" +
	" \x01(\v2\x12.mir2.MoveRejectedH\x00R\fmoveRejected\x12S\n" +
	"\x16entity_feature_changed\x18\x8a\n" +
	" \x01(\v2\x1a.mir2.EntityFeatureChangedH\x00R\x14entityFeatureChanged\x127\n" +
	"\fattack_input\x18\x81\f \x01(\v2\x11.mir2.AttackInputH\x00R\vattackInput\x12'\n" +
	"\x06damage\x18\x82\f \x01(\v2\f.mir2.DamageH\x00R\x06damage\x12$\n" +
	"\x05death\x18\x83\f \x01(\v2\v.mir2.DeathH\x00R\x05death\x12'\n" +
	"\x06revive\x18\x84\f \x01(\v2\f.mir2.ReviveH\x00R\x06revive\x12@\n" +
	"\x0fexperience_gain\x18\x85\f \x01(\v2\x14.mir2.ExperienceGainH\x00R\x0eexperienceGain\x12+\n" +
	"\blevel_up\x18\x86\f \x01(\v2\r.mir2.LevelUpH\x00R\alevelUp\x12A\n" +
	"\x10cast_skill_input\x18\x81\x0e \x01(\v2\x14.mir2.CastSkillInputH\x00R\x0ecastSkillInput\x127\n" +
	"\fskill_effect\x18\x82\x0e \x01(\v2\x11.mir2.SkillEffectH\x00R\vskillEffect\x121\n" +
	"\n" +
	"magic_list\x18\x83\x0e \x01(\v2\x0f.mir2.MagicListH\x00R\tmagicList\x12:\n" +
	"\rmagic_changed\x18\x84\x0e \x01(\v2\x12.mir2.MagicChangedH\x00R\fmagicChanged\x12>\n" +
	"\x0fmagic_level_exp\x18\x85\x0e \x01(\v2\x13.mir2.MagicLevelExpH\x00R\rmagicLevelExp\x12.\n" +
	"\tbag_items\x18\x81\x10 \x01(\v2\x0e.mir2.BagItemsH\x00R\bbagItems\x12+\n" +
	"\badd_item\x18\x82\x10 \x01(\v2\r.mir2.AddItemH\x00R\aaddItem\x124\n" +
	"\vremove_item\x18\x83\x10 \x01(\v2\x10.mir2.RemoveItemH\x00R\n" +
	"removeItem\x124\n" +
	"\vupdate_item\x18\x84\x10 \x01(\v2\x10.mir2.UpdateItemH\x00R\n" +
	"updateItem\x12+\n" +
	"\buse_item\x18\x85\x10 \x01(\v2\r.mir2.UseItemH\x00R\auseItem\x12.\n" +
	"\tdrop_item\x18\x86\x10 \x01(\v2\x0e.mir2.DropItemH\x00R\bdropItem\x124\n" +
	"\vpickup_item\x18\x87\x10 \x01(\v2\x10.mir2.PickupItemH\x00R\n" +
	"pickupItem\x12A\n" +
	"\x10ground_item_show\x18\x88\x10 \x01(\v2\x14.mir2.GroundItemShowH\x00R\x0egroundItemShow\x12A\n" +
	"\x10ground_item_hide\x18\x89\x10 \x01(\v2\x14.mir2.GroundItemHideH\x00R\x0egroundItemHide\x121\n" +
	"\n" +
	"equip_item\x18\x8a\x10 \x01(\v2\x0f.mir2.EquipItemH\x00R\tequipItem\x127\n" +
	"\funequip_item\x18\x8b\x10 \x01(\v2\x11.mir2.UnequipItemH\x00R\vunequipItem\x12=\n" +
	"\x0eequipped_items\x18\x8c\x10 \x01(\v2\x13.mir2.EquippedItemsH\x00R\requippedItems\x12=\n" +
	"\x0eweight_changed\x18\x8d\x10 \x01(\v2\x13.mir2.WeightChangedH\x00R\rweightChanged\x127\n" +
	"\fgold_changed\x18\x8e\x10 \x01(\v2\x11.mir2.GoldChangedH\x00R\vgoldChanged\x124\n" +
	"\vrepair_item\x18\x8f\x10 \x01(\v2\x10.mir2.RepairItemH\x00R\n" +
	"repairItem\x12G\n" +
	"\x12repair_cost_notice\x18\x90\x10 \x01(\v2\x16.mir2.RepairCostNoticeH\x00R\x10repairCostNotice\x121\n" +
	"\n" +
	"chat_input\x18\x81\x12 \x01(\v2\x0f.mir2.ChatInputH\x00R\tchatInput\x127\n" +
	"\fchat_message\x18\x82\x12 \x01(\v2\x11.mir2.ChatMessageH\x00R\vchatMessage\x12.\n" +
	"\tnpc_click\x18\x81\x14 \x01(\v2\x0e.mir2.NpcClickH\x00R\bnpcClick\x12(\n" +
	"\anpc_say\x18\x82\x14 \x01(\v2\f.mir2.NpcSayH\x00R\x06npcSay\x121\n" +
	"\n" +
	"npc_select\x18\x83\x14 \x01(\v2\x0f.mir2.NpcSelectH\x00R\tnpcSelect\x12.\n" +
	"\tnpc_close\x18\x84\x14 \x01(\v2\x0e.mir2.NpcCloseH\x00R\bnpcClose\x12\x1e\n" +
	"\x03raw\x18\xff\x1f \x01(\v2\t.mir2.RawH\x00R\x03rawB\x06\n" +
	"\x04body\"0\n" +
	"\x03Raw\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04bodyB2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_envelope_proto_rawDescOnce sync.Once
	file_envelope_proto_rawDescData []byte
)

func file_envelope_proto_rawDescGZIP() []byte {
	file_envelope_proto_rawDescOnce.Do(func() {
		file_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)))
	})
	return file_envelope_proto_rawDescData
}

var file_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: mir2.Envelope
	(*Raw)(nil),                   // 1: mir2.Raw
	(*ClientHello)(nil),           // 2: mir2.ClientHello
	(*ServerHello)(nil),           // 3: mir2.ServerHello
	(*Ping)(nil),                  // 4: mir2.Ping
	(*Pong)(nil),                  // 5: mir2.Pong
	(*Disconnect)(nil),            // 6: mir2.Disconnect
	(*ServerError)(nil),           // 7: mir2.ServerError
	(*Reconnect)(nil),             // 8: mir2.Reconnect
	(*ReconnectResult)(nil),       // 9: mir2.ReconnectResult
	(*Login)(nil),                 // 10: mir2.Login
	(*LoginResult)(nil),           // 11: mir2.LoginResult
	(*ChangePassword)(nil),        // 12: mir2.ChangePassword
	(*ChangePasswordResult)(nil),  // 13: mir2.ChangePasswordResult
	(*LoginSaltRequest)(nil),      // 14: mir2.LoginSaltRequest
	(*LoginSalt)(nil),             // 15: mir2.LoginSalt
	(*CreateAccount)(nil),         // 16: mir2.CreateAccount
	(*CreateAccountResult)(nil),   // 17: mir2.CreateAccountResult
	(*ListCharacters)(nil),        // 18: mir2.ListCharacters
	(*CharacterList)(nil),         // 19: mir2.CharacterList
	(*SelectCharacter)(nil),       // 20: mir2.SelectCharacter
	(*SelectCharacterResult)(nil), // 21: mir2.SelectCharacterResult
	(*CreateCharacter)(nil),       // 22: mir2.CreateCharacter
	(*CreateCharacterResult)(nil), // 23: mir2.CreateCharacterResult
	(*DeleteCharacter)(nil),       // 24: mir2.DeleteCharacter
	(*DeleteCharacterResult)(nil), // 25: mir2.DeleteCharacterResult
	(*EnterWorld)(nil),            // 26: mir2.EnterWorld
	(*ChangeMap)(nil),             // 27: mir2.ChangeMap
	(*MapChunk)(nil),              // 28: mir2.MapChunk
	(*TimeOfDay)(nil),             // 29: mir2.TimeOfDay
	(*MapDescription)(nil),        // 30: mir2.MapDescription
	(*EntityAppear)(nil),          // 31: mir2.EntityAppear
	(*EntityDisappear)(nil),       // 32: mir2.EntityDisappear
	(*EntityMove)(nil),            // 33: mir2.EntityMove
	(*EntityAction)(nil),          // 34: mir2.EntityAction
	(*EntityHealth)(nil),          // 35: mir2.EntityHealth
	(*EntityStatus)(nil),          // 36: mir2.EntityStatus
	(*AbilityUpdate)(nil),         // 37: mir2.AbilityUpdate
	(*MoveInput)(nil),             // 38: mir2.MoveInput
	(*MoveRejected)(nil),          // 39: mir2.MoveRejected
	(*EntityFeatureChanged)(nil),  // 40: mir2.EntityFeatureChanged
	(*AttackInput)(nil),           // 41: mir2.AttackInput
	(*Damage)(nil),                // 42: mir2.Damage
	(*Death)(nil),                 // 43: mir2.Death
	(*Revive)(nil),                // 44: mir2.Revive
	(*ExperienceGain)(nil),        // 45: mir2.ExperienceGain
	(*LevelUp)(nil),               // 46: mir2.LevelUp
	(*CastSkillInput)(nil),        // 47: mir2.CastSkillInput
	(*SkillEffect)(nil),           // 48: mir2.SkillEffect
	(*MagicList)(nil),             // 49: mir2.MagicList
	(*MagicChanged)(nil),          // 50: mir2.MagicChanged
	(*MagicLevelExp)(nil),         // 51: mir2.MagicLevelExp
	(*BagItems)(nil),              // 52: mir2.BagItems
	(*AddItem)(nil),               // 53: mir2.AddItem
	(*RemoveItem)(nil),            // 54: mir2.RemoveItem
	(*UpdateItem)(nil),            // 55: mir2.UpdateItem
	(*UseItem)(nil),               // 56: mir2.UseItem
	(*DropItem)(nil),              // 57: mir2.DropItem
	(*PickupItem)(nil),            // 58: mir2.PickupItem
	(*GroundItemShow)(nil),        // 59: mir2.GroundItemShow
	(*GroundItemHide)(nil),        // 60: mir2.GroundItemHide
	(*EquipItem)(nil),             // 61: mir2.EquipItem
	(*UnequipItem)(nil),           // 62: mir2.UnequipItem
	(*EquippedItems)(nil),         // 63: mir2.EquippedItems
	(*WeightChanged)(nil),         // 64: mir2.WeightChanged
	(*GoldChanged)(nil),           // 65: mir2.GoldChanged
	(*RepairItem)(nil),            // 66: mir2.RepairItem
	(*RepairCostNotice)(nil),      // 67: mir2.RepairCostNotice
	(*ChatInput)(nil),             // 68: mir2.ChatInput
	(*ChatMessage)(nil),           // 69: mir2.ChatMessage
	(*NpcClick)(nil),              // 70: mir2.NpcClick
	(*NpcSay)(nil),                // 71: mir2.NpcSay
	(*NpcSelect)(nil),             // 72: mir2.NpcSelect
	(*NpcClose)(nil),              // 73: mir2.NpcClose
}
var file_envelope_proto_depIdxs = []int32{
	2,  // 0: mir2.Envelope.client_hello:type_name -> mir2.ClientHello
	3,  // 1: mir2.Envelope.server_hello:type_name -> mir2.ServerHello
	4,  // 2: mir2.Envelope.ping:type_name -> mir2.Ping
	5,  // 3: mir2.Envelope.pong:type_name -> mir2.Pong
	6,  // 4: mir2.Envelope.disconnect:type_name -> mir2.Disconnect
	7,  // 5: mir2.Envelope.server_error:type_name -> mir2.ServerError
	8,  // 6: mir2.Envelope.reconnect:type_name -> mir2.Reconnect
	9,  // 7: mir2.Envelope.reconnect_result:type_name -> mir2.ReconnectResult
	10, // 8: mir2.Envelope.login:type_name -> mir2.Login
	11, // 9: mir2.Envelope.login_result:type_name -> mir2.LoginResult
	12, // 10: mir2.Envelope.change_password:type_name -> mir2.ChangePassword
	13, // 11: mir2.Envelope.change_password_result:type_name -> mir2.ChangePasswordResult
	14, // 12: mir2.Envelope.login_salt_request:type_name -> mir2.LoginSaltRequest
	15, // 13: mir2.Envelope.login_salt:type_name -> mir2.LoginSalt
	16, // 14: mir2.Envelope.create_account:type_name -> mir2.CreateAccount
	17, // 15: mir2.Envelope.create_account_result:type_name -> mir2.CreateAccountResult
	18, // 16: mir2.Envelope.list_characters:type_name -> mir2.ListCharacters
	19, // 17: mir2.Envelope.character_list:type_name -> mir2.CharacterList
	20, // 18: mir2.Envelope.select_character:type_name -> mir2.SelectCharacter
	21, // 19: mir2.Envelope.select_character_result:type_name -> mir2.SelectCharacterResult
	22, // 20: mir2.Envelope.create_character:type_name -> mir2.CreateCharacter
	23, // 21: mir2.Envelope.create_character_result:type_name -> mir2.CreateCharacterResult
	24, // 22: mir2.Envelope.delete_character:type_name -> mir2.DeleteCharacter
	25, // 23: mir2.Envelope.delete_character_result:type_name -> mir2.DeleteCharacterResult
	26, // 24: mir2.Envelope.enter_world:type_name -> mir2.EnterWorld
	27, // 25: mir2.Envelope.change_map:type_name -> mir2.ChangeMap
	28, // 26: mir2.Envelope.map_chunk:type_name -> mir2.MapChunk
	29, // 27: mir2.Envelope.time_of_day:type_name -> mir2.TimeOfDay
	30, // 28: mir2.Envelope.map_description:type_name -> mir2.MapDescription
	31, // 29: mir2.Envelope.entity_appear:type_name -> mir2.EntityAppear
	32, // 30: mir2.Envelope.entity_disappear:type_name -> mir2.EntityDisappear
	33, // 31: mir2.Envelope.entity_move:type_name -> mir2.EntityMove
	34, // 32: mir2.Envelope.entity_action:type_name -> mir2.EntityAction
	35, // 33: mir2.Envelope.entity_health:type_name -> mir2.EntityHealth
	36, // 34: mir2.Envelope.entity_status:type_name -> mir2.EntityStatus
	37, // 35: mir2.Envelope.ability_update:type_name -> mir2.AbilityUpdate
	38, // 36: mir2.Envelope.move_input:type_name -> mir2.MoveInput
	39, // 37: mir2.Envelope.move_rejected:type_name -> mir2.MoveRejected
	40, // 38: mir2.Envelope.entity_feature_changed:type_name -> mir2.EntityFeatureChanged
	41, // 39: mir2.Envelope.attack_input:type_name -> mir2.AttackInput
	42, // 40: mir2.Envelope.damage:type_name -> mir2.Damage
	43, // 41: mir2.Envelope.death:type_name -> mir2.Death
	44, // 42: mir2.Envelope.revive:type_name -> mir2.Revive
	45, // 43: mir2.Envelope.experience_gain:type_name -> mir2.ExperienceGain
	46, // 44: mir2.Envelope.level_up:type_name -> mir2.LevelUp
	47, // 45: mir2.Envelope.cast_skill_input:type_name -> mir2.CastSkillInput
	48, // 46: mir2.Envelope.skill_effect:type_name -> mir2.SkillEffect
	49, // 47: mir2.Envelope.magic_list:type_name -> mir2.MagicList
	50, // 48: mir2.Envelope.magic_changed:type_name -> mir2.MagicChanged
	51, // 49: mir2.Envelope.magic_level_exp:type_name -> mir2.MagicLevelExp
	52, // 50: mir2.Envelope.bag_items:type_name -> mir2.BagItems
	53, // 51: mir2.Envelope.add_item:type_name -> mir2.AddItem
	54, // 52: mir2.Envelope.remove_item:type_name -> mir2.RemoveItem
	55, // 53: mir2.Envelope.update_item:type_name -> mir2.UpdateItem
	56, // 54: mir2.Envelope.use_item:type_name -> mir2.UseItem
	57, // 55: mir2.Envelope.drop_item:type_name -> mir2.DropItem
	58, // 56: mir2.Envelope.pickup_item:type_name -> mir2.PickupItem
	59, // 57: mir2.Envelope.ground_item_show:type_name -> mir2.GroundItemShow
	60, // 58: mir2.Envelope.ground_item_hide:type_name -> mir2.GroundItemHide
	61, // 59: mir2.Envelope.equip_item:type_name -> mir2.EquipItem
	62, // 60: mir2.Envelope.unequip_item:type_name -> mir2.UnequipItem
	63, // 61: mir2.Envelope.equipped_items:type_name -> mir2.EquippedItems
	64, // 62: mir2.Envelope.weight_changed:type_name -> mir2.WeightChanged
	65, // 63: mir2.Envelope.gold_changed:type_name -> mir2.GoldChanged
	66, // 64: mir2.Envelope.repair_item:type_name -> mir2.RepairItem
	67, // 65: mir2.Envelope.repair_cost_notice:type_name -> mir2.RepairCostNotice
	68, // 66: mir2.Envelope.chat_input:type_name -> mir2.ChatInput
	69, // 67: mir2.Envelope.chat_message:type_name -> mir2.ChatMessage
	70, // 68: mir2.Envelope.npc_click:type_name -> mir2.NpcClick
	71, // 69: mir2.Envelope.npc_say:type_name -> mir2.NpcSay
	72, // 70: mir2.Envelope.npc_select:type_name -> mir2.NpcSelect
	73, // 71: mir2.Envelope.npc_close:type_name -> mir2.NpcClose
	1,  // 72: mir2.Envelope.raw:type_name -> mir2.Raw
	73, // [73:73] is the sub-list for method output_type
	73, // [73:73] is the sub-list for method input_type
	73, // [73:73] is the sub-list for extension type_name
	73, // [73:73] is the sub-list for extension extendee
	0,  // [0:73] is the sub-list for field type_name
}

func init() { file_envelope_proto_init() }
func file_envelope_proto_init() {
	if File_envelope_proto != nil {
		return
	}
	file_control_proto_init()
	file_account_proto_init()
	file_scene_proto_init()
	file_combat_proto_init()
	file_item_proto_init()
	file_social_proto_init()
	file_npc_proto_init()
	file_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_ClientHello)(nil),
		(*Envelope_ServerHello)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Disconnect)(nil),
		(*Envelope_ServerError)(nil),
		(*Envelope_Reconnect)(nil),
		(*Envelope_ReconnectResult)(nil),
		(*Envelope_Login)(nil),
		(*Envelope_LoginResult)(nil),
		(*Envelope_ChangePassword)(nil),
		(*Envelope_ChangePasswordResult)(nil),
		(*Envelope_LoginSaltRequest)(nil),
		(*Envelope_LoginSalt)(nil),
		(*Envelope_CreateAccount)(nil),
		(*Envelope_CreateAccountResult)(nil),
		(*Envelope_ListCharacters)(nil),
		(*Envelope_CharacterList)(nil),
		(*Envelope_SelectCharacter)(nil),
		(*Envelope_SelectCharacterResult)(nil),
		(*Envelope_CreateCharacter)(nil),
		(*Envelope_CreateCharacterResult)(nil),
		(*Envelope_DeleteCharacter)(nil),
		(*Envelope_DeleteCharacterResult)(nil),
		(*Envelope_EnterWorld)(nil),
		(*Envelope_ChangeMap)(nil),
		(*Envelope_MapChunk)(nil),
		(*Envelope_TimeOfDay)(nil),
		(*Envelope_MapDescription)(nil),
		(*Envelope_EntityAppear)(nil),
		(*Envelope_EntityDisappear)(nil),
		(*Envelope_EntityMove)(nil),
		(*Envelope_EntityAction)(nil),
		(*Envelope_EntityHealth)(nil),
		(*Envelope_EntityStatus)(nil),
		(*Envelope_AbilityUpdate)(nil),
		(*Envelope_MoveInput)(nil),
		(*Envelope_MoveRejected)(nil),
		(*Envelope_EntityFeatureChanged)(nil),
		(*Envelope_AttackInput)(nil),
		(*Envelope_Damage)(nil),
		(*Envelope_Death)(nil),
		(*Envelope_Revive)(nil),
		(*Envelope_ExperienceGain)(nil),
		(*Envelope_LevelUp)(nil),
		(*Envelope_CastSkillInput)(nil),
		(*Envelope_SkillEffect)(nil),
		(*Envelope_MagicList)(nil),
		(*Envelope_MagicChanged)(nil),
		(*Envelope_MagicLevelExp)(nil),
		(*Envelope_BagItems)(nil),
		(*Envelope_AddItem)(nil),
		(*Envelope_RemoveItem)(nil),
		(*Envelope_UpdateItem)(nil),
		(*Envelope_UseItem)(nil),
		(*Envelope_DropItem)(nil),
		(*Envelope_PickupItem)(nil),
		(*Envelope_GroundItemShow)(nil),
		(*Envelope_GroundItemHide)(nil),
		(*Envelope_EquipItem)(nil),
		(*Envelope_UnequipItem)(nil),
		(*Envelope_EquippedItems)(nil),
		(*Envelope_WeightChanged)(nil),
		(*Envelope_GoldChanged)(nil),
		(*Envelope_RepairItem)(nil),
		(*Envelope_RepairCostNotice)(nil),
		(*Envelope_ChatInput)(nil),
		(*Envelope_ChatMessage)(nil),
		(*Envelope_NpcClick)(nil),
		(*Envelope_NpcSay)(nil),
		(*Envelope_NpcSelect)(nil),
		(*Envelope_NpcClose)(nil),
		(*Envelope_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envelope_proto_rawDesc), len(file_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envelope_proto_goTypes,
		DependencyIndexes: file_envelope_proto_depIdxs,
		MessageInfos:      file_envelope_proto_msgTypes,
	}.Build()
	File_envelope_proto = out.File
	file_envelope_proto_goTypes = nil
	file_envelope_proto_depIdxs = nil
}
