// MIR2 协议 · 0x08xx 物品
//
// 覆盖：背包 / 装备 / 地面物品 / 使用 / 丢弃 / 拾取 / 修理 / 重量 / 金币。
// ⚠️ 原版地面物品用 `SM_ITEMSHOW`(610)、进背包用 `SM_ADDITEM`(200)（见 docs/messages.md §2.5）；
//   自研协议用 `GroundItemShow` / `AddItem` 明确区分，**不要**沿用原版那种混用。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: item.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 物品实例（原版 TClientItem）。
type ItemStack struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // 物品表索引；0 = 空槽
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Looks          uint32                 `protobuf:"varint,3,opt,name=looks,proto3" json:"looks,omitempty"` // 外观
	Count          uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"` // 叠加数
	Dura           uint32                 `protobuf:"varint,5,opt,name=dura,proto3" json:"dura,omitempty"`
	DuraMax        uint32                 `protobuf:"varint,6,opt,name=dura_max,json=duraMax,proto3" json:"dura_max,omitempty"`
	AttributeFlags uint64                 `protobuf:"varint,7,opt,name=attribute_flags,json=attributeFlags,proto3" json:"attribute_flags,omitempty"`
	Values         []uint32               `protobuf:"varint,8,rep,packed,name=values,proto3" json:"values,omitempty"` // 属性值（DC/MC/SC/AC/MAC 的 min/max 等，顺序另行约定）
	// **卖价**（原版卖东西 = 原价一半，`handleSellItem`）：客户端"卖:"后面
	// 显示的就是它 —— 拖进卖货圈、点 OK 之前就要看到能卖多少钱。
	SellPrice uint32 `protobuf:"varint,11,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// 物品**实例号**（`UserItem.MakeIndex`，全服唯一；0 = 空槽）。
	//
	// ⚠️ 为什么必须有：原版认一件东西靠的就是它 —— `CM_USERSELLITEM` /
	// `CM_USERREPAIRITEM` / 双击使用发的都是 MakeIndex（`ClMain.pas:3711`、
	// `FState.pas:5452`），不是槽位号（背包一压缩，槽位号就指到别人身上了）。
	// 我们原来这一栏没下发 ⇒ 客户端**没法卖东西**（"背包槽 5"在两个面板之间会漂）。
	MakeIndex int32 `protobuf:"varint,9,opt,name=make_index,json=makeIndex,proto3" json:"make_index,omitempty"`
	// 物品**类别**（`StdMode`，原版客户端挑声音用的就是它：`ItemClickSound`，
	// `SoundUtil.pas:293-310` —— 药 108 / 武器 111 / 盔甲 112 / 戒指 113 / 手镯 117 /
	// 项链 115 / 头盔 116 / 其他 118）。少了它客户端只能全体一个声。
	StdMode       uint32 `protobuf:"varint,10,opt,name=std_mode,json=stdMode,proto3" json:"std_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStack) Reset() {
	*x = ItemStack{}
	mi := &file_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStack) ProtoMessage() {}

func (x *ItemStack) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStack.ProtoReflect.Descriptor instead.
func (*ItemStack) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemStack) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ItemStack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemStack) GetLooks() uint32 {
	if x != nil {
		return x.Looks
	}
	return 0
}

func (x *ItemStack) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemStack) GetDura() uint32 {
	if x != nil {
		return x.Dura
	}
	return 0
}

func (x *ItemStack) GetDuraMax() uint32 {
	if x != nil {
		return x.DuraMax
	}
	return 0
}

func (x *ItemStack) GetAttributeFlags() uint64 {
	if x != nil {
		return x.AttributeFlags
	}
	return 0
}

func (x *ItemStack) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *ItemStack) GetSellPrice() uint32 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *ItemStack) GetMakeIndex() int32 {
	if x != nil {
		return x.MakeIndex
	}
	return 0
}

func (x *ItemStack) GetStdMode() uint32 {
	if x != nil {
		return x.StdMode
	}
	return 0
}

// 全量背包（按槽位顺序；空槽为 index=0）。
type BagItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStack           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItems) Reset() {
	*x = BagItems{}
	mi := &file_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItems) ProtoMessage() {}

func (x *BagItems) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItems.ProtoReflect.Descriptor instead.
func (*BagItems) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{1}
}

func (x *BagItems) GetItems() []*ItemStack {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Item          *ItemStack             `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItem) Reset() {
	*x = AddItem{}
	mi := &file_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItem) ProtoMessage() {}

func (x *AddItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItem.ProtoReflect.Descriptor instead.
func (*AddItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{2}
}

func (x *AddItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AddItem) GetItem() *ItemStack {
	if x != nil {
		return x.Item
	}
	return nil
}

type RemoveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItem) Reset() {
	*x = RemoveItem{}
	mi := &file_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItem) ProtoMessage() {}

func (x *RemoveItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItem.ProtoReflect.Descriptor instead.
func (*RemoveItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type UpdateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Item          *ItemStack             `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItem) Reset() {
	*x = UpdateItem{}
	mi := &file_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItem) ProtoMessage() {}

func (x *UpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItem.ProtoReflect.Descriptor instead.
func (*UpdateItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *UpdateItem) GetItem() *ItemStack {
	if x != nil {
		return x.Item
	}
	return nil
}

// 地面物品出现 / 消失（★ 与原版 SM_ITEMSHOW/SM_ITEMHIDE 对应）。
type GroundItemShow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundId      uint64                 `protobuf:"varint,1,opt,name=ground_id,json=groundId,proto3" json:"ground_id,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Item          *ItemStack             `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundItemShow) Reset() {
	*x = GroundItemShow{}
	mi := &file_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundItemShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundItemShow) ProtoMessage() {}

func (x *GroundItemShow) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundItemShow.ProtoReflect.Descriptor instead.
func (*GroundItemShow) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{5}
}

func (x *GroundItemShow) GetGroundId() uint64 {
	if x != nil {
		return x.GroundId
	}
	return 0
}

func (x *GroundItemShow) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *GroundItemShow) GetItem() *ItemStack {
	if x != nil {
		return x.Item
	}
	return nil
}

type GroundItemHide struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundId      uint64                 `protobuf:"varint,1,opt,name=ground_id,json=groundId,proto3" json:"ground_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundItemHide) Reset() {
	*x = GroundItemHide{}
	mi := &file_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundItemHide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundItemHide) ProtoMessage() {}

func (x *GroundItemHide) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundItemHide.ProtoReflect.Descriptor instead.
func (*GroundItemHide) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{6}
}

func (x *GroundItemHide) GetGroundId() uint64 {
	if x != nil {
		return x.GroundId
	}
	return 0
}

// 已穿戴（原版 SM_SENDUSEITEMS）。
type EquippedItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStack           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquippedItems) Reset() {
	*x = EquippedItems{}
	mi := &file_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquippedItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquippedItems) ProtoMessage() {}

func (x *EquippedItems) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquippedItems.ProtoReflect.Descriptor instead.
func (*EquippedItems) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{7}
}

func (x *EquippedItems) GetItems() []*ItemStack {
	if x != nil {
		return x.Items
	}
	return nil
}

type WeightChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        uint32                 `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	MaxWeight     uint32                 `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	WearWeight    uint32                 `protobuf:"varint,3,opt,name=wear_weight,json=wearWeight,proto3" json:"wear_weight,omitempty"`
	MaxWearWeight uint32                 `protobuf:"varint,4,opt,name=max_wear_weight,json=maxWearWeight,proto3" json:"max_wear_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightChanged) Reset() {
	*x = WeightChanged{}
	mi := &file_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightChanged) ProtoMessage() {}

func (x *WeightChanged) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightChanged.ProtoReflect.Descriptor instead.
func (*WeightChanged) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{8}
}

func (x *WeightChanged) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WeightChanged) GetMaxWeight() uint32 {
	if x != nil {
		return x.MaxWeight
	}
	return 0
}

func (x *WeightChanged) GetWearWeight() uint32 {
	if x != nil {
		return x.WearWeight
	}
	return 0
}

func (x *WeightChanged) GetMaxWearWeight() uint32 {
	if x != nil {
		return x.MaxWearWeight
	}
	return 0
}

type GoldChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          uint64                 `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoldChanged) Reset() {
	*x = GoldChanged{}
	mi := &file_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoldChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoldChanged) ProtoMessage() {}

func (x *GoldChanged) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoldChanged.ProtoReflect.Descriptor instead.
func (*GoldChanged) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{9}
}

func (x *GoldChanged) GetGold() uint64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type RepairCostNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Cost          uint32                 `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Special       bool                   `protobuf:"varint,3,opt,name=special,proto3" json:"special,omitempty"` // 特修
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairCostNotice) Reset() {
	*x = RepairCostNotice{}
	mi := &file_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairCostNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairCostNotice) ProtoMessage() {}

func (x *RepairCostNotice) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairCostNotice.ProtoReflect.Descriptor instead.
func (*RepairCostNotice) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{10}
}

func (x *RepairCostNotice) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *RepairCostNotice) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *RepairCostNotice) GetSpecial() bool {
	if x != nil {
		return x.Special
	}
	return false
}

type UseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ClientTick    uint32                 `protobuf:"varint,2,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItem) Reset() {
	*x = UseItem{}
	mi := &file_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItem) ProtoMessage() {}

func (x *UseItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItem.ProtoReflect.Descriptor instead.
func (*UseItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{11}
}

func (x *UseItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *UseItem) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type DropItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ClientTick    uint32                 `protobuf:"varint,3,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropItem) Reset() {
	*x = DropItem{}
	mi := &file_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropItem) ProtoMessage() {}

func (x *DropItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropItem.ProtoReflect.Descriptor instead.
func (*DropItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{12}
}

func (x *DropItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DropItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DropItem) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type PickupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroundId      uint64                 `protobuf:"varint,1,opt,name=ground_id,json=groundId,proto3" json:"ground_id,omitempty"`
	ClientTick    uint32                 `protobuf:"varint,2,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupItem) Reset() {
	*x = PickupItem{}
	mi := &file_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupItem) ProtoMessage() {}

func (x *PickupItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupItem.ProtoReflect.Descriptor instead.
func (*PickupItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{13}
}

func (x *PickupItem) GetGroundId() uint64 {
	if x != nil {
		return x.GroundId
	}
	return 0
}

func (x *PickupItem) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type EquipItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ClientTick    uint32                 `protobuf:"varint,2,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipItem) Reset() {
	*x = EquipItem{}
	mi := &file_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipItem) ProtoMessage() {}

func (x *EquipItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipItem.ProtoReflect.Descriptor instead.
func (*EquipItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{14}
}

func (x *EquipItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *EquipItem) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type UnequipItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipSlot     uint32                 `protobuf:"varint,1,opt,name=equip_slot,json=equipSlot,proto3" json:"equip_slot,omitempty"`
	ClientTick    uint32                 `protobuf:"varint,2,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnequipItem) Reset() {
	*x = UnequipItem{}
	mi := &file_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnequipItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnequipItem) ProtoMessage() {}

func (x *UnequipItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnequipItem.ProtoReflect.Descriptor instead.
func (*UnequipItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{15}
}

func (x *UnequipItem) GetEquipSlot() uint32 {
	if x != nil {
		return x.EquipSlot
	}
	return 0
}

func (x *UnequipItem) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type RepairItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Special       bool                   `protobuf:"varint,2,opt,name=special,proto3" json:"special,omitempty"` // 特修（原版 @s_repair）
	ClientTick    uint32                 `protobuf:"varint,3,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepairItem) Reset() {
	*x = RepairItem{}
	mi := &file_item_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairItem) ProtoMessage() {}

func (x *RepairItem) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairItem.ProtoReflect.Descriptor instead.
func (*RepairItem) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{16}
}

func (x *RepairItem) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *RepairItem) GetSpecial() bool {
	if x != nil {
		return x.Special
	}
	return false
}

func (x *RepairItem) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

// 服务端 → 客户端：一条系统提示（原版 `sysMsg` 的对应物）。
//
// 挖肉的「肉被发现」「什么都没找到」、负重提醒……这些原本走 legacy 的
// `SM_SYSMESSAGE`，proto 玩家收不到 ⇒ 全都无声。客户端收到后推进聊天框。
type SystemNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemNotice) Reset() {
	*x = SystemNotice{}
	mi := &file_item_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNotice) ProtoMessage() {}

func (x *SystemNotice) ProtoReflect() protoreflect.Message {
	mi := &file_item_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNotice.ProtoReflect.Descriptor instead.
func (*SystemNotice) Descriptor() ([]byte, []int) {
	return file_item_proto_rawDescGZIP(), []int{17}
}

func (x *SystemNotice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_item_proto protoreflect.FileDescriptor

const file_item_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"item.proto\x12\x04mir2\x1a\fcommon.proto\"\xaa\x02\n" +
	"\tItemStack\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05looks\x18\x03 \x01(\rR\x05looks\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12\x12\n" +
	"\x04dura\x18\x05 \x01(\rR\x04dura\x12\x19\n" +
	"\bdura_max\x18\x06 \x01(\rR\aduraMax\x12'\n" +
	"\x0fattribute_flags\x18\a \x01(\x04R\x0eattributeFlags\x12\x16\n" +
	"\x06values\x18\b \x03(\rR\x06values\x12\x1d\n" +
	"\n" +
	"sell_price\x18\v \x01(\rR\tsellPrice\x12\x1d\n" +
	"\n" +
	"make_index\x18\t \x01(\x05R\tmakeIndex\x12\x19\n" +
	"\bstd_mode\x18\n" +
	" \x01(\rR\astdMode\"1\n" +
	"\bBagItems\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.mir2.ItemStackR\x05items\"B\n" +
	"\aAddItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12#\n" +
	"\x04item\x18\x02 \x01(\v2\x0f.mir2.ItemStackR\x04item\" \n" +
	"\n" +
	"RemoveItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\"E\n" +
	"\n" +
	"UpdateItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12#\n" +
	"\x04item\x18\x02 \x01(\v2\x0f.mir2.ItemStackR\x04item\"z\n" +
	"\x0eGroundItemShow\x12\x1b\n" +
	"\tground_id\x18\x01 \x01(\x04R\bgroundId\x12&\n" +
	"\bposition\x18\x02 \x01(\v2\n" +
	".mir2.Vec2R\bposition\x12#\n" +
	"\x04item\x18\x03 \x01(\v2\x0f.mir2.ItemStackR\x04item\"-\n" +
	"\x0eGroundItemHide\x12\x1b\n" +
	"\tground_id\x18\x01 \x01(\x04R\bgroundId\"6\n" +
	"\rEquippedItems\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.mir2.ItemStackR\x05items\"\x8f\x01\n" +
	"\rWeightChanged\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\rR\x06weight\x12\x1d\n" +
	"\n" +
	"max_weight\x18\x02 \x01(\rR\tmaxWeight\x12\x1f\n" +
	"\vwear_weight\x18\x03 \x01(\rR\n" +
	"wearWeight\x12&\n" +
	"\x0fmax_wear_weight\x18\x04 \x01(\rR\rmaxWearWeight\"!\n" +
	"\vGoldChanged\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x04R\x04gold\"T\n" +
	"\x10RepairCostNotice\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\rR\x04cost\x12\x18\n" +
	"\aspecial\x18\x03 \x01(\bR\aspecial\">\n" +
	"\aUseItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x1f\n" +
	"\vclient_tick\x18\x02 \x01(\rR\n" +
	"clientTick\"U\n" +
	"\bDropItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1f\n" +
	"\vclient_tick\x18\x03 \x01(\rR\n" +
	"clientTick\"J\n" +
	"\n" +
	"PickupItem\x12\x1b\n" +
	"\tground_id\x18\x01 \x01(\x04R\bgroundId\x12\x1f\n" +
	"\vclient_tick\x18\x02 \x01(\rR\n" +
	"clientTick\"@\n" +
	"\tEquipItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x1f\n" +
	"\vclient_tick\x18\x02 \x01(\rR\n" +
	"clientTick\"M\n" +
	"\vUnequipItem\x12\x1d\n" +
	"\n" +
	"equip_slot\x18\x01 \x01(\rR\tequipSlot\x12\x1f\n" +
	"\vclient_tick\x18\x02 \x01(\rR\n" +
	"clientTick\"[\n" +
	"\n" +
	"RepairItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\rR\x04slot\x12\x18\n" +
	"\aspecial\x18\x02 \x01(\bR\aspecial\x12\x1f\n" +
	"\vclient_tick\x18\x03 \x01(\rR\n" +
	"clientTick\"\"\n" +
	"\fSystemNotice\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textB2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_item_proto_rawDescOnce sync.Once
	file_item_proto_rawDescData []byte
)

func file_item_proto_rawDescGZIP() []byte {
	file_item_proto_rawDescOnce.Do(func() {
		file_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)))
	})
	return file_item_proto_rawDescData
}

var file_item_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_item_proto_goTypes = []any{
	(*ItemStack)(nil),        // 0: mir2.ItemStack
	(*BagItems)(nil),         // 1: mir2.BagItems
	(*AddItem)(nil),          // 2: mir2.AddItem
	(*RemoveItem)(nil),       // 3: mir2.RemoveItem
	(*UpdateItem)(nil),       // 4: mir2.UpdateItem
	(*GroundItemShow)(nil),   // 5: mir2.GroundItemShow
	(*GroundItemHide)(nil),   // 6: mir2.GroundItemHide
	(*EquippedItems)(nil),    // 7: mir2.EquippedItems
	(*WeightChanged)(nil),    // 8: mir2.WeightChanged
	(*GoldChanged)(nil),      // 9: mir2.GoldChanged
	(*RepairCostNotice)(nil), // 10: mir2.RepairCostNotice
	(*UseItem)(nil),          // 11: mir2.UseItem
	(*DropItem)(nil),         // 12: mir2.DropItem
	(*PickupItem)(nil),       // 13: mir2.PickupItem
	(*EquipItem)(nil),        // 14: mir2.EquipItem
	(*UnequipItem)(nil),      // 15: mir2.UnequipItem
	(*RepairItem)(nil),       // 16: mir2.RepairItem
	(*SystemNotice)(nil),     // 17: mir2.SystemNotice
	(*Vec2)(nil),             // 18: mir2.Vec2
}
var file_item_proto_depIdxs = []int32{
	0,  // 0: mir2.BagItems.items:type_name -> mir2.ItemStack
	0,  // 1: mir2.AddItem.item:type_name -> mir2.ItemStack
	0,  // 2: mir2.UpdateItem.item:type_name -> mir2.ItemStack
	18, // 3: mir2.GroundItemShow.position:type_name -> mir2.Vec2
	0,  // 4: mir2.GroundItemShow.item:type_name -> mir2.ItemStack
	0,  // 5: mir2.EquippedItems.items:type_name -> mir2.ItemStack
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_item_proto_init() }
func file_item_proto_init() {
	if File_item_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_proto_rawDesc), len(file_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_proto_goTypes,
		DependencyIndexes: file_item_proto_depIdxs,
		MessageInfos:      file_item_proto_msgTypes,
	}.Build()
	File_item_proto = out.File
	file_item_proto_goTypes = nil
	file_item_proto_depIdxs = nil
}
