// MIR2 协议 · 0x0Axx NPC 对话与商店
//
// 原版把 NPC 对话拆成三条：CM_CLICKNPC(1010) + CM_MERCHANTDLGSELECT(1011) +
// SM_MERCHANTDLG(**服务端把"文本 + 编号选项"拼成一整块**塞在 body 里发出去，
// 见 `M2Server/npcdlg.go` 现在走的那条 legacy 路)，商店则是一堆 `SM_*` 号。
//
// 本版把它拆成**结构化**的样子：说一段话 + 一组可点选项，客户端回一个下标。
// 好处是客户端不用解析中文文本里的 `[1] xxx` 编号，也不必猜哪几行是选项。
//
// ⚠️ 与 `npcdlg.go` 的映射：脚本里一段（`[@标签]`）的 `Say` 是 `NpcSay.text`，
// `Links`（`<文字/@标签>`）逐条变成 `NpcOption`，`index` 从 **1** 起（与原版
// "Recog = 选项序号" 那套一致，`ClMain.pas:3661-3681`）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: npc.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端 → 服务端：点了一个 NPC（原版 `CM_CLICKNPC`，Recog = NPC 的 ActorId）。
type NpcClick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcClick) Reset() {
	*x = NpcClick{}
	mi := &file_npc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcClick) ProtoMessage() {}

func (x *NpcClick) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcClick.ProtoReflect.Descriptor instead.
func (*NpcClick) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{0}
}

func (x *NpcClick) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

// 一个可点选项（对应脚本里的 `<文字/@标签>`）。
type NpcOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based 序号（客户端原样回传，服务端按下标找 `Links`）。
	Index         uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcOption) Reset() {
	*x = NpcOption{}
	mi := &file_npc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcOption) ProtoMessage() {}

func (x *NpcOption) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcOption.ProtoReflect.Descriptor instead.
func (*NpcOption) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{1}
}

func (x *NpcOption) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NpcOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 服务端 → 客户端：NPC 说一段话 + 可点选项。
type NpcSay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	NpcId uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	// 正文（可能多行；脚本里的续行符已去掉）。
	Text          string       `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []*NpcOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcSay) Reset() {
	*x = NpcSay{}
	mi := &file_npc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcSay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcSay) ProtoMessage() {}

func (x *NpcSay) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcSay.ProtoReflect.Descriptor instead.
func (*NpcSay) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{2}
}

func (x *NpcSay) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *NpcSay) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NpcSay) GetOptions() []*NpcOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// 客户端 → 服务端：选了第 index 项（1-based）。
type NpcSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcSelect) Reset() {
	*x = NpcSelect{}
	mi := &file_npc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcSelect) ProtoMessage() {}

func (x *NpcSelect) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcSelect.ProtoReflect.Descriptor instead.
func (*NpcSelect) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{3}
}

func (x *NpcSelect) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *NpcSelect) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 客户端 → 服务端：关掉对话（原版 `@exit`；服务端清 `p.dialog`）。
type NpcClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcClose) Reset() {
	*x = NpcClose{}
	mi := &file_npc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcClose) ProtoMessage() {}

func (x *NpcClose) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcClose.ProtoReflect.Descriptor instead.
func (*NpcClose) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{4}
}

func (x *NpcClose) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

var File_npc_proto protoreflect.FileDescriptor

const file_npc_proto_rawDesc = "" +
	"\n" +
	"\tnpc.proto\x12\x04mir2\"!\n" +
	"\bNpcClick\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\"5\n" +
	"\tNpcOption\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"^\n" +
	"\x06NpcSay\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12)\n" +
	"\aoptions\x18\x03 \x03(\v2\x0f.mir2.NpcOptionR\aoptions\"8\n" +
	"\tNpcSelect\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"!\n" +
	"\bNpcClose\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcIdB2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_npc_proto_rawDescOnce sync.Once
	file_npc_proto_rawDescData []byte
)

func file_npc_proto_rawDescGZIP() []byte {
	file_npc_proto_rawDescOnce.Do(func() {
		file_npc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_npc_proto_rawDesc), len(file_npc_proto_rawDesc)))
	})
	return file_npc_proto_rawDescData
}

var file_npc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_npc_proto_goTypes = []any{
	(*NpcClick)(nil),  // 0: mir2.NpcClick
	(*NpcOption)(nil), // 1: mir2.NpcOption
	(*NpcSay)(nil),    // 2: mir2.NpcSay
	(*NpcSelect)(nil), // 3: mir2.NpcSelect
	(*NpcClose)(nil),  // 4: mir2.NpcClose
}
var file_npc_proto_depIdxs = []int32{
	1, // 0: mir2.NpcSay.options:type_name -> mir2.NpcOption
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_npc_proto_init() }
func file_npc_proto_init() {
	if File_npc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_npc_proto_rawDesc), len(file_npc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_npc_proto_goTypes,
		DependencyIndexes: file_npc_proto_depIdxs,
		MessageInfos:      file_npc_proto_msgTypes,
	}.Build()
	File_npc_proto = out.File
	file_npc_proto_goTypes = nil
	file_npc_proto_depIdxs = nil
}
