// MIR2 协议 · 0x0Axx NPC 对话与商店
//
// 原版把 NPC 对话拆成三条：CM_CLICKNPC(1010) + CM_MERCHANTDLGSELECT(1011) +
// SM_MERCHANTDLG(**服务端把"文本 + 编号选项"拼成一整块**塞在 body 里发出去，
// 见 `M2Server/npcdlg.go` 现在走的那条 legacy 路)，商店则是一堆 `SM_*` 号。
//
// 本版把它拆成**结构化**的样子：说一段话 + 一组可点选项，客户端回一个下标。
// 好处是客户端不用解析中文文本里的 `[1] xxx` 编号，也不必猜哪几行是选项。
//
// ⚠️ 与 `npcdlg.go` 的映射：脚本里一段（`[@标签]`）的 `Say` 是 `NpcSay.text`，
// `Links`（`<文字/@标签>`）逐条变成 `NpcOption`，`index` 从 **1** 起（与原版
// "Recog = 选项序号" 那套一致，`ClMain.pas:3661-3681`）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: npc.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端 → 服务端：点了一个 NPC（原版 `CM_CLICKNPC`，Recog = NPC 的 ActorId）。
type NpcClick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcClick) Reset() {
	*x = NpcClick{}
	mi := &file_npc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcClick) ProtoMessage() {}

func (x *NpcClick) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcClick.ProtoReflect.Descriptor instead.
func (*NpcClick) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{0}
}

func (x *NpcClick) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

// 一个可点选项（对应脚本里的 `<文字/@标签>`）。
type NpcOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based 序号（客户端原样回传，服务端按下标找 `Links`）。
	Index         uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcOption) Reset() {
	*x = NpcOption{}
	mi := &file_npc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcOption) ProtoMessage() {}

func (x *NpcOption) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcOption.ProtoReflect.Descriptor instead.
func (*NpcOption) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{1}
}

func (x *NpcOption) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *NpcOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 服务端 → 客户端：NPC 说一段话 + 可点选项。
type NpcSay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	NpcId uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	// 正文（可能多行；脚本里的续行符已去掉）。
	Text          string       `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []*NpcOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcSay) Reset() {
	*x = NpcSay{}
	mi := &file_npc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcSay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcSay) ProtoMessage() {}

func (x *NpcSay) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcSay.ProtoReflect.Descriptor instead.
func (*NpcSay) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{2}
}

func (x *NpcSay) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *NpcSay) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NpcSay) GetOptions() []*NpcOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// 客户端 → 服务端：选了第 index 项（1-based）。
type NpcSelect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcSelect) Reset() {
	*x = NpcSelect{}
	mi := &file_npc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcSelect) ProtoMessage() {}

func (x *NpcSelect) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcSelect.ProtoReflect.Descriptor instead.
func (*NpcSelect) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{3}
}

func (x *NpcSelect) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *NpcSelect) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 客户端 → 服务端：关掉对话（原版 `@exit`；服务端清 `p.dialog`）。
type NpcClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpcClose) Reset() {
	*x = NpcClose{}
	mi := &file_npc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpcClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpcClose) ProtoMessage() {}

func (x *NpcClose) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpcClose.ProtoReflect.Descriptor instead.
func (*NpcClose) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{4}
}

func (x *NpcClose) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

// ---------- 商店（原版 `SM_SENDGOODSLIST` / `CM_BUYITEM` / `CM_SELLITEM`）----------
//
// 原版那条是**文本协议**：把"名称/子菜单/价格/存量/"拼成一整串塞在 body 里
// （`ObjNpc.pas:1449-1455` 写、`ClMain.pas:6158-6190` 用 `'/'` 切四次读出来），
// 买入时再把"名字 + 存量"当 `Param/Tag` 回发（`FState.pas:5244`）。
// 我们照例拆成结构化消息：**服务端不依赖客户端回发的存量**（买入按名字解析，
// 见 `shop.go` 的 `shopGoodsByName`）。
type ShopItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price uint64                 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	// 货架存量：我们的商品按模板即时生成、永不缺货 ⇒ 这一栏只用于**显示**（见 `shop.go`
	// 的 `shopStock`）。
	Stock uint32 `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	// 要不要弹"买几个"的二级菜单（原版 `submenu`：可堆叠类为 0，其余为 1）。
	Submenu bool `protobuf:"varint,4,opt,name=submenu,proto3" json:"submenu,omitempty"`
	// 最大持久（原版商品列表第三栏"持久"显示的就是它，`FState.pas` 的买窗）。
	DuraMax       uint32 `protobuf:"varint,5,opt,name=dura_max,json=duraMax,proto3" json:"dura_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_npc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{5}
}

func (x *ShopItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopItem) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ShopItem) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ShopItem) GetSubmenu() bool {
	if x != nil {
		return x.Submenu
	}
	return false
}

func (x *ShopItem) GetDuraMax() uint32 {
	if x != nil {
		return x.DuraMax
	}
	return 0
}

// 服务端 → 客户端：这个商人的商品列表（原版 `SM_SENDGOODSLIST`）。
type ShopList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	NpcId uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Items []*ShopItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	// **开的是哪个窗**：1 = 买（商品列表），2 = 卖（放物品的槽）。
	//
	// ⚠️ 为什么要有：原版点 NPC 脚本里的 `<我要买/@buy>` 与 `<我要卖/@sell>` 弹的是
	// **两个不同的窗**（列表窗 / 卖出窗），数据都是同一次 `SM_SENDGOODSLIST` 来的。
	// 我们少了这一位 ⇒ 点"卖"时只能要么两个窗一起弹、要么都不弹
	//（用户 2026-10-10："卖售窗口没有出现"）。
	Mode          uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopList) Reset() {
	*x = ShopList{}
	mi := &file_npc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopList) ProtoMessage() {}

func (x *ShopList) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopList.ProtoReflect.Descriptor instead.
func (*ShopList) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{6}
}

func (x *ShopList) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopList) GetItems() []*ShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShopList) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 客户端 → 服务端：买 `count` 个 `name`（原版 `CM_BUYITEM` 的 `Param=存量 / Tag=名字`）。
type ShopBuy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NpcId         uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopBuy) Reset() {
	*x = ShopBuy{}
	mi := &file_npc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopBuy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopBuy) ProtoMessage() {}

func (x *ShopBuy) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopBuy.ProtoReflect.Descriptor instead.
func (*ShopBuy) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{7}
}

func (x *ShopBuy) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopBuy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShopBuy) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 客户端 → 服务端：卖背包里 `make_index` 那一个（原版 `CM_SELLITEM` 用 MakeIndex 认物）。
type ShopSell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	NpcId uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	// 物品实例号（`UserItem.make_index`）；`count > 1` 时按可堆叠数量卖。
	MakeIndex     int32  `protobuf:"varint,2,opt,name=make_index,json=makeIndex,proto3" json:"make_index,omitempty"`
	Count         uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopSell) Reset() {
	*x = ShopSell{}
	mi := &file_npc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopSell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopSell) ProtoMessage() {}

func (x *ShopSell) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopSell.ProtoReflect.Descriptor instead.
func (*ShopSell) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{8}
}

func (x *ShopSell) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopSell) GetMakeIndex() int32 {
	if x != nil {
		return x.MakeIndex
	}
	return 0
}

func (x *ShopSell) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 服务端 → 客户端：买卖的结果（原版是 `SM_BUYITEM_SUCCESS` / `SM_SOLD_FAIL` 那几个号
// + 随后的金币/背包刷新）。
//
// ⚠️ 成功后的**背包与金币**由 `BagItems` / `AbilityUpdate` 照常下发，不挤在这里。
type ShopResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	NpcId uint64                 `protobuf:"varint,1,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// 失败原因（金币不够 / 负重超了 / 没有这件…），人能读。
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopResult) Reset() {
	*x = ShopResult{}
	mi := &file_npc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopResult) ProtoMessage() {}

func (x *ShopResult) ProtoReflect() protoreflect.Message {
	mi := &file_npc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopResult.ProtoReflect.Descriptor instead.
func (*ShopResult) Descriptor() ([]byte, []int) {
	return file_npc_proto_rawDescGZIP(), []int{9}
}

func (x *ShopResult) GetNpcId() uint64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *ShopResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ShopResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_npc_proto protoreflect.FileDescriptor

const file_npc_proto_rawDesc = "" +
	"\n" +
	"\tnpc.proto\x12\x04mir2\"!\n" +
	"\bNpcClick\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\"5\n" +
	"\tNpcOption\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"^\n" +
	"\x06NpcSay\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12)\n" +
	"\aoptions\x18\x03 \x03(\v2\x0f.mir2.NpcOptionR\aoptions\"8\n" +
	"\tNpcSelect\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"!\n" +
	"\bNpcClose\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\"\x7f\n" +
	"\bShopItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x04R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\rR\x05stock\x12\x18\n" +
	"\asubmenu\x18\x04 \x01(\bR\asubmenu\x12\x19\n" +
	"\bdura_max\x18\x05 \x01(\rR\aduraMax\"[\n" +
	"\bShopList\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12$\n" +
	"\x05items\x18\x02 \x03(\v2\x0e.mir2.ShopItemR\x05items\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"J\n" +
	"\aShopBuy\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"V\n" +
	"\bShopSell\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x1d\n" +
	"\n" +
	"make_index\x18\x02 \x01(\x05R\tmakeIndex\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"M\n" +
	"\n" +
	"ShopResult\x12\x15\n" +
	"\x06npc_id\x18\x01 \x01(\x04R\x05npcId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_npc_proto_rawDescOnce sync.Once
	file_npc_proto_rawDescData []byte
)

func file_npc_proto_rawDescGZIP() []byte {
	file_npc_proto_rawDescOnce.Do(func() {
		file_npc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_npc_proto_rawDesc), len(file_npc_proto_rawDesc)))
	})
	return file_npc_proto_rawDescData
}

var file_npc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_npc_proto_goTypes = []any{
	(*NpcClick)(nil),   // 0: mir2.NpcClick
	(*NpcOption)(nil),  // 1: mir2.NpcOption
	(*NpcSay)(nil),     // 2: mir2.NpcSay
	(*NpcSelect)(nil),  // 3: mir2.NpcSelect
	(*NpcClose)(nil),   // 4: mir2.NpcClose
	(*ShopItem)(nil),   // 5: mir2.ShopItem
	(*ShopList)(nil),   // 6: mir2.ShopList
	(*ShopBuy)(nil),    // 7: mir2.ShopBuy
	(*ShopSell)(nil),   // 8: mir2.ShopSell
	(*ShopResult)(nil), // 9: mir2.ShopResult
}
var file_npc_proto_depIdxs = []int32{
	1, // 0: mir2.NpcSay.options:type_name -> mir2.NpcOption
	5, // 1: mir2.ShopList.items:type_name -> mir2.ShopItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_npc_proto_init() }
func file_npc_proto_init() {
	if File_npc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_npc_proto_rawDesc), len(file_npc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_npc_proto_goTypes,
		DependencyIndexes: file_npc_proto_depIdxs,
		MessageInfos:      file_npc_proto_msgTypes,
	}.Build()
	File_npc_proto = out.File
	file_npc_proto_goTypes = nil
	file_npc_proto_depIdxs = nil
}
