// MIR2 协议 · 0x04xx 场景 / 0x05xx 实体
//
// 对应 docs/protocol.md §7（实体标识）与 §8（移动与预测）。
// ★ `entity_id` 是 **uint64 全局唯一**，由服务端分配 —— 取代原版 16 位 `Series`
//   （装不下 ActorId，被迫"坐标优先定位目标"）。
// ★ 沿用 mir2go 的分段：玩家 < 1_000_000、怪物 ≥ 1_000_000、NPC ≥ 2_000_000。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: scene.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisappearReason int32

const (
	DisappearReason_DISAPPEAR_REASON_UNSPECIFIED DisappearReason = 0
	DisappearReason_DISAPPEAR_LEFT_VIEW          DisappearReason = 1 // 离开视野
	DisappearReason_DISAPPEAR_HIDE               DisappearReason = 2 // 隐身
	DisappearReason_DISAPPEAR_DEAD               DisappearReason = 3 // 死亡移出（尸骨另见 Death）
	DisappearReason_DISAPPEAR_LOGOUT             DisappearReason = 4
)

// Enum value maps for DisappearReason.
var (
	DisappearReason_name = map[int32]string{
		0: "DISAPPEAR_REASON_UNSPECIFIED",
		1: "DISAPPEAR_LEFT_VIEW",
		2: "DISAPPEAR_HIDE",
		3: "DISAPPEAR_DEAD",
		4: "DISAPPEAR_LOGOUT",
	}
	DisappearReason_value = map[string]int32{
		"DISAPPEAR_REASON_UNSPECIFIED": 0,
		"DISAPPEAR_LEFT_VIEW":          1,
		"DISAPPEAR_HIDE":               2,
		"DISAPPEAR_DEAD":               3,
		"DISAPPEAR_LOGOUT":             4,
	}
)

func (x DisappearReason) Enum() *DisappearReason {
	p := new(DisappearReason)
	*p = x
	return p
}

func (x DisappearReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisappearReason) Descriptor() protoreflect.EnumDescriptor {
	return file_scene_proto_enumTypes[0].Descriptor()
}

func (DisappearReason) Type() protoreflect.EnumType {
	return &file_scene_proto_enumTypes[0]
}

func (x DisappearReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisappearReason.Descriptor instead.
func (DisappearReason) EnumDescriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

// 实体的完整快照（进图初始快照 / 实体出现 用）。
type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Kind          uint32                 `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"` // 0=玩家 1=怪物 2=NPC
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Position      *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=mir2.Direction" json:"direction,omitempty"`
	Feature       *EntityFeature         `protobuf:"bytes,6,opt,name=feature,proto3" json:"feature,omitempty"`
	Hp            uint32                 `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         uint32                 `protobuf:"varint,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	StatusBits    uint64                 `protobuf:"varint,9,opt,name=status_bits,json=statusBits,proto3" json:"status_bits,omitempty"`
	Action        uint32                 `protobuf:"varint,10,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

func (x *EntityState) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *EntityState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityState) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityState) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *EntityState) GetFeature() *EntityFeature {
	if x != nil {
		return x.Feature
	}
	return nil
}

func (x *EntityState) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityState) GetMaxHp() uint32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EntityState) GetStatusBits() uint64 {
	if x != nil {
		return x.StatusBits
	}
	return 0
}

func (x *EntityState) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 服务端 → 客户端：进世界（选角成功后的初始快照）。
type EnterWorld struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SelfEntityId uint64                 `protobuf:"varint,1,opt,name=self_entity_id,json=selfEntityId,proto3" json:"self_entity_id,omitempty"`
	MapId        uint32                 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	MapName      string                 `protobuf:"bytes,3,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	Position     *Vec2                  `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Direction    Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=mir2.Direction" json:"direction,omitempty"`
	Entities     []*EntityState         `protobuf:"bytes,6,rep,name=entities,proto3" json:"entities,omitempty"`
	ServerTick   uint32                 `protobuf:"varint,7,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	// 自己的外观 —— **不在 `entities` 里**：快照刻意不包含自己（自己由 `self_entity_id`
	// 与移动/心跳回显维护）。少了它客户端就画不出自己的精灵（连"自己长什么样"都不知道）。
	SelfFeature *EntityFeature `protobuf:"bytes,8,opt,name=self_feature,json=selfFeature,proto3" json:"self_feature,omitempty"`
	// 小地图图号（0 = 该图没有小地图）。
	//
	// 来源：服务端 `data/envir/MiniMap.txt` 的"地图号 → 小地图编号"（`s.cfg.miniMaps`）。
	// 客户端拿它当 **`mmap` 图库的下标（图号 - 1）** 去取整张地图的缩略图 ——
	// 与 legacy 的 `CM_WANTMINIMAP`/`SM_READMINIMAP_OK` 是同一份数据（`ClMain.pas:6045-6051`），
	// 只是新协议不再单开一问一答：进图/换图那条消息顺手带上。
	MinimapIndex uint32 `protobuf:"varint,9,opt,name=minimap_index,json=minimapIndex,proto3" json:"minimap_index,omitempty"`
	// 自己的**角色名**（要画在自己头顶：原版 `FState.pas` 的头顶血条 + 名字）。
	// 快照里不含自己（见 `self_feature` 的说明），所以名字必须单独给 —— 否则客户端
	// 只能显示占位符（我们之前写的是 "[自己]"）。
	SelfName      string `protobuf:"bytes,10,opt,name=self_name,json=selfName,proto3" json:"self_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterWorld) Reset() {
	*x = EnterWorld{}
	mi := &file_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorld) ProtoMessage() {}

func (x *EnterWorld) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorld.ProtoReflect.Descriptor instead.
func (*EnterWorld) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{1}
}

func (x *EnterWorld) GetSelfEntityId() uint64 {
	if x != nil {
		return x.SelfEntityId
	}
	return 0
}

func (x *EnterWorld) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *EnterWorld) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *EnterWorld) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EnterWorld) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *EnterWorld) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EnterWorld) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *EnterWorld) GetSelfFeature() *EntityFeature {
	if x != nil {
		return x.SelfFeature
	}
	return nil
}

func (x *EnterWorld) GetMinimapIndex() uint32 {
	if x != nil {
		return x.MinimapIndex
	}
	return 0
}

func (x *EnterWorld) GetSelfName() string {
	if x != nil {
		return x.SelfName
	}
	return ""
}

// 服务端 → 客户端：切换地图（重发新图快照）。
type ChangeMap struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MapId      uint32                 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	MapName    string                 `protobuf:"bytes,2,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	Position   *Vec2                  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Entities   []*EntityState         `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	ServerTick uint32                 `protobuf:"varint,5,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	// 自己的外观，与 `EnterWorld.self_feature` 同义（换图后重发一次）。
	SelfFeature *EntityFeature `protobuf:"bytes,6,opt,name=self_feature,json=selfFeature,proto3" json:"self_feature,omitempty"`
	// 小地图图号 —— 换图了就是另一张缩略图，与 `EnterWorld.minimap_index` 同义。
	MinimapIndex  uint32 `protobuf:"varint,7,opt,name=minimap_index,json=minimapIndex,proto3" json:"minimap_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMap) Reset() {
	*x = ChangeMap{}
	mi := &file_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMap) ProtoMessage() {}

func (x *ChangeMap) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMap.ProtoReflect.Descriptor instead.
func (*ChangeMap) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeMap) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ChangeMap) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *ChangeMap) GetPosition() *Vec2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ChangeMap) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ChangeMap) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *ChangeMap) GetSelfFeature() *EntityFeature {
	if x != nil {
		return x.SelfFeature
	}
	return nil
}

func (x *ChangeMap) GetMinimapIndex() uint32 {
	if x != nil {
		return x.MinimapIndex
	}
	return 0
}

// 大块地图数据 —— 独立分块传输（protocol.md §2：大二进制块单独分帧）。
type MapChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         uint32                 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	ChunkCount    uint32                 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChunk) Reset() {
	*x = MapChunk{}
	mi := &file_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChunk) ProtoMessage() {}

func (x *MapChunk) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChunk.ProtoReflect.Descriptor instead.
func (*MapChunk) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{3}
}

func (x *MapChunk) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *MapChunk) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *MapChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 日夜 / 光照（原版 SM_DAYCHANGING / SM_CHANGELIGHT）。
type TimeOfDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          uint32                 `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute        uint32                 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	Dark          bool                   `protobuf:"varint,3,opt,name=dark,proto3" json:"dark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeOfDay) Reset() {
	*x = TimeOfDay{}
	mi := &file_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeOfDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeOfDay) ProtoMessage() {}

func (x *TimeOfDay) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeOfDay.ProtoReflect.Descriptor instead.
func (*TimeOfDay) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{4}
}

func (x *TimeOfDay) GetHour() uint32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *TimeOfDay) GetMinute() uint32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

func (x *TimeOfDay) GetDark() bool {
	if x != nil {
		return x.Dark
	}
	return false
}

type MapDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         uint32                 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapDescription) Reset() {
	*x = MapDescription{}
	mi := &file_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapDescription) ProtoMessage() {}

func (x *MapDescription) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapDescription.ProtoReflect.Descriptor instead.
func (*MapDescription) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{5}
}

func (x *MapDescription) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapDescription) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type EntityAppear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *EntityState           `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAppear) Reset() {
	*x = EntityAppear{}
	mi := &file_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAppear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAppear) ProtoMessage() {}

func (x *EntityAppear) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAppear.ProtoReflect.Descriptor instead.
func (*EntityAppear) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{6}
}

func (x *EntityAppear) GetEntity() *EntityState {
	if x != nil {
		return x.Entity
	}
	return nil
}

type EntityDisappear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason        DisappearReason        `protobuf:"varint,2,opt,name=reason,proto3,enum=mir2.DisappearReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDisappear) Reset() {
	*x = EntityDisappear{}
	mi := &file_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDisappear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDisappear) ProtoMessage() {}

func (x *EntityDisappear) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDisappear.ProtoReflect.Descriptor instead.
func (*EntityDisappear) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{7}
}

func (x *EntityDisappear) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityDisappear) GetReason() DisappearReason {
	if x != nil {
		return x.Reason
	}
	return DisappearReason_DISAPPEAR_REASON_UNSPECIFIED
}

// 服务端权威移动广播（高频位置：可丢弃过期包，按 seq 丢弃）。
type EntityMove struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EntityId   uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	From       *Vec2                  `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To         *Vec2                  `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Direction  Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=mir2.Direction" json:"direction,omitempty"`
	ServerTick uint32                 `protobuf:"varint,5,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	// 这一步是**跑**（原版是 `SM_RUN` 与 `SM_WALK` 两条消息；这里用一个标志位）。
	//
	// 客户端要它才能播对动画：走是 `ActWalk`（6 帧 × 90 ms）、跑是 `ActRun`
	//（6 帧 × 120 ms），两段的图号差 64（`Actor.pas:77-78`）。少了这个字段，
	// 跑起来只能放走的动画 —— 而且**连别人跑起来也看不出来**。
	Run           bool `protobuf:"varint,6,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMove) Reset() {
	*x = EntityMove{}
	mi := &file_scene_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMove) ProtoMessage() {}

func (x *EntityMove) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMove.ProtoReflect.Descriptor instead.
func (*EntityMove) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{8}
}

func (x *EntityMove) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityMove) GetFrom() *Vec2 {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EntityMove) GetTo() *Vec2 {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EntityMove) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *EntityMove) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *EntityMove) GetRun() bool {
	if x != nil {
		return x.Run
	}
	return false
}

// 动作切换（走/跑/攻击/受击/死亡/骑马…）。用动作 id + 时间戳，取代原版 70 个手写动画类。
//
// ⚠️ `action` 的**值域**见 docs/protocol.md §9.5（1..8 与 AttackAction 同值 / 51 受击 /
// 52 死亡）。它是本项目**自己定的**：原版那 70 个动画类没法照搬，也不该照搬。
type EntityAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action        uint32                 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	ServerTick    uint32                 `protobuf:"varint,3,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAction) Reset() {
	*x = EntityAction{}
	mi := &file_scene_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAction) ProtoMessage() {}

func (x *EntityAction) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAction.ProtoReflect.Descriptor instead.
func (*EntityAction) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{9}
}

func (x *EntityAction) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityAction) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *EntityAction) GetServerTick() uint32 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

type EntityHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Hp            uint32                 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         uint32                 `protobuf:"varint,3,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityHealth) Reset() {
	*x = EntityHealth{}
	mi := &file_scene_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityHealth) ProtoMessage() {}

func (x *EntityHealth) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityHealth.ProtoReflect.Descriptor instead.
func (*EntityHealth) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{10}
}

func (x *EntityHealth) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityHealth) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityHealth) GetMaxHp() uint32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

type EntityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	StatusBits    uint64                 `protobuf:"varint,2,opt,name=status_bits,json=statusBits,proto3" json:"status_bits,omitempty"` // 隐身/中毒/石化…（约定见 decisions D-… 待定）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityStatus) Reset() {
	*x = EntityStatus{}
	mi := &file_scene_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStatus) ProtoMessage() {}

func (x *EntityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStatus.ProtoReflect.Descriptor instead.
func (*EntityStatus) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{11}
}

func (x *EntityStatus) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityStatus) GetStatusBits() uint64 {
	if x != nil {
		return x.StatusBits
	}
	return 0
}

// 自身能力值（`Ability` 定义在 common.proto，scene 与 combat 共用）。
type AbilityUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ability       *Ability               `protobuf:"bytes,1,opt,name=ability,proto3" json:"ability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityUpdate) Reset() {
	*x = AbilityUpdate{}
	mi := &file_scene_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityUpdate) ProtoMessage() {}

func (x *AbilityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityUpdate.ProtoReflect.Descriptor instead.
func (*AbilityUpdate) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{12}
}

func (x *AbilityUpdate) GetAbility() *Ability {
	if x != nil {
		return x.Ability
	}
	return nil
}

// 客户端 → 服务端：移动输入（★ 有且仅有一次生效：带 request_id 走信封）。
type MoveInput struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	From       *Vec2                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To         *Vec2                  `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Direction  Direction              `protobuf:"varint,3,opt,name=direction,proto3,enum=mir2.Direction" json:"direction,omitempty"`
	ClientTick uint32                 `protobuf:"varint,4,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	// 跑（原版 `CM_RUN`）：**一步 2 格**、节流比走短（`MinRun` vs `MinWalk`）。
	//
	// 原版客户端：按住右键（远距）或 Ctrl+左键 = 跑（`ClMain.pas:2200-2244 / 2344-2352`），
	// 其余左键 = 走；跑一步的位移见 `GetNextRunXY`（+2 格，`ClFunc.pas:370-382`）。
	//
	// ⚠️ 老客户端不填这个字段 ⇒ 默认 false = 走，行为与以前完全一致
	//（所以**不需要** bump `version.txt`：加带默认值的可选字段是兼容变更）。
	Run           bool `protobuf:"varint,5,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	mi := &file_scene_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{13}
}

func (x *MoveInput) GetFrom() *Vec2 {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MoveInput) GetTo() *Vec2 {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MoveInput) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *MoveInput) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *MoveInput) GetRun() bool {
	if x != nil {
		return x.Run
	}
	return false
}

// 服务端 → 客户端：移动被拒（越界/超速），回权威位置校正。
type MoveRejected struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AuthoritativePosition *Vec2                  `protobuf:"bytes,1,opt,name=authoritative_position,json=authoritativePosition,proto3" json:"authoritative_position,omitempty"`
	Reason                uint32                 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"` // 1=超速 2=越界 3=阻挡
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MoveRejected) Reset() {
	*x = MoveRejected{}
	mi := &file_scene_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRejected) ProtoMessage() {}

func (x *MoveRejected) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRejected.ProtoReflect.Descriptor instead.
func (*MoveRejected) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{14}
}

func (x *MoveRejected) GetAuthoritativePosition() *Vec2 {
	if x != nil {
		return x.AuthoritativePosition
	}
	return nil
}

func (x *MoveRejected) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type EntityFeatureChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Feature       *EntityFeature         `protobuf:"bytes,2,opt,name=feature,proto3" json:"feature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityFeatureChanged) Reset() {
	*x = EntityFeatureChanged{}
	mi := &file_scene_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityFeatureChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityFeatureChanged) ProtoMessage() {}

func (x *EntityFeatureChanged) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityFeatureChanged.ProtoReflect.Descriptor instead.
func (*EntityFeatureChanged) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{15}
}

func (x *EntityFeatureChanged) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityFeatureChanged) GetFeature() *EntityFeature {
	if x != nil {
		return x.Feature
	}
	return nil
}

var File_scene_proto protoreflect.FileDescriptor

const file_scene_proto_rawDesc = "" +
	"\n" +
	"\vscene.proto\x12\x04mir2\x1a\fcommon.proto\"\xb8\x02\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\rR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12&\n" +
	"\bposition\x18\x04 \x01(\v2\n" +
	".mir2.Vec2R\bposition\x12-\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x0f.mir2.DirectionR\tdirection\x12-\n" +
	"\afeature\x18\x06 \x01(\v2\x13.mir2.EntityFeatureR\afeature\x12\x0e\n" +
	"\x02hp\x18\a \x01(\rR\x02hp\x12\x15\n" +
	"\x06max_hp\x18\b \x01(\rR\x05maxHp\x12\x1f\n" +
	"\vstatus_bits\x18\t \x01(\x04R\n" +
	"statusBits\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\rR\x06action\"\x85\x03\n" +
	"\n" +
	"EnterWorld\x12$\n" +
	"\x0eself_entity_id\x18\x01 \x01(\x04R\fselfEntityId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\rR\x05mapId\x12\x19\n" +
	"\bmap_name\x18\x03 \x01(\tR\amapName\x12&\n" +
	"\bposition\x18\x04 \x01(\v2\n" +
	".mir2.Vec2R\bposition\x12-\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x0f.mir2.DirectionR\tdirection\x12-\n" +
	"\bentities\x18\x06 \x03(\v2\x11.mir2.EntityStateR\bentities\x12\x1f\n" +
	"\vserver_tick\x18\a \x01(\rR\n" +
	"serverTick\x126\n" +
	"\fself_feature\x18\b \x01(\v2\x13.mir2.EntityFeatureR\vselfFeature\x12#\n" +
	"\rminimap_index\x18\t \x01(\rR\fminimapIndex\x12\x1b\n" +
	"\tself_name\x18\n" +
	" \x01(\tR\bselfName\"\x92\x02\n" +
	"\tChangeMap\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\rR\x05mapId\x12\x19\n" +
	"\bmap_name\x18\x02 \x01(\tR\amapName\x12&\n" +
	"\bposition\x18\x03 \x01(\v2\n" +
	".mir2.Vec2R\bposition\x12-\n" +
	"\bentities\x18\x04 \x03(\v2\x11.mir2.EntityStateR\bentities\x12\x1f\n" +
	"\vserver_tick\x18\x05 \x01(\rR\n" +
	"serverTick\x126\n" +
	"\fself_feature\x18\x06 \x01(\v2\x13.mir2.EntityFeatureR\vselfFeature\x12#\n" +
	"\rminimap_index\x18\a \x01(\rR\fminimapIndex\"w\n" +
	"\bMapChunk\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\rR\x05mapId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\rR\n" +
	"chunkCount\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"K\n" +
	"\tTimeOfDay\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\rR\x04hour\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\rR\x06minute\x12\x12\n" +
	"\x04dark\x18\x03 \x01(\bR\x04dark\"I\n" +
	"\x0eMapDescription\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\rR\x05mapId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"9\n" +
	"\fEntityAppear\x12)\n" +
	"\x06entity\x18\x01 \x01(\v2\x11.mir2.EntityStateR\x06entity\"]\n" +
	"\x0fEntityDisappear\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12-\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x15.mir2.DisappearReasonR\x06reason\"\xc7\x01\n" +
	"\n" +
	"EntityMove\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1e\n" +
	"\x04from\x18\x02 \x01(\v2\n" +
	".mir2.Vec2R\x04from\x12\x1a\n" +
	"\x02to\x18\x03 \x01(\v2\n" +
	".mir2.Vec2R\x02to\x12-\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x0f.mir2.DirectionR\tdirection\x12\x1f\n" +
	"\vserver_tick\x18\x05 \x01(\rR\n" +
	"serverTick\x12\x10\n" +
	"\x03run\x18\x06 \x01(\bR\x03run\"d\n" +
	"\fEntityAction\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\rR\x06action\x12\x1f\n" +
	"\vserver_tick\x18\x03 \x01(\rR\n" +
	"serverTick\"R\n" +
	"\fEntityHealth\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\rR\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x03 \x01(\rR\x05maxHp\"L\n" +
	"\fEntityStatus\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1f\n" +
	"\vstatus_bits\x18\x02 \x01(\x04R\n" +
	"statusBits\"8\n" +
	"\rAbilityUpdate\x12'\n" +
	"\aability\x18\x01 \x01(\v2\r.mir2.AbilityR\aability\"\xa9\x01\n" +
	"\tMoveInput\x12\x1e\n" +
	"\x04from\x18\x01 \x01(\v2\n" +
	".mir2.Vec2R\x04from\x12\x1a\n" +
	"\x02to\x18\x02 \x01(\v2\n" +
	".mir2.Vec2R\x02to\x12-\n" +
	"\tdirection\x18\x03 \x01(\x0e2\x0f.mir2.DirectionR\tdirection\x12\x1f\n" +
	"\vclient_tick\x18\x04 \x01(\rR\n" +
	"clientTick\x12\x10\n" +
	"\x03run\x18\x05 \x01(\bR\x03run\"i\n" +
	"\fMoveRejected\x12A\n" +
	"\x16authoritative_position\x18\x01 \x01(\v2\n" +
	".mir2.Vec2R\x15authoritativePosition\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\rR\x06reason\"b\n" +
	"\x14EntityFeatureChanged\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12-\n" +
	"\afeature\x18\x02 \x01(\v2\x13.mir2.EntityFeatureR\afeature*\x8a\x01\n" +
	"\x0fDisappearReason\x12 \n" +
	"\x1cDISAPPEAR_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DISAPPEAR_LEFT_VIEW\x10\x01\x12\x12\n" +
	"\x0eDISAPPEAR_HIDE\x10\x02\x12\x12\n" +
	"\x0eDISAPPEAR_DEAD\x10\x03\x12\x14\n" +
	"\x10DISAPPEAR_LOGOUT\x10\x04B2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_scene_proto_rawDescOnce sync.Once
	file_scene_proto_rawDescData []byte
)

func file_scene_proto_rawDescGZIP() []byte {
	file_scene_proto_rawDescOnce.Do(func() {
		file_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)))
	})
	return file_scene_proto_rawDescData
}

var file_scene_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_scene_proto_goTypes = []any{
	(DisappearReason)(0),         // 0: mir2.DisappearReason
	(*EntityState)(nil),          // 1: mir2.EntityState
	(*EnterWorld)(nil),           // 2: mir2.EnterWorld
	(*ChangeMap)(nil),            // 3: mir2.ChangeMap
	(*MapChunk)(nil),             // 4: mir2.MapChunk
	(*TimeOfDay)(nil),            // 5: mir2.TimeOfDay
	(*MapDescription)(nil),       // 6: mir2.MapDescription
	(*EntityAppear)(nil),         // 7: mir2.EntityAppear
	(*EntityDisappear)(nil),      // 8: mir2.EntityDisappear
	(*EntityMove)(nil),           // 9: mir2.EntityMove
	(*EntityAction)(nil),         // 10: mir2.EntityAction
	(*EntityHealth)(nil),         // 11: mir2.EntityHealth
	(*EntityStatus)(nil),         // 12: mir2.EntityStatus
	(*AbilityUpdate)(nil),        // 13: mir2.AbilityUpdate
	(*MoveInput)(nil),            // 14: mir2.MoveInput
	(*MoveRejected)(nil),         // 15: mir2.MoveRejected
	(*EntityFeatureChanged)(nil), // 16: mir2.EntityFeatureChanged
	(*Vec2)(nil),                 // 17: mir2.Vec2
	(Direction)(0),               // 18: mir2.Direction
	(*EntityFeature)(nil),        // 19: mir2.EntityFeature
	(*Ability)(nil),              // 20: mir2.Ability
}
var file_scene_proto_depIdxs = []int32{
	17, // 0: mir2.EntityState.position:type_name -> mir2.Vec2
	18, // 1: mir2.EntityState.direction:type_name -> mir2.Direction
	19, // 2: mir2.EntityState.feature:type_name -> mir2.EntityFeature
	17, // 3: mir2.EnterWorld.position:type_name -> mir2.Vec2
	18, // 4: mir2.EnterWorld.direction:type_name -> mir2.Direction
	1,  // 5: mir2.EnterWorld.entities:type_name -> mir2.EntityState
	19, // 6: mir2.EnterWorld.self_feature:type_name -> mir2.EntityFeature
	17, // 7: mir2.ChangeMap.position:type_name -> mir2.Vec2
	1,  // 8: mir2.ChangeMap.entities:type_name -> mir2.EntityState
	19, // 9: mir2.ChangeMap.self_feature:type_name -> mir2.EntityFeature
	1,  // 10: mir2.EntityAppear.entity:type_name -> mir2.EntityState
	0,  // 11: mir2.EntityDisappear.reason:type_name -> mir2.DisappearReason
	17, // 12: mir2.EntityMove.from:type_name -> mir2.Vec2
	17, // 13: mir2.EntityMove.to:type_name -> mir2.Vec2
	18, // 14: mir2.EntityMove.direction:type_name -> mir2.Direction
	20, // 15: mir2.AbilityUpdate.ability:type_name -> mir2.Ability
	17, // 16: mir2.MoveInput.from:type_name -> mir2.Vec2
	17, // 17: mir2.MoveInput.to:type_name -> mir2.Vec2
	18, // 18: mir2.MoveInput.direction:type_name -> mir2.Direction
	17, // 19: mir2.MoveRejected.authoritative_position:type_name -> mir2.Vec2
	19, // 20: mir2.EntityFeatureChanged.feature:type_name -> mir2.EntityFeature
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_scene_proto_init() }
func file_scene_proto_init() {
	if File_scene_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_proto_goTypes,
		DependencyIndexes: file_scene_proto_depIdxs,
		EnumInfos:         file_scene_proto_enumTypes,
		MessageInfos:      file_scene_proto_msgTypes,
	}.Build()
	File_scene_proto = out.File
	file_scene_proto_goTypes = nil
	file_scene_proto_depIdxs = nil
}
