// MIR2 协议 · 0x09xx 聊天（0x0Axx 社交待定）
//
// 原版把聊天拆成 SM_HEAR(40)/SM_SYSMESSAGE(100)/SM_GROUPMESSAGE(101)/SM_CRY(102)/
// SM_WHISPER(103)/SM_GUILDMESSAGE(104) 六条消息；自研协议合并为
// **一个 ChatInput + 一个 ChatMessage + 一个 channel 枚举**。
//
// ⚠️ 0x0Axx（组队 / 行会 / 好友 / 黑名单 / 邮件 / 备忘录）**尚未定稿**：
//   docs/messages.md §5 已确认「邮件/好友/黑名单/备忘录」在本版协议里**零消息**、
//   客户端也零引用 ⇒ 按 plan.md §1「不做遗留客户端里没有的东西」，暂不设计；
//   组队/行会是 1.76 核心玩法，需单独一轮（用 M0 清单的 T1 可达集驱动）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: social.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatChannel int32

const (
	ChatChannel_CHAT_CHANNEL_UNSPECIFIED ChatChannel = 0
	ChatChannel_CHAT_SAY                 ChatChannel = 1 // 普通说话（原版 SM_HEAR）
	ChatChannel_CHAT_CRY                 ChatChannel = 2 // 喊话（原版 SM_CRY）
	ChatChannel_CHAT_WHISPER             ChatChannel = 3 // 私聊（原版 SM_WHISPER）
	ChatChannel_CHAT_GROUP               ChatChannel = 4 // 组队（原版 SM_GROUPMESSAGE）
	ChatChannel_CHAT_GUILD               ChatChannel = 5 // 行会（原版 SM_GUILDMESSAGE）
	ChatChannel_CHAT_SYSTEM              ChatChannel = 6 // 系统（原版 SM_SYSMESSAGE）
)

// Enum value maps for ChatChannel.
var (
	ChatChannel_name = map[int32]string{
		0: "CHAT_CHANNEL_UNSPECIFIED",
		1: "CHAT_SAY",
		2: "CHAT_CRY",
		3: "CHAT_WHISPER",
		4: "CHAT_GROUP",
		5: "CHAT_GUILD",
		6: "CHAT_SYSTEM",
	}
	ChatChannel_value = map[string]int32{
		"CHAT_CHANNEL_UNSPECIFIED": 0,
		"CHAT_SAY":                 1,
		"CHAT_CRY":                 2,
		"CHAT_WHISPER":             3,
		"CHAT_GROUP":               4,
		"CHAT_GUILD":               5,
		"CHAT_SYSTEM":              6,
	}
)

func (x ChatChannel) Enum() *ChatChannel {
	p := new(ChatChannel)
	*p = x
	return p
}

func (x ChatChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_social_proto_enumTypes[0].Descriptor()
}

func (ChatChannel) Type() protoreflect.EnumType {
	return &file_social_proto_enumTypes[0]
}

func (x ChatChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatChannel.Descriptor instead.
func (ChatChannel) EnumDescriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{0}
}

// 客户端 → 服务端
type ChatInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       ChatChannel            `protobuf:"varint,1,opt,name=channel,proto3,enum=mir2.ChatChannel" json:"channel,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TargetName    string                 `protobuf:"bytes,3,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"` // 私聊目标（channel = CHAT_WHISPER 时有效）
	ClientTick    uint32                 `protobuf:"varint,4,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInput) Reset() {
	*x = ChatInput{}
	mi := &file_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInput) ProtoMessage() {}

func (x *ChatInput) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInput.ProtoReflect.Descriptor instead.
func (*ChatInput) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{0}
}

func (x *ChatInput) GetChannel() ChatChannel {
	if x != nil {
		return x.Channel
	}
	return ChatChannel_CHAT_CHANNEL_UNSPECIFIED
}

func (x *ChatInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatInput) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *ChatInput) GetClientTick() uint32 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

// 服务端 → 客户端（原版 SM_HEAR 带前景/背景色）
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       ChatChannel            `protobuf:"varint,1,opt,name=channel,proto3,enum=mir2.ChatChannel" json:"channel,omitempty"`
	SenderId      uint64                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // 0 = 系统
	SenderName    string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Color         uint32                 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_social_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetChannel() ChatChannel {
	if x != nil {
		return x.Channel
	}
	return ChatChannel_CHAT_CHANNEL_UNSPECIFIED
}

func (x *ChatMessage) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_social_proto protoreflect.FileDescriptor

const file_social_proto_rawDesc = "" +
	"\n" +
	"\fsocial.proto\x12\x04mir2\"\x8e\x01\n" +
	"\tChatInput\x12+\n" +
	"\achannel\x18\x01 \x01(\x0e2\x11.mir2.ChatChannelR\achannel\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1f\n" +
	"\vtarget_name\x18\x03 \x01(\tR\n" +
	"targetName\x12\x1f\n" +
	"\vclient_tick\x18\x04 \x01(\rR\n" +
	"clientTick\"\xa2\x01\n" +
	"\vChatMessage\x12+\n" +
	"\achannel\x18\x01 \x01(\x0e2\x11.mir2.ChatChannelR\achannel\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x04R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05color\x18\x05 \x01(\rR\x05color*\x8a\x01\n" +
	"\vChatChannel\x12\x1c\n" +
	"\x18CHAT_CHANNEL_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCHAT_SAY\x10\x01\x12\f\n" +
	"\bCHAT_CRY\x10\x02\x12\x10\n" +
	"\fCHAT_WHISPER\x10\x03\x12\x0e\n" +
	"\n" +
	"CHAT_GROUP\x10\x04\x12\x0e\n" +
	"\n" +
	"CHAT_GUILD\x10\x05\x12\x0f\n" +
	"\vCHAT_SYSTEM\x10\x06B2Z0github.com/algotao/mir2/server/protocol;protocolb\x06proto3"

var (
	file_social_proto_rawDescOnce sync.Once
	file_social_proto_rawDescData []byte
)

func file_social_proto_rawDescGZIP() []byte {
	file_social_proto_rawDescOnce.Do(func() {
		file_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)))
	})
	return file_social_proto_rawDescData
}

var file_social_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_social_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_social_proto_goTypes = []any{
	(ChatChannel)(0),    // 0: mir2.ChatChannel
	(*ChatInput)(nil),   // 1: mir2.ChatInput
	(*ChatMessage)(nil), // 2: mir2.ChatMessage
}
var file_social_proto_depIdxs = []int32{
	0, // 0: mir2.ChatInput.channel:type_name -> mir2.ChatChannel
	0, // 1: mir2.ChatMessage.channel:type_name -> mir2.ChatChannel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_social_proto_init() }
func file_social_proto_init() {
	if File_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_social_proto_rawDesc), len(file_social_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_proto_goTypes,
		DependencyIndexes: file_social_proto_depIdxs,
		EnumInfos:         file_social_proto_enumTypes,
		MessageInfos:      file_social_proto_msgTypes,
	}.Build()
	File_social_proto = out.File
	file_social_proto_goTypes = nil
	file_social_proto_depIdxs = nil
}
