// Code generated by protocol/gen.sh from protocol/version.txt. DO NOT EDIT.
//
// 协议版本号（握手用）：见 docs/protocol.md §5 与 §9.4。
// schema 变更必须同时 bump protocol/version.txt 并重跑本脚本。
package protocol

// Version 与 protocol/version.txt 对应。
const Version uint32 = 4
